platform :ios, '16.0'

project 'ExampleApp.xcodeproj'

flutter_application_path = '../example_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'ExampleApp' do
  use_frameworks!
  use_modular_headers!

  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
