name: ExampleApp
options:
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "16.0"

targets:
  ExampleApp:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: ../example_module/example_module_native/ios/Classes/Generated
    resources:
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: co.leancode.inlay.example.ios
        INFOPLIST_FILE: Resources/Info.plist
        SWIFT_VERSION: 5.9
