name: signal_module
description: "Flutter module for Signal app add2app PoC"
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  custom_lint: ^0.7.6
  flutter_test:
    sdk: flutter
  leancode_lint: ^17.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/wallpapers/

  module:
    androidX: true
    androidPackage: co.leancode.signal_module
    iosBundleIdentifier: co.leancode.signalModule
