name: signal_module
description: "Flutter module for Signal app add2app PoC"
publish_to: none
resolution: workspace

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  leancode_add2app:
    path: ../leancode_add2app

dev_dependencies:
  build_runner: ^2.11.0
  flutter_test:
    sdk: flutter
  leancode_add2app_gen:
    path: ../leancode_add2app_gen
  leancode_lint: ^21.0.0
  pigeon: ^26.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/wallpapers/

  module:
    androidX: true
    androidPackage: co.leancode.signal_module
    iosBundleIdentifier: co.leancode.signalModule
