name: add2app_framework_poc
publish_to: none

environment:
  sdk: ^3.11.0

workspace:
  - leancode_add2app
  - leancode_add2app_gen
  - signal_module

dependency_overrides:
  meta: ^1.18.0
  analyzer: ^10.0.0
  dart_style: ^3.1.4
