name: inlay
publish_to: none

environment:
  sdk: ^3.11.0

workspace:
  - inlay
  - inlay_gen
  - example/example_module
  - example/example_module/example_module_native

dependency_overrides:
  meta: ^1.18.0
  analyzer: ^10.0.0
  dart_style: ^3.1.4
