// GENERATED CODE — DO NOT MODIFY BY HAND
// Generated by leancode_add2app_gen

import 'package:leancode_add2app/leancode_add2app.dart';

class SoundsNotificationsPage extends Add2AppFlutterRoute {
  const SoundsNotificationsPage({required this.contactId});

  final String contactId;

  @override
  String get routeId => 'soundsNotifications';

  @override
  Map<String, String> get params => {
    'contactId': contactId,
  };
}

class SetWallpaperPage extends Add2AppFlutterRoute {
  const SetWallpaperPage({this.recipientId});

  final String? recipientId;

  @override
  String get routeId => 'setWallpaper';

  @override
  Map<String, String> get params => {
    ...?recipientId != null ? {'recipientId': recipientId!} : null,
  };
}

class ContactDetailsPage extends Add2AppFlutterRoute {
  const ContactDetailsPage({required this.contactId});

  final String contactId;

  @override
  String get routeId => 'contactDetails';

  @override
  Map<String, String> get params => {
    'contactId': contactId,
  };
}

