// GENERATED CODE — DO NOT MODIFY BY HAND
// Generated by leancode_add2app_gen

import 'package:flutter/widgets.dart';
import 'package:leancode_add2app/leancode_add2app.dart';

class SoundsNotificationsPage extends Add2AppFlutterRoute {
  const SoundsNotificationsPage({required this.contactId});

  final String contactId;

  static const String routeName = 'soundsNotifications';

  static SoundsNotificationsPage fromParams(Map<String, String> params) {
    return SoundsNotificationsPage(
      contactId:
          params['contactId'] ??
          (throw ArgumentError(
            'Missing required param contactId for SoundsNotificationsPage',
          )),
    );
  }

  @override
  String get routeId => routeName;

  @override
  Map<String, String> get params => {'contactId': contactId};
}

class SetWallpaperPage extends Add2AppFlutterRoute {
  const SetWallpaperPage({this.recipientId});

  final String? recipientId;

  static const String routeName = 'setWallpaper';

  static SetWallpaperPage fromParams(Map<String, String> params) {
    return SetWallpaperPage(recipientId: params['recipientId']);
  }

  @override
  String get routeId => routeName;

  @override
  Map<String, String> get params => {
    ...?recipientId != null ? {'recipientId': recipientId!} : null,
  };
}

class ContactDetailsPage extends Add2AppFlutterRoute {
  const ContactDetailsPage({required this.contactId});

  final String contactId;

  static const String routeName = 'contactDetails';

  static ContactDetailsPage fromParams(Map<String, String> params) {
    return ContactDetailsPage(
      contactId:
          params['contactId'] ??
          (throw ArgumentError(
            'Missing required param contactId for ContactDetailsPage',
          )),
    );
  }

  @override
  String get routeId => routeName;

  @override
  Map<String, String> get params => {'contactId': contactId};
}

abstract class FlutterRouteHandler {
  const FlutterRouteHandler();

  Widget handle(PageSettings route) {
    switch (route.routeId) {
      case 'soundsNotifications':
        return onSoundsNotifications(
          SoundsNotificationsPage.fromParams(_asMap(route.params)),
        );
      case 'setWallpaper':
        return onSetWallpaper(
          SetWallpaperPage.fromParams(_asMap(route.params)),
        );
      case 'contactDetails':
        return onContactDetails(
          ContactDetailsPage.fromParams(_asMap(route.params)),
        );
      default:
        return onUnknownRoute(route);
    }
  }

  Widget onSoundsNotifications(SoundsNotificationsPage page);
  Widget onSetWallpaper(SetWallpaperPage page);
  Widget onContactDetails(ContactDetailsPage page);

  Widget onUnknownRoute(PageSettings route) {
    return Center(child: Text('Unknown route: ${route.routeId}'));
  }

  static Map<String, String> _asMap(Object? raw) => raw is Map<String, String>
      ? raw
      : (raw is Map ? Map<String, String>.from(raw) : const {});
}
