// GENERATED CODE — DO NOT MODIFY BY HAND
// Generated by leancode_add2app_gen

import 'package:leancode_add2app/leancode_add2app.dart' show PageSettings;
import 'pages.g.dart';

extension NativeEditProfilePageToPageSettings on NativeEditProfilePage {
  static const String routeId = 'nativeEditProfile';

  PageSettings toPageSettings() {
    return PageSettings(routeId: 'nativeEditProfile', params: encode());
  }
}

extension NativeMediaViewerPageToPageSettings on NativeMediaViewerPage {
  static const String routeId = 'nativeMediaViewer';

  PageSettings toPageSettings() {
    return PageSettings(routeId: 'nativeMediaViewer', params: encode());
  }
}

