// GENERATED CODE — DO NOT MODIFY BY HAND
// Generated by leancode_add2app_gen

import 'package:leancode_add2app/leancode_add2app.dart' show Add2AppNativeRoute, PageSettings;
import 'pages.g.dart';

extension NativeEditProfilePageToNativeRoute on NativeEditProfilePage {
  static const String routeId = 'nativeEditProfile';

  Add2AppNativeRoute toNativeRoute() {
    return Add2AppNativeRoute(
      PageSettings(routeId: 'nativeEditProfile', params: encode()),
    );
  }
}

extension NativeMediaViewerPageToNativeRoute on NativeMediaViewerPage {
  static const String routeId = 'nativeMediaViewer';

  Add2AppNativeRoute toNativeRoute() {
    return Add2AppNativeRoute(
      PageSettings(routeId: 'nativeMediaViewer', params: encode()),
    );
  }
}

