// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


/// Page settings for the Sounds & Notifications screen.
class SoundsNotificationsPage {
  SoundsNotificationsPage({
    required this.contactId,
  });

  String contactId;

  List<Object?> _toList() {
    return <Object?>[
      contactId,
    ];
  }

  Object encode() {
    return _toList();  }

  static SoundsNotificationsPage decode(Object result) {
    result as List<Object?>;
    return SoundsNotificationsPage(
      contactId: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SoundsNotificationsPage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class SetWallpaperPage {
  SetWallpaperPage({
    required this.recipientId,
  });

  String recipientId;

  List<Object?> _toList() {
    return <Object?>[
      recipientId,
    ];
  }

  Object encode() {
    return _toList();  }

  static SetWallpaperPage decode(Object result) {
    result as List<Object?>;
    return SetWallpaperPage(
      recipientId: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SetWallpaperPage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class ContactDetailsPage {
  ContactDetailsPage({
    required this.contactId,
  });

  String contactId;

  List<Object?> _toList() {
    return <Object?>[
      contactId,
    ];
  }

  Object encode() {
    return _toList();  }

  static ContactDetailsPage decode(Object result) {
    result as List<Object?>;
    return ContactDetailsPage(
      contactId: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ContactDetailsPage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class NativeEditProfilePage {
  NativeEditProfilePage({
    required this.contactId,
  });

  String contactId;

  List<Object?> _toList() {
    return <Object?>[
      contactId,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeEditProfilePage decode(Object result) {
    result as List<Object?>;
    return NativeEditProfilePage(
      contactId: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeEditProfilePage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class NativeMediaViewerPage {
  NativeMediaViewerPage({
    required this.mediaId,
    this.mediaType,
  });

  String mediaId;

  String? mediaType;

  List<Object?> _toList() {
    return <Object?>[
      mediaId,
      mediaType,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeMediaViewerPage decode(Object result) {
    result as List<Object?>;
    return NativeMediaViewerPage(
      mediaId: result[0]! as String,
      mediaType: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeMediaViewerPage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is SoundsNotificationsPage) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is SetWallpaperPage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is ContactDetailsPage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is NativeEditProfilePage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is NativeMediaViewerPage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return SoundsNotificationsPage.decode(readValue(buffer)!);
      case 130: 
        return SetWallpaperPage.decode(readValue(buffer)!);
      case 131: 
        return ContactDetailsPage.decode(readValue(buffer)!);
      case 132: 
        return NativeEditProfilePage.decode(readValue(buffer)!);
      case 133: 
        return NativeMediaViewerPage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}
