// GENERATED CODE — DO NOT MODIFY BY HAND
// Generated by inlay_gen

package co.leancode.example_module.javagen;

import co.leancode.inlay.FlutterDialogRouteWithResult;
import co.leancode.inlay.navigator.PageSettings;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;

public final class ConfirmActionDialog implements FlutterDialogRouteWithResult<Boolean> {
    public static final String ROUTE_NAME = "confirmActionDialog";
    public static final String PATH_TEMPLATE = "/confirm-action/:action";

    private final String action;
    private final String message;

    public ConfirmActionDialog(
            String action,
            String message
    ) {
        this.action = action;
        this.message = message;
    }

    public String getAction() {
        return action;
    }

    public String getMessage() {
        return message;
    }

    @SuppressWarnings("unchecked")
    public static ConfirmActionDialog fromList(List<Object> list) {
        return new ConfirmActionDialog(
                (String) list.get(0),
                list.get(1) == null ? null : (String) list.get(1)
        );
    }

    public List<Object> toList() {
        return Arrays.asList(
                action,
                message
        );
    }

    public String toPath() {
        final String basePath = "/confirm-action/" + encodeRouteParam(String.valueOf(action));
        final List<String> query = new ArrayList<>();
        if (message != null) {
            query.add("message=" + encodeRouteParam(String.valueOf(message)));
        }
        if (query.isEmpty()) {
            return basePath;
        }
        return basePath + "?" + String.join("&", query);
    }

    private static String encodeRouteParam(String value) {
        try {
            return java.net.URLEncoder.encode(value, "UTF-8");
        } catch (java.io.UnsupportedEncodingException e) {
            throw new AssertionError(e);
        }
    }

    @Override
    public PageSettings toPageSettings() {
        return new PageSettings(ROUTE_NAME, toList(), toPath(), InlaySchema.FINGERPRINT);
    }

    public static Object encodeResult(Boolean result) {
        return result;
    }

    @Override
    public Boolean decodeResult(Object raw) {
        return raw == null ? null : (Boolean) raw;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        final ConfirmActionDialog that = (ConfirmActionDialog) o;
        return Objects.deepEquals(action, that.action)
                && Objects.deepEquals(message, that.message);
    }

    @Override
    public int hashCode() {
        return Arrays.deepHashCode(new Object[] {action, message});
    }
}
