// GENERATED CODE — DO NOT MODIFY BY HAND
// Generated by inlay_gen

package co.leancode.example_module.javagen;

import co.leancode.inlay.FlutterRouteWithResult;
import co.leancode.inlay.navigator.PageSettings;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;

public final class CounterPage implements FlutterRouteWithResult<Long> {
    public static final String ROUTE_NAME = "/counter";
    public static final String PATH_TEMPLATE = "/counter";

    private final Long seed;

    public CounterPage(
            Long seed
    ) {
        this.seed = seed;
    }

    public Long getSeed() {
        return seed;
    }

    @SuppressWarnings("unchecked")
    public static CounterPage fromList(List<Object> list) {
        return new CounterPage(
                list.get(0) == null ? null : ((Number) list.get(0)).longValue()
        );
    }

    public List<Object> toList() {
        return Arrays.asList(
                seed
        );
    }

    public String toPath() {
        final String basePath = "/counter";
        final List<String> query = new ArrayList<>();
        if (seed != null) {
            query.add("seed=" + encodeRouteParam(String.valueOf(seed)));
        }
        if (query.isEmpty()) {
            return basePath;
        }
        return basePath + "?" + String.join("&", query);
    }

    private static String encodeRouteParam(String value) {
        try {
            return java.net.URLEncoder.encode(value, "UTF-8");
        } catch (java.io.UnsupportedEncodingException e) {
            throw new AssertionError(e);
        }
    }

    @Override
    public PageSettings toPageSettings() {
        return new PageSettings(ROUTE_NAME, toList(), toPath(), InlaySchema.FINGERPRINT);
    }

    public static Object encodeResult(Long result) {
        return result;
    }

    @Override
    public Long decodeResult(Object raw) {
        return raw == null ? null : ((Number) raw).longValue();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        final CounterPage that = (CounterPage) o;
        return Objects.deepEquals(seed, that.seed);
    }

    @Override
    public int hashCode() {
        return Arrays.deepHashCode(new Object[] {seed});
    }
}
