// GENERATED CODE — DO NOT MODIFY BY HAND
// Generated by inlay_gen

package co.leancode.example_module.javagen;

import co.leancode.inlay.FlutterRoute;
import co.leancode.inlay.navigator.PageSettings;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;

public final class GreetingPage implements FlutterRoute {
    public static final String ROUTE_NAME = "/greeting/:name";
    public static final String PATH_TEMPLATE = "/greeting/:name";

    private final String name;
    private final GreetingStyle style;

    public GreetingPage(
            String name,
            GreetingStyle style
    ) {
        this.name = name;
        this.style = style;
    }

    public String getName() {
        return name;
    }

    public GreetingStyle getStyle() {
        return style;
    }

    @SuppressWarnings("unchecked")
    public static GreetingPage fromList(List<Object> list) {
        return new GreetingPage(
                (String) list.get(0),
                list.get(1) == null ? null : GreetingStyle.values()[((Number) list.get(1)).intValue()]
        );
    }

    public List<Object> toList() {
        return Arrays.asList(
                name,
                style == null ? null : style.ordinal()
        );
    }

    public String toPath() {
        final String basePath = "/greeting/" + encodeRouteParam(String.valueOf(name));
        final List<String> query = new ArrayList<>();
        if (style != null) {
            query.add("style=" + encodeRouteParam(String.valueOf(style)));
        }
        if (query.isEmpty()) {
            return basePath;
        }
        return basePath + "?" + String.join("&", query);
    }

    private static String encodeRouteParam(String value) {
        try {
            return java.net.URLEncoder.encode(value, "UTF-8");
        } catch (java.io.UnsupportedEncodingException e) {
            throw new AssertionError(e);
        }
    }

    @Override
    public PageSettings toPageSettings() {
        return new PageSettings(ROUTE_NAME, toList(), toPath(), InlaySchema.FINGERPRINT);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        final GreetingPage that = (GreetingPage) o;
        return Objects.deepEquals(name, that.name)
                && Objects.deepEquals(style, that.style);
    }

    @Override
    public int hashCode() {
        return Arrays.deepHashCode(new Object[] {name, style});
    }
}
