// GENERATED CODE — DO NOT MODIFY BY HAND
// Generated by inlay_gen

package co.leancode.example_module.javagen;

import co.leancode.inlay.navigator.PageSettings;

/**
 * Fingerprint of the schema this code was generated from.
 *
 * Embedded into every outgoing {@code PageSettings} and verified by the
 * generated route handler, so host/module schema drift fails fast.
 */
public final class InlaySchema {
    public static final String FINGERPRINT = "231397b50962578d";

    private InlaySchema() {}
}
