// GENERATED CODE — DO NOT MODIFY BY HAND
// Generated by inlay_gen

package co.leancode.example_module.javagen;

import android.content.Context;
import co.leancode.inlay.navigator.PageSettings;
import java.util.List;
import java.util.function.Consumer;
import kotlin.Unit;
import kotlin.jvm.functions.Function1;

/**
 * Base class for handling native routes pushed from Flutter.
 *
 * Extend it and implement the typed {@code on*} methods; register the
 * instance with {@code InlayNavigator.INSTANCE.setNativeRouteHandler(...)}.
 */
public abstract class NativeRouteHandler implements co.leancode.inlay.NativeRouteHandler {

    @Override
    @SuppressWarnings("unchecked")
    public void handle(Context context, PageSettings route, Function1<Object, Unit> completion) {
        final String remote = route.getSchemaFingerprint();
        if (remote != null && !remote.equals(InlaySchema.FINGERPRINT)) {
            throw new IllegalStateException(
                    "Inlay schema mismatch: the Flutter module sent a route generated "
                            + "from schema " + remote + ", but this host was built against schema "
                            + InlaySchema.FINGERPRINT + ". Re-run inlay_gen and rebuild both sides "
                            + "from the same schema revision.");
        }
        switch (route.getRouteId()) {
            case NativeSettingsPage.ROUTE_NAME:
                onNativeSettings(NativeSettingsPage.fromList((List<Object>) route.getParams()), context);
                completion.invoke(null);
                break;
            case NativeAboutPage.ROUTE_NAME:
                onNativeAbout(NativeAboutPage.fromList((List<Object>) route.getParams()), context, result -> completion.invoke(NativeAboutPage.encodeResult(result)));
                break;
            default:
                onUnknownRoute(route, context);
                completion.invoke(null);
                break;
        }
    }

    public abstract void onNativeSettings(NativeSettingsPage page, Context context);
    public abstract void onNativeAbout(NativeAboutPage page, Context context, Consumer<String> completion);

    public void onUnknownRoute(PageSettings route, Context context) {
        throw new IllegalArgumentException("Unknown route: " + route.getRouteId());
    }
}
