// GENERATED CODE — DO NOT MODIFY BY HAND
// Generated by inlay_gen

package co.leancode.example_module.javagen;

import java.util.Arrays;
import java.util.List;
import java.util.Objects;

public final class NativeSettingsPage {
    public static final String ROUTE_NAME = "nativeSettings";

    private final String source;

    public NativeSettingsPage(
            String source
    ) {
        this.source = source;
    }

    public String getSource() {
        return source;
    }

    @SuppressWarnings("unchecked")
    public static NativeSettingsPage fromList(List<Object> list) {
        return new NativeSettingsPage(
                list.get(0) == null ? null : (String) list.get(0)
        );
    }

    public List<Object> toList() {
        return Arrays.asList(
                source
        );
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        final NativeSettingsPage that = (NativeSettingsPage) o;
        return Objects.deepEquals(source, that.source);
    }

    @Override
    public int hashCode() {
        return Arrays.deepHashCode(new Object[] {source});
    }
}
