// GENERATED CODE — DO NOT MODIFY BY HAND
// Generated by inlay_gen

package co.leancode.example_module.javagen;

import java.util.Arrays;
import java.util.List;
import java.util.Objects;

public final class NativeAboutPage {
    public static final String ROUTE_NAME = "nativeAbout";

    private final String appVersion;

    public NativeAboutPage(
            String appVersion
    ) {
        this.appVersion = appVersion;
    }

    public String getAppVersion() {
        return appVersion;
    }

    @SuppressWarnings("unchecked")
    public static NativeAboutPage fromList(List<Object> list) {
        return new NativeAboutPage(
                (String) list.get(0)
        );
    }

    public List<Object> toList() {
        return Arrays.asList(
                appVersion
        );
    }

    public static Object encodeResult(String result) {
        return result;
    }

    public static String decodeResult(Object raw) {
        return raw == null ? null : (String) raw;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        final NativeAboutPage that = (NativeAboutPage) o;
        return Objects.deepEquals(appVersion, that.appVersion);
    }

    @Override
    public int hashCode() {
        return Arrays.deepHashCode(new Object[] {appVersion});
    }
}
