// GENERATED CODE — DO NOT MODIFY BY HAND
// Generated by inlay_gen

package co.leancode.example_module.javagen;

import co.leancode.inlay.FlutterRoute;
import co.leancode.inlay.navigator.PageSettings;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

public final class ProfilePage implements FlutterRoute {
    public static final String ROUTE_NAME = "/profile/:userId";
    public static final String PATH_TEMPLATE = "/profile/:userId";

    private final String userId;
    private final List<UserBadge> badges;

    public ProfilePage(
            String userId,
            List<UserBadge> badges
    ) {
        this.userId = userId;
        this.badges = badges;
    }

    public String getUserId() {
        return userId;
    }

    public List<UserBadge> getBadges() {
        return badges;
    }

    @SuppressWarnings("unchecked")
    public static ProfilePage fromList(List<Object> list) {
        return new ProfilePage(
                (String) list.get(0),
                list.get(1) == null ? null : ((List<Object>) list.get(1)).stream().map(it -> UserBadge.fromList((List<Object>) it)).collect(Collectors.toList())
        );
    }

    public List<Object> toList() {
        return Arrays.asList(
                userId,
                badges == null ? null : badges.stream().map(it -> it.toList()).collect(Collectors.toList())
        );
    }

    public String toPath() {
        return "/profile/" + encodeRouteParam(String.valueOf(userId));
    }

    private static String encodeRouteParam(String value) {
        try {
            return java.net.URLEncoder.encode(value, "UTF-8");
        } catch (java.io.UnsupportedEncodingException e) {
            throw new AssertionError(e);
        }
    }

    @Override
    public PageSettings toPageSettings() {
        return new PageSettings(ROUTE_NAME, toList(), toPath(), InlaySchema.FINGERPRINT);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        final ProfilePage that = (ProfilePage) o;
        return Objects.deepEquals(userId, that.userId)
                && Objects.deepEquals(badges, that.badges);
    }

    @Override
    public int hashCode() {
        return Arrays.deepHashCode(new Object[] {userId, badges});
    }
}
