// GENERATED CODE — DO NOT MODIFY BY HAND
// Generated by inlay_gen

package co.leancode.example_module.javagen;

import co.leancode.inlay.FlutterDialogRoute;
import co.leancode.inlay.navigator.PageSettings;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;

public final class ThemePickerDialog implements FlutterDialogRoute {
    public static final String ROUTE_NAME = "themePickerDialog";
    public static final String PATH_TEMPLATE = "/theme-picker/:userId";

    private final String userId;

    public ThemePickerDialog(
            String userId
    ) {
        this.userId = userId;
    }

    public String getUserId() {
        return userId;
    }

    @SuppressWarnings("unchecked")
    public static ThemePickerDialog fromList(List<Object> list) {
        return new ThemePickerDialog(
                (String) list.get(0)
        );
    }

    public List<Object> toList() {
        return Arrays.asList(
                userId
        );
    }

    public String toPath() {
        return "/theme-picker/" + encodeRouteParam(String.valueOf(userId));
    }

    private static String encodeRouteParam(String value) {
        try {
            return java.net.URLEncoder.encode(value, "UTF-8");
        } catch (java.io.UnsupportedEncodingException e) {
            throw new AssertionError(e);
        }
    }

    @Override
    public PageSettings toPageSettings() {
        return new PageSettings(ROUTE_NAME, toList(), toPath(), InlaySchema.FINGERPRINT);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        final ThemePickerDialog that = (ThemePickerDialog) o;
        return Objects.deepEquals(userId, that.userId);
    }

    @Override
    public int hashCode() {
        return Arrays.deepHashCode(new Object[] {userId});
    }
}
