// GENERATED CODE — DO NOT MODIFY BY HAND
// Generated by inlay_gen

package co.leancode.example_module.javagen;

import java.util.Arrays;
import java.util.List;
import java.util.Objects;

public final class UserBadge {
    private final String label;
    private final BadgeLevel level;

    public UserBadge(
            String label,
            BadgeLevel level
    ) {
        this.label = label;
        this.level = level;
    }

    public String getLabel() {
        return label;
    }

    public BadgeLevel getLevel() {
        return level;
    }

    @SuppressWarnings("unchecked")
    public static UserBadge fromList(List<Object> list) {
        return new UserBadge(
                (String) list.get(0),
                BadgeLevel.values()[((Number) list.get(1)).intValue()]
        );
    }

    public List<Object> toList() {
        return Arrays.asList(
                label,
                level.ordinal()
        );
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        final UserBadge that = (UserBadge) o;
        return Objects.deepEquals(label, that.label)
                && Objects.deepEquals(level, that.level);
    }

    @Override
    public int hashCode() {
        return Arrays.deepHashCode(new Object[] {label, level});
    }
}
