name: leancode_add2app
description: "A lightweight add2app framework for seamless Flutter-native integration"
version: 0.0.1
homepage: https://leancode.co

environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  custom_lint: ^0.7.6
  flutter_test:
    sdk: flutter
  leancode_lint: ^17.0.0

flutter:
  plugin:
    platforms:
      android:
        package: co.leancode.leancode_add2app
        pluginClass: LeancodeAdd2appPlugin
      ios:
        pluginClass: LeancodeAdd2appPlugin
