import 'package:leancode_add2app_gen/src/generators/dart/dart_routes_generator.dart'
    show extractPathParamNames, isSimpleType;
import 'package:leancode_add2app_gen/src/generators/kotlin/kotlin_serialization.dart';
import 'package:leancode_add2app_gen/src/models/data_type_definition.dart';
import 'package:leancode_add2app_gen/src/models/route_definition.dart';
import 'package:leancode_add2app_gen/src/models/schema.dart';
import 'package:leancode_add2app_gen/src/models/type_info.dart';
import 'package:leancode_add2app_gen/src/parser/type_resolver.dart';
import 'package:leancode_add2app_gen/src/utils/naming.dart';

/// Generates Kotlin code for routes from a resolved schema.
///
/// Produces:
/// - Data classes for routes with toList()/fromList() serialization
/// - Data classes for shared types
/// - Enum classes
/// - NativeRouteHandler base class
String generateKotlinRoutes({
  required Schema schema,
  required Map<String, TypeDefinition> typeGraph,
  required String packageName,
}) {
  final hasFlutterRoutes = schema.flutterRoutes.isNotEmpty;
  final buffer = StringBuffer()
    // Header.
    ..writeln('// GENERATED CODE — DO NOT MODIFY BY HAND')
    ..writeln('// Generated by leancode_add2app_gen')
    ..writeln()
    ..writeln('package $packageName')
    ..writeln()
    ..writeln('import android.content.Context')
    ..writeln('import android.net.Uri');
  if (hasFlutterRoutes) {
    buffer.writeln('import co.leancode.add2app.FlutterRoute');
  }
  buffer
    ..writeln('import co.leancode.add2app.NativeRouteHandler as NativeRouteHandling')
    ..writeln('import co.leancode.add2app.navigator.PageSettings')
    ..writeln();

  // Generate enums.
  for (final enumDef in schema.enums) {
    _writeEnum(buffer, enumDef);
    buffer.writeln();
  }

  // Generate data classes for shared types.
  for (final dataClass in schema.dataClasses) {
    _writeDataClass(buffer, dataClass, typeGraph);
    buffer.writeln();
  }

  // Generate data classes for Flutter routes.
  for (final route in schema.flutterRoutes) {
    _writeRouteDataClass(buffer, route, typeGraph);
    buffer.writeln();
  }

  // Generate data classes for native routes.
  for (final route in schema.nativeRoutes) {
    _writeRouteDataClass(buffer, route, typeGraph);
    buffer.writeln();
  }

  // Generate NativeRouteHandler if there are native routes.
  if (schema.nativeRoutes.isNotEmpty) {
    _writeNativeRouteHandler(buffer, schema.nativeRoutes);
  }

  final output = buffer.toString();
  return output.endsWith('\n') ? output : '$output\n';
}

void _writeEnum(StringBuffer buffer, EnumDefinition enumDef) {
  buffer.writeln('enum class ${enumDef.name} {');
  for (var i = 0; i < enumDef.values.length; i++) {
    final value = enumDef.values[i];
    if (i < enumDef.values.length - 1) {
      buffer.writeln('    $value,');
    } else {
      buffer.writeln('    $value');
    }
  }
  buffer.writeln('}');
}

void _writeDataClass(
  StringBuffer buffer,
  DataClassDefinition dataClass,
  Map<String, TypeDefinition> typeGraph,
) {
  final className = dataClass.className;
  final fields = dataClass.fields;

  _writeDataClassWithFields(buffer, className, fields, typeGraph);
}

void _writeRouteDataClass(
  StringBuffer buffer,
  RouteDefinition route,
  Map<String, TypeDefinition> typeGraph,
) {
  final className = route.className;
  final fields = route.fields;
  final isFlutterRoute = route.routeType == RouteType.flutter;
  final path = route.path;

  buffer.write('data class $className(');
  if (fields.isNotEmpty) {
    buffer.writeln();
    for (var i = 0; i < fields.length; i++) {
      final field = fields[i];
      final kotlinType = dartTypeToKotlin(field.type);
      final comma = i < fields.length - 1 ? ',' : '';
      buffer.writeln('    val ${field.name}: $kotlinType$comma');
    }
  }

  // Flutter routes implement FlutterRoute interface.
  if (isFlutterRoute) {
    buffer.writeln(') : FlutterRoute {');
  } else {
    buffer.writeln(') {');
  }

  // Route name constant + path template.
  buffer
    ..writeln('    companion object {')
    ..writeln('        const val ROUTE_NAME = "${route.routeName}"');
  if (path != null) {
    buffer.writeln('        const val PATH_TEMPLATE = "$path"');
  }
  buffer
    ..writeln()
    ..writeln(
      '        ${generateKotlinFromListMethod(className, fields, typeGraph)}',
    )
    ..writeln('    }')
    ..writeln()
    // toList() method.
    ..writeln('    ${generateKotlinToListMethod(fields, typeGraph)}');

  // For Flutter routes, add toMap(), toPath(), and toPageSettings().
  if (isFlutterRoute) {
    buffer
      ..writeln()
      ..writeln('    fun toMap(): Map<String, String> = mapOf(');
    for (var i = 0; i < fields.length; i++) {
      final field = fields[i];
      final comma = i < fields.length - 1 ? ',' : '';
      if (field.type.isNullable) {
        buffer.writeln(
          '        "${field.name}" to (${field.name}?.toString() ?: "")$comma',
        );
      } else {
        buffer.writeln('        "${field.name}" to ${field.name}.toString()$comma');
      }
    }
    buffer.writeln('    )');

    if (path != null) {
      _writeKotlinToPath(buffer, path, fields, typeGraph);
    }

    buffer.writeln();
    if (path != null) {
      buffer.writeln(
        '    override fun toPageSettings(): PageSettings = PageSettings(ROUTE_NAME, toList(), toPath())',
      );
    } else {
      buffer.writeln(
        '    override fun toPageSettings(): PageSettings = PageSettings(ROUTE_NAME, toList())',
      );
    }
  }

  buffer.writeln('}');
}

void _writeKotlinToPath(
  StringBuffer buffer,
  String path,
  List<FieldInfo> fields,
  Map<String, TypeDefinition> typeGraph,
) {
  final pathParamNames = extractPathParamNames(path);
  final queryFields = fields.where(
    (f) =>
        !pathParamNames.contains(f.name) && isSimpleType(f.type, typeGraph),
  );

  buffer.writeln();

  // Build path expression with URI-encoded params.
  var pathExpr = path;
  for (final paramName in pathParamNames) {
    final field = fields.where((f) => f.name == paramName).firstOrNull;
    final isNullable = field?.type.isNullable ?? false;
    final encode = isNullable
        ? '\${Uri.encode($paramName ?: "")}'
        : '\${Uri.encode($paramName)}';
    pathExpr = pathExpr.replaceAll(':$paramName', encode);
  }

  if (queryFields.isEmpty) {
    buffer.writeln('    fun toPath(): String = "$pathExpr"');
  } else {
    buffer
      ..writeln('    fun toPath(): String {')
      ..writeln('        val basePath = "$pathExpr"')
      ..writeln('        val query = mutableListOf<String>()');
    for (final field in queryFields) {
      final name = field.name;
      if (field.type.isNullable) {
        buffer.writeln(
          '        $name?.let { query.add("$name=\${Uri.encode(it.toString())}") }',
        );
      } else {
        buffer.writeln(
          '        query.add("$name=\${Uri.encode($name.toString())}")',
        );
      }
    }
    buffer
      ..writeln('        if (query.isEmpty()) return basePath')
      ..writeln(r'        return "$basePath?${query.joinToString("&")}"')
      ..writeln('    }');
  }
}

void _writeDataClassWithFields(
  StringBuffer buffer,
  String className,
  List<FieldInfo> fields,
  Map<String, TypeDefinition> typeGraph,
) {
  buffer.writeln('data class $className(');
  for (var i = 0; i < fields.length; i++) {
    final field = fields[i];
    final kotlinType = dartTypeToKotlin(field.type);
    final comma = i < fields.length - 1 ? ',' : '';
    buffer.writeln('    val ${field.name}: $kotlinType$comma');
  }

  buffer
    ..writeln(') {')
    // companion object with fromList.
    ..writeln('    companion object {')
    ..writeln(
      '        ${generateKotlinFromListMethod(className, fields, typeGraph)}',
    )
    ..writeln('    }')
    ..writeln()
    // toList() method.
    ..writeln('    ${generateKotlinToListMethod(fields, typeGraph)}')
    ..writeln('}');
}

void _writeNativeRouteHandler(
  StringBuffer buffer,
  List<RouteDefinition> routes,
) {
  buffer
    ..writeln('abstract class NativeRouteHandler : NativeRouteHandling {')
    ..writeln()
    // handle() method.
    ..writeln(
      '    override fun handle(context: Context, route: PageSettings) {',
    )
    ..writeln('        when (route.routeId) {');

  for (final route in routes) {
    final methodName = methodNameFromClassName(route.className);
    buffer
      ..writeln('            "${route.routeName}" -> $methodName(')
      ..writeln(
        '                ${route.className}.fromList(route.params as List<Any?>),',
      )
      ..writeln('                context')
      ..writeln('            )');
  }

  buffer
    ..writeln('            else -> onUnknownRoute(route, context)')
    ..writeln('        }')
    ..writeln('    }')
    ..writeln();

  // Abstract methods for each route.
  for (final route in routes) {
    final methodName = methodNameFromClassName(route.className);
    buffer.writeln(
      '    abstract fun $methodName(page: ${route.className}, context: Context)',
    );
  }

  buffer
    ..writeln()
    // Default onUnknownRoute.
    ..writeln(
      '    open fun onUnknownRoute(route: PageSettings, context: Context) {',
    )
    ..writeln(
      r'        throw IllegalArgumentException("Unknown route: ${route.routeId}")',
    )
    ..writeln('    }')
    ..writeln('}');
}
