import 'package:leancode_add2app_gen/src/generators/kotlin/kotlin_serialization.dart';
import 'package:leancode_add2app_gen/src/models/data_type_definition.dart';
import 'package:leancode_add2app_gen/src/models/route_definition.dart';
import 'package:leancode_add2app_gen/src/models/schema.dart';
import 'package:leancode_add2app_gen/src/models/type_info.dart';
import 'package:leancode_add2app_gen/src/parser/type_resolver.dart';
import 'package:leancode_add2app_gen/src/utils/naming.dart';

/// Generates Kotlin code for routes from a resolved schema.
///
/// Produces:
/// - Data classes for routes with toList()/fromList() serialization
/// - Data classes for shared types
/// - Enum classes
/// - NativeRouteHandler base class
String generateKotlinRoutes({
  required Schema schema,
  required Map<String, TypeDefinition> typeGraph,
  required String packageName,
}) {
  final buffer = StringBuffer();

  // Header.
  buffer.writeln('// GENERATED CODE — DO NOT MODIFY BY HAND');
  buffer.writeln('// Generated by leancode_add2app_gen');
  buffer.writeln();
  buffer.writeln('package $packageName');
  buffer.writeln();
  buffer.writeln('import android.content.Context');
  buffer.writeln('import co.leancode.add2app.NativeRouteHandler as NativeRouteHandling');
  buffer.writeln('import co.leancode.add2app.navigator.PageSettings');
  buffer.writeln();

  // Generate enums.
  for (final enumDef in schema.enums) {
    _writeEnum(buffer, enumDef);
    buffer.writeln();
  }

  // Generate data classes for shared types.
  for (final dataClass in schema.dataClasses) {
    _writeDataClass(buffer, dataClass, typeGraph);
    buffer.writeln();
  }

  // Generate data classes for Flutter routes.
  for (final route in schema.flutterRoutes) {
    _writeRouteDataClass(buffer, route, typeGraph);
    buffer.writeln();
  }

  // Generate data classes for native routes.
  for (final route in schema.nativeRoutes) {
    _writeRouteDataClass(buffer, route, typeGraph);
    buffer.writeln();
  }

  // Generate NativeRouteHandler if there are native routes.
  if (schema.nativeRoutes.isNotEmpty) {
    _writeNativeRouteHandler(buffer, schema.nativeRoutes);
  }

  final output = buffer.toString();
  return output.endsWith('\n') ? output : '$output\n';
}

void _writeEnum(StringBuffer buffer, EnumDefinition enumDef) {
  buffer.writeln('enum class ${enumDef.name} {');
  for (var i = 0; i < enumDef.values.length; i++) {
    final value = enumDef.values[i];
    if (i < enumDef.values.length - 1) {
      buffer.writeln('    $value,');
    } else {
      buffer.writeln('    $value');
    }
  }
  buffer.writeln('}');
}

void _writeDataClass(
  StringBuffer buffer,
  DataClassDefinition dataClass,
  Map<String, TypeDefinition> typeGraph,
) {
  final className = dataClass.className;
  final fields = dataClass.fields;

  _writeDataClassWithFields(buffer, className, fields, typeGraph);
}

void _writeRouteDataClass(
  StringBuffer buffer,
  RouteDefinition route,
  Map<String, TypeDefinition> typeGraph,
) {
  final className = route.className;
  final fields = route.fields;
  final isFlutterRoute = route.routeType == RouteType.flutter;

  buffer.writeln('data class $className(');
  for (var i = 0; i < fields.length; i++) {
    final field = fields[i];
    final kotlinType = dartTypeToKotlin(field.type);
    final comma = i < fields.length - 1 ? ',' : '';
    buffer.writeln('    val ${field.name}: $kotlinType$comma');
  }
  buffer.writeln(') {');

  // Route name constant.
  buffer.writeln('    companion object {');
  buffer.writeln('        const val ROUTE_NAME = "${route.routeName}"');
  buffer.writeln();
  buffer.writeln(
    '        ${generateKotlinFromListMethod(className, fields, typeGraph)}',
  );
  buffer.writeln('    }');
  buffer.writeln();

  // toList() method.
  buffer.writeln('    ${generateKotlinToListMethod(fields, typeGraph)}');

  // For Flutter routes, add toMap() and toPageSettings() for easier Android navigation.
  if (isFlutterRoute) {
    buffer.writeln();
    buffer.writeln('    fun toMap(): Map<String, String> = mapOf(');
    for (var i = 0; i < fields.length; i++) {
      final field = fields[i];
      final comma = i < fields.length - 1 ? ',' : '';
      if (field.type.isNullable) {
        buffer.writeln(
          '        "${field.name}" to (${field.name}?.toString() ?: "")$comma',
        );
      } else {
        buffer.writeln('        "${field.name}" to ${field.name}.toString()$comma');
      }
    }
    buffer.writeln('    )');
    buffer.writeln();
    buffer.writeln(
      '    fun toPageSettings(): PageSettings = PageSettings(ROUTE_NAME, toMap())',
    );
  }

  buffer.writeln('}');
}

void _writeDataClassWithFields(
  StringBuffer buffer,
  String className,
  List<FieldInfo> fields,
  Map<String, TypeDefinition> typeGraph,
) {
  buffer.writeln('data class $className(');
  for (var i = 0; i < fields.length; i++) {
    final field = fields[i];
    final kotlinType = dartTypeToKotlin(field.type);
    final comma = i < fields.length - 1 ? ',' : '';
    buffer.writeln('    val ${field.name}: $kotlinType$comma');
  }
  buffer.writeln(') {');

  // companion object with fromList.
  buffer.writeln('    companion object {');
  buffer.writeln(
    '        ${generateKotlinFromListMethod(className, fields, typeGraph)}',
  );
  buffer.writeln('    }');
  buffer.writeln();

  // toList() method.
  buffer.writeln('    ${generateKotlinToListMethod(fields, typeGraph)}');

  buffer.writeln('}');
}

void _writeNativeRouteHandler(
  StringBuffer buffer,
  List<RouteDefinition> routes,
) {
  buffer.writeln('abstract class NativeRouteHandler : NativeRouteHandling {');
  buffer.writeln();

  // handle() method.
  buffer.writeln(
    '    override fun handle(context: Context, route: PageSettings) {',
  );
  buffer.writeln('        when (route.routeId) {');

  for (final route in routes) {
    final methodName = methodNameFromClassName(route.className);
    buffer.writeln('            "${route.routeName}" -> $methodName(');
    buffer.writeln(
      '                ${route.className}.fromList(route.params as List<Any?>),',
    );
    buffer.writeln('                context');
    buffer.writeln('            )');
  }

  buffer.writeln('            else -> onUnknownRoute(route, context)');
  buffer.writeln('        }');
  buffer.writeln('    }');
  buffer.writeln();

  // Abstract methods for each route.
  for (final route in routes) {
    final methodName = methodNameFromClassName(route.className);
    buffer.writeln(
      '    abstract fun $methodName(page: ${route.className}, context: Context)',
    );
  }
  buffer.writeln();

  // Default onUnknownRoute.
  buffer.writeln(
    '    open fun onUnknownRoute(route: PageSettings, context: Context) {',
  );
  buffer.writeln(
    r'        throw IllegalArgumentException("Unknown route: ${route.routeId}")',
  );
  buffer.writeln('    }');

  buffer.writeln('}');
}
