import 'package:leancode_add2app_gen/src/generators/kotlin/kotlin_serialization.dart';
import 'package:leancode_add2app_gen/src/models/schema.dart';
import 'package:leancode_add2app_gen/src/models/store_definition.dart';
import 'package:leancode_add2app_gen/src/models/type_info.dart';

/// Generates Kotlin code for stores from a resolved schema.
///
/// Produces:
/// - Store classes with typed getters/setters via NativeStorageScope
String generateKotlinStores({
  required Schema schema,
  required String packageName,
}) {
  final buffer = StringBuffer();

  // Header.
  buffer.writeln('// GENERATED CODE — DO NOT MODIFY BY HAND');
  buffer.writeln('// Generated by leancode_add2app_gen');
  buffer.writeln();
  buffer.writeln('package $packageName');
  buffer.writeln();
  buffer.writeln('import co.leancode.add2app.NativeStorageScope');
  buffer.writeln();

  // Generate store classes.
  for (final store in schema.stores) {
    _writeStoreClass(buffer, store);
    buffer.writeln();
  }

  final output = buffer.toString();
  return output.endsWith('\n') ? output : '$output\n';
}

void _writeStoreClass(StringBuffer buffer, StoreDefinition store) {
  final className = store.className;
  final storeKey = store.storeKey;
  final scopeFields = store.scopeFields;
  final valueFields = store.valueFields;

  buffer.writeln('/**');
  buffer.writeln(' * Generated store wrapper for $className.');
  buffer.writeln(' */');

  // Class declaration.
  buffer.write('class $className(');
  buffer.writeln();
  buffer.writeln('    private val storage: NativeStorageScope,');
  for (final field in scopeFields) {
    final kotlinType = dartTypeToKotlin(field.type);
    buffer.writeln('    private val ${field.name}: $kotlinType,');
  }
  buffer.writeln(') {');
  buffer.writeln();

  // Key helper.
  if (scopeFields.isEmpty) {
    buffer.writeln(r'    private fun key(field: String) = "$storeKey/$field"');
  } else {
    final scopeParts = scopeFields.map((f) => '\$${f.name}').join('/');
    buffer.writeln('    private fun key(field: String) = "$storeKey/$scopeParts/\$field"');
  }
  buffer.writeln();

  // Properties for each value field.
  for (final field in valueFields) {
    _writeProperty(buffer, field);
    buffer.writeln();
  }

  // clear() method.
  buffer.writeln('    fun clear() = storage.removeByPrefix(key(""))');

  buffer.writeln('}');
}

void _writeProperty(StringBuffer buffer, FieldInfo field) {
  final baseName = field.type.baseName;
  final kotlinType = _kotlinPrimitiveType(baseName);
  final defaultVal = field.defaultValue ?? _defaultValueForType(baseName);

  buffer.writeln('    var ${field.name}: $kotlinType');

  // Getter.
  switch (baseName) {
    case 'bool':
      if (defaultVal == 'true') {
        buffer.writeln('        get() = storage.get(key("${field.name}")) != "false"');
      } else {
        buffer.writeln('        get() = storage.get(key("${field.name}")) == "true"');
      }
    case 'int':
      buffer.writeln(
        '        get() = storage.get(key("${field.name}"))?.toLongOrNull() ?: $defaultVal',
      );
    case 'double':
      buffer.writeln(
        '        get() = storage.get(key("${field.name}"))?.toDoubleOrNull() ?: $defaultVal',
      );
    case 'String':
      buffer.writeln(
        '        get() = storage.get(key("${field.name}")) ?: $defaultVal',
      );
    default:
      buffer.writeln(
        '        get() = storage.get(key("${field.name}")) ?: ""',
      );
  }

  // Setter.
  switch (baseName) {
    case 'String':
      buffer.writeln('        set(value) = storage.put(key("${field.name}"), value)');
    default:
      buffer.writeln(
        '        set(value) = storage.put(key("${field.name}"), value.toString())',
      );
  }
}

String _kotlinPrimitiveType(String dartType) {
  switch (dartType) {
    case 'bool':
      return 'Boolean';
    case 'int':
      return 'Long';
    case 'double':
      return 'Double';
    case 'String':
      return 'String';
    default:
      return 'String';
  }
}

String _defaultValueForType(String dartType) {
  switch (dartType) {
    case 'bool':
      return 'false';
    case 'int':
      return '0L';
    case 'double':
      return '0.0';
    case 'String':
      return '""';
    default:
      return '""';
  }
}
