import 'package:leancode_add2app_gen/src/generators/kotlin/kotlin_serialization.dart';
import 'package:leancode_add2app_gen/src/models/schema.dart';
import 'package:leancode_add2app_gen/src/models/store_definition.dart';
import 'package:leancode_add2app_gen/src/models/type_info.dart';
import 'package:leancode_add2app_gen/src/parser/type_resolver.dart';

/// Generates Kotlin code for stores from a resolved schema.
///
/// Produces:
/// - Store classes with typed getters/setters via NativeStorageScope
String generateKotlinStores({
  required Schema schema,
  required Map<String, TypeDefinition> typeGraph,
  required String packageName,
}) {
  final buffer = StringBuffer()
    // Header.
    ..writeln('// GENERATED CODE — DO NOT MODIFY BY HAND')
    ..writeln('// Generated by leancode_add2app_gen')
    ..writeln()
    ..writeln('package $packageName')
    ..writeln()
    ..writeln('import co.leancode.add2app.NativeStorageScope')
    ..writeln('import co.leancode.add2app.storage.StorageEntry')
    ..writeln();

  // Generate store classes.
  for (final store in schema.stores) {
    _writeStoreClass(buffer, store, typeGraph);
    buffer.writeln();
  }

  final output = buffer.toString();
  return output.endsWith('\n') ? output : '$output\n';
}

void _writeStoreClass(
  StringBuffer buffer,
  StoreDefinition store,
  Map<String, TypeDefinition> typeGraph,
) {
  final className = store.className;
  final storeKey = store.storeKey;
  final keyField = store.keyField;
  final valueFields = store.valueFields;

  buffer
    ..writeln('/**')
    ..writeln(' * Generated store wrapper for $className.')
    ..writeln(' */')
    // Class declaration.
    ..write('class $className(')
    ..writeln()
    ..writeln('    private val storage: NativeStorageScope,');
  if (keyField != null) {
    final kotlinType = dartTypeToKotlin(keyField.type);
    buffer.writeln('    private val ${keyField.name}: $kotlinType,');
  }
  buffer
    ..writeln(') {')
    ..writeln();

  // Key prefix and key helper.
  if (keyField == null) {
    buffer
      ..writeln('    val keyPrefix: String get() = "$storeKey/"')
      ..writeln()
      ..writeln('    private fun key(field: String) = "$storeKey/\$field"');
  } else {
    final keySegment = _keySegmentExpression(keyField, typeGraph);
    buffer
      ..writeln('    val keyPrefix: String get() = "$storeKey/$keySegment/"')
      ..writeln()
      ..writeln(
        '    private fun key(field: String) = "$storeKey/$keySegment/\$field"',
      );
  }
  buffer
    ..writeln()
    // containsChanges helper.
    ..writeln(
      '    fun containsChanges(entries: List<StorageEntry>) = entries.any { it.key.startsWith(keyPrefix) }',
    )
    ..writeln();

  // Properties for each value field.
  for (final field in valueFields) {
    _writeProperty(buffer, field, typeGraph);
    buffer.writeln();
  }

  // clear() method.
  buffer
    ..writeln('    fun clear() = storage.removeByPrefix(key(""))')
    ..writeln('}');
}

void _writeProperty(
  StringBuffer buffer,
  FieldInfo field,
  Map<String, TypeDefinition> typeGraph,
) {
  final baseName = field.type.baseName;
  final enumType = typeGraph[baseName] is EnumType
      ? typeGraph[baseName]! as EnumType
      : null;
  final kotlinType = _kotlinStoreType(baseName, enumType);
  final rawDefault =
      field.defaultValue ?? _defaultValueForType(baseName, enumType);
  final defaultVal = _dartToKotlinLiteral(rawDefault, baseName);

  buffer.writeln('    var ${field.name}: $kotlinType');

  // Getter.
  if (enumType != null) {
    buffer
      ..writeln(
        '        get() = storage.get(key("${field.name}"))?.toIntOrNull()?.let { $baseName.entries[it] } ?: $defaultVal',
      )
      ..writeln(
        '        set(value) = storage.put(key("${field.name}"), value.ordinal.toString())',
      );
    return;
  }

  switch (baseName) {
    case 'bool':
      if (defaultVal == 'true') {
        buffer.writeln(
          '        get() = storage.get(key("${field.name}")) != "false"',
        );
      } else {
        buffer.writeln(
          '        get() = storage.get(key("${field.name}")) == "true"',
        );
      }
    case 'int':
      buffer.writeln(
        '        get() = storage.get(key("${field.name}"))?.toLongOrNull() ?: $defaultVal',
      );
    case 'double':
      buffer.writeln(
        '        get() = storage.get(key("${field.name}"))?.toDoubleOrNull() ?: $defaultVal',
      );
    case 'String':
      buffer.writeln(
        '        get() = storage.get(key("${field.name}")) ?: $defaultVal',
      );
    default:
      buffer.writeln('        get() = storage.get(key("${field.name}")) ?: ""');
  }

  // Setter.
  switch (baseName) {
    case 'String':
      buffer.writeln(
        '        set(value) = storage.put(key("${field.name}"), value)',
      );
    default:
      buffer.writeln(
        '        set(value) = storage.put(key("${field.name}"), value.toString())',
      );
  }
}

String _kotlinStoreType(String dartType, EnumType? enumType) {
  if (enumType != null) {
    return enumType.name;
  }

  switch (dartType) {
    case 'bool':
      return 'Boolean';
    case 'int':
      return 'Long';
    case 'double':
      return 'Double';
    case 'String':
      return 'String';
    default:
      return 'String';
  }
}

String _defaultValueForType(String dartType, EnumType? enumType) {
  if (enumType != null) {
    return '${enumType.name}.${enumType.values.first}';
  }

  switch (dartType) {
    case 'bool':
      return 'false';
    case 'int':
      return '0L';
    case 'double':
      return '0.0';
    case 'String':
      return '""';
    default:
      return '""';
  }
}

/// Converts a Dart literal to its Kotlin equivalent.
///
/// Mainly handles string literals: Dart uses single quotes (`'hello'`),
/// while Kotlin uses double quotes (`"hello"`).
String _dartToKotlinLiteral(String dartLiteral, String dartType) {
  if (dartType == 'String') {
    // Convert Dart single-quoted strings to Kotlin double-quoted strings.
    if (dartLiteral.startsWith("'") && dartLiteral.endsWith("'")) {
      final content = dartLiteral.substring(1, dartLiteral.length - 1);
      return '"$content"';
    }
  }
  return dartLiteral;
}

String _keySegmentExpression(
  FieldInfo keyField,
  Map<String, TypeDefinition> typeGraph,
) {
  if (typeGraph[keyField.type.baseName] is EnumType) {
    return '\${${keyField.name}.name}';
  }
  return '\$${keyField.name}';
}
