// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package co.leancode.signal_module

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object KeyValueStorageApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * A generic key-value entry stored on the platform side.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StorageEntry (
  /** The key for this entry. */
  val key: String,
  /**
   * The JSON-encoded value for this entry.
   * We use String (JSON) so Pigeon can transport any structured data.
   */
  val value: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StorageEntry {
      val key = pigeonVar_list[0] as String
      val value = pigeonVar_list[1] as String
      return StorageEntry(key, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      key,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is StorageEntry) {
      return false
    }
    if (this === other) {
      return true
    }
    return KeyValueStorageApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Batch of changed entries, used for change notifications.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StorageChangeEvent (
  /** The entries that changed (new values). */
  val entries: List<StorageEntry>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StorageChangeEvent {
      val entries = pigeonVar_list[0] as List<StorageEntry>
      return StorageChangeEvent(entries)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      entries,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is StorageChangeEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return KeyValueStorageApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class KeyValueStorageApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StorageEntry.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StorageChangeEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is StorageEntry -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is StorageChangeEvent -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Host API — Flutter calls into platform (Android/iOS).
 * The platform owns the data; Flutter reads/writes through this API.
 * Uses TaskQueue.serialBackgroundThread for thread-safety.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface KeyValueStorageHostApi {
  /** Put a value into the storage. Overwrites if key already exists. */
  fun put(entry: StorageEntry)
  /** Put multiple values at once (atomic batch). */
  fun putAll(entries: List<StorageEntry>)
  /** Get a value by key. Returns null if not found. */
  fun get(key: String): StorageEntry?
  /** Get all values whose keys start with the given prefix. */
  fun getByPrefix(prefix: String): List<StorageEntry>
  /** Remove a value by key. Returns true if the key existed. */
  fun remove(key: String): Boolean
  /** Remove all values whose keys start with the given prefix. */
  fun removeByPrefix(prefix: String)
  /** Get all stored entries (full dump). */
  fun getAll(): List<StorageEntry>
  /** Clear all storage. */
  fun clear()

  companion object {
    /** The codec used by KeyValueStorageHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      KeyValueStorageApiPigeonCodec()
    }
    /** Sets up an instance of `KeyValueStorageHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: KeyValueStorageHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.signal_module.KeyValueStorageHostApi.put$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val entryArg = args[0] as StorageEntry
            val wrapped: List<Any?> = try {
              api.put(entryArg)
              listOf(null)
            } catch (exception: Throwable) {
              KeyValueStorageApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.signal_module.KeyValueStorageHostApi.putAll$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val entriesArg = args[0] as List<StorageEntry>
            val wrapped: List<Any?> = try {
              api.putAll(entriesArg)
              listOf(null)
            } catch (exception: Throwable) {
              KeyValueStorageApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.signal_module.KeyValueStorageHostApi.get$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.get(keyArg))
            } catch (exception: Throwable) {
              KeyValueStorageApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.signal_module.KeyValueStorageHostApi.getByPrefix$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val prefixArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.getByPrefix(prefixArg))
            } catch (exception: Throwable) {
              KeyValueStorageApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.signal_module.KeyValueStorageHostApi.remove$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.remove(keyArg))
            } catch (exception: Throwable) {
              KeyValueStorageApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.signal_module.KeyValueStorageHostApi.removeByPrefix$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val prefixArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.removeByPrefix(prefixArg)
              listOf(null)
            } catch (exception: Throwable) {
              KeyValueStorageApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.signal_module.KeyValueStorageHostApi.getAll$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getAll())
            } catch (exception: Throwable) {
              KeyValueStorageApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.signal_module.KeyValueStorageHostApi.clear$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clear()
              listOf(null)
            } catch (exception: Throwable) {
              KeyValueStorageApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Flutter API — Platform calls into Flutter to notify about changes.
 * Each Flutter engine isolate registers this so it gets notified when
 * any other engine (or Android itself) changes storage.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class KeyValueStorageFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by KeyValueStorageFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      KeyValueStorageApiPigeonCodec()
    }
  }
  /**
   * Called when entries in the storage have changed.
   * The Flutter side should update its local cache.
   */
  fun onStorageChanged(eventArg: StorageChangeEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.signal_module.KeyValueStorageFlutterApi.onStorageChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(KeyValueStorageApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
