import 'package:inlay_gen/src/generators/swift/swift_serialization.dart';
import 'package:inlay_gen/src/models/data_type_definition.dart';
import 'package:inlay_gen/src/models/schema.dart';
import 'package:inlay_gen/src/models/store_definition.dart';
import 'package:inlay_gen/src/models/type_info.dart';
import 'package:inlay_gen/src/parser/type_resolver.dart';

/// Generates Swift code for stores from a resolved schema.
///
/// Produces:
/// - Store structs with typed getters/setters via NativeStorageScope
String generateSwiftStores({
  required Schema schema,
  required Map<String, TypeDefinition> typeGraph,
}) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE — DO NOT MODIFY BY HAND')
    ..writeln('// Generated by inlay_gen')
    ..writeln()
    ..writeln('import Foundation')
    ..writeln('import inlay')
    ..writeln();

  // Generate store-only enums.
  for (final enumDef in schema.enums) {
    _writeEnum(buffer, enumDef);
    buffer.writeln();
  }

  // Generate store-only data classes.
  for (final dataClass in schema.dataClasses) {
    _writeDataStruct(buffer, dataClass, typeGraph);
    buffer.writeln();
  }

  for (final store in schema.stores) {
    _writeStoreStruct(buffer, store, typeGraph);
    buffer.writeln();
  }

  final output = buffer.toString();
  return output.endsWith('\n') ? output : '$output\n';
}

void _writeStoreStruct(
  StringBuffer buffer,
  StoreDefinition store,
  Map<String, TypeDefinition> typeGraph,
) {
  final className = store.className;
  final storeKey = store.storeKey;
  final keyField = store.keyField;
  final valueFields = store.valueFields;

  buffer
    ..writeln('/// Generated store wrapper for $className.')
    ..writeln('struct $className {')
    ..writeln('    private let storage: NativeStorageScope');
  if (keyField != null) {
    final swiftType = _swiftStoreType(keyField.type.baseName, typeGraph);
    buffer.writeln('    private let ${keyField.name}: $swiftType');
  }
  buffer.writeln();

  // Explicit init — Swift's memberwise init is private when properties are.
  if (keyField != null) {
    final swiftType = _swiftStoreType(keyField.type.baseName, typeGraph);
    buffer
      ..writeln(
        '    init(storage: NativeStorageScope, ${keyField.name}: $swiftType) {',
      )
      ..writeln('        self.storage = storage')
      ..writeln('        self.${keyField.name} = ${keyField.name}')
      ..writeln('    }');
  } else {
    buffer
      ..writeln('    init(storage: NativeStorageScope) {')
      ..writeln('        self.storage = storage')
      ..writeln('    }');
  }
  buffer.writeln();

  // Key prefix and key helper.
  if (keyField == null) {
    buffer
      ..writeln('    var keyPrefix: String { "$storeKey/" }')
      ..writeln()
      ..writeln(
        '    private func key(_ field: String) -> String { "$storeKey/\\(field)" }',
      );
  } else {
    final keySegment = _keySegmentExpression(keyField, typeGraph);
    buffer
      ..writeln('    var keyPrefix: String { "$storeKey/$keySegment/" }')
      ..writeln()
      ..writeln(
        '    private func key(_ field: String) -> String { "$storeKey/$keySegment/\\(field)" }',
      );
  }
  buffer
    ..writeln()
    // containsChanges helper.
    ..writeln('    func containsChanges(in entries: [StorageEntry]) -> Bool {')
    ..writeln(r'        entries.contains { $0.key.hasPrefix(keyPrefix) }')
    ..writeln('    }')
    ..writeln();

  // Properties for each value field.
  for (final field in valueFields) {
    _writeProperty(buffer, field, typeGraph);
    buffer.writeln();
  }

  // clear() method.
  buffer
    ..writeln('    func clear() { storage.removeByPrefix(prefix: key("")) }')
    ..writeln('}');
}

void _writeProperty(
  StringBuffer buffer,
  FieldInfo field,
  Map<String, TypeDefinition> typeGraph,
) {
  if (isSimpleStoreType(field.type, typeGraph)) {
    _writeSimpleProperty(buffer, field, typeGraph);
  } else {
    _writeComplexProperty(buffer, field, typeGraph);
  }
}

void _writeSimpleProperty(
  StringBuffer buffer,
  FieldInfo field,
  Map<String, TypeDefinition> typeGraph,
) {
  final baseName = field.type.baseName;
  final enumType = typeGraph[baseName] is EnumType
      ? typeGraph[baseName]! as EnumType
      : null;
  final swiftType = _swiftStoreType(baseName, typeGraph);
  final rawDefault =
      field.defaultValue ?? _defaultValueForType(baseName, enumType);
  final defaultVal = _dartToSwiftLiteral(rawDefault, baseName);

  buffer.writeln('    var ${field.name}: $swiftType {');

  // Getter.
  if (enumType != null) {
    buffer
      ..writeln('        get {')
      ..writeln(
        '            guard let raw = storage.get(key: key("${field.name}")),',
      )
      ..writeln(
        '                  let intVal = Int(raw) else { return $defaultVal }',
      )
      ..writeln('            return $baseName(rawValue: intVal) ?? $defaultVal')
      ..writeln('        }')
      ..writeln(
        '        set { storage.put(key: key("${field.name}"), value: String(newValue.rawValue)) }',
      )
      ..writeln('    }');
    return;
  }

  switch (baseName) {
    case 'bool':
      if (defaultVal == 'true') {
        buffer.writeln(
          '        get { storage.get(key: key("${field.name}")) != "false" }',
        );
      } else {
        buffer.writeln(
          '        get { storage.get(key: key("${field.name}")) == "true" }',
        );
      }
    case 'int':
      buffer.writeln(
        '        get { Int(storage.get(key: key("${field.name}")) ?? "") ?? $defaultVal }',
      );
    case 'double':
      buffer.writeln(
        '        get { Double(storage.get(key: key("${field.name}")) ?? "") ?? $defaultVal }',
      );
    case 'String':
      buffer.writeln(
        '        get { storage.get(key: key("${field.name}")) ?? $defaultVal }',
      );
    default:
      buffer.writeln(
        '        get { storage.get(key: key("${field.name}")) ?? "" }',
      );
  }

  // Setter.
  switch (baseName) {
    case 'String':
      buffer.writeln(
        '        set { storage.put(key: key("${field.name}"), value: newValue) }',
      );
    default:
      buffer.writeln(
        '        set { storage.put(key: key("${field.name}"), value: String(describing: newValue)) }',
      );
  }

  buffer.writeln('    }');
}

void _writeComplexProperty(
  StringBuffer buffer,
  FieldInfo field,
  Map<String, TypeDefinition> typeGraph,
) {
  final swiftType = dartTypeToSwift(field.type);

  buffer.writeln('    var ${field.name}: $swiftType {');

  // Getter.
  if (field.type.isNullable) {
    final decodeExpr = generateSwiftDecode(
      'json',
      field.type.toNonNullable(),
      typeGraph,
    );
    buffer
      ..writeln('        get {')
      ..writeln(
        '            guard let raw = storage.get(key: key("${field.name}")),',
      )
      ..writeln('                  let data = raw.data(using: .utf8),')
      ..writeln(
        '                  let json = try? JSONSerialization.jsonObject(with: data) else { return nil }',
      )
      ..writeln('            return $decodeExpr')
      ..writeln('        }');
  } else {
    final decodeExpr = generateSwiftDecode('json', field.type, typeGraph);
    final rawDefault = field.defaultValue ?? '[]';
    final defaultVal = _dartToSwiftLiteral(rawDefault, field.type.baseName);
    buffer
      ..writeln('        get {')
      ..writeln(
        '            guard let raw = storage.get(key: key("${field.name}")),',
      )
      ..writeln('                  let data = raw.data(using: .utf8),')
      ..writeln(
        '                  let json = try? JSONSerialization.jsonObject(with: data) else { return $defaultVal }',
      )
      ..writeln('            return $decodeExpr')
      ..writeln('        }');
  }

  // Setter.
  if (field.type.isNullable) {
    final encodeExpr = generateSwiftEncode(
      'newValue',
      field.type.toNonNullable(),
      typeGraph,
    );
    buffer
      ..writeln('        set {')
      ..writeln('            guard let newValue else {')
      ..writeln('                storage.remove(key: key("${field.name}"))')
      ..writeln('                return')
      ..writeln('            }')
      ..writeln(
        '            if let data = try? JSONSerialization.data(withJSONObject: $encodeExpr as Any),',
      )
      ..writeln(
        '               let str = String(data: data, encoding: .utf8) {',
      )
      ..writeln(
        '                storage.put(key: key("${field.name}"), value: str)',
      )
      ..writeln('            }')
      ..writeln('        }');
  } else {
    final encodeExpr = generateSwiftEncode('newValue', field.type, typeGraph);
    buffer
      ..writeln('        set {')
      ..writeln(
        '            if let data = try? JSONSerialization.data(withJSONObject: $encodeExpr as Any),',
      )
      ..writeln(
        '               let str = String(data: data, encoding: .utf8) {',
      )
      ..writeln(
        '                storage.put(key: key("${field.name}"), value: str)',
      )
      ..writeln('            }')
      ..writeln('        }');
  }

  buffer.writeln('    }');
}

String _swiftStoreType(String dartType, Map<String, TypeDefinition> typeGraph) {
  if (typeGraph[dartType] is EnumType) {
    return dartType;
  }

  switch (dartType) {
    case 'bool':
      return 'Bool';
    case 'int':
      return 'Int';
    case 'double':
      return 'Double';
    case 'String':
      return 'String';
    default:
      return 'String';
  }
}

String _defaultValueForType(String dartType, EnumType? enumType) {
  if (enumType != null) {
    return '.${enumType.values.first}';
  }

  switch (dartType) {
    case 'bool':
      return 'false';
    case 'int':
      return '0';
    case 'double':
      return '0.0';
    case 'String':
      return '""';
    default:
      return '""';
  }
}

/// Converts a Dart literal to its Swift equivalent.
///
/// Handles string literals (single → double quotes) and
/// collection literals (const [] → [], const {} → [:]).
String _dartToSwiftLiteral(String dartLiteral, String dartType) {
  if (dartType == 'String') {
    if (dartLiteral.startsWith("'") && dartLiteral.endsWith("'")) {
      final content = dartLiteral.substring(1, dartLiteral.length - 1);
      return '"$content"';
    }
  }
  if (dartLiteral == 'const []') {
    return '[]';
  }
  if (dartLiteral == 'const {}') {
    return '[:]';
  }
  // Enum defaults already use .value syntax from _defaultValueForType.
  return dartLiteral;
}

String _keySegmentExpression(
  FieldInfo keyField,
  Map<String, TypeDefinition> typeGraph,
) {
  if (typeGraph[keyField.type.baseName] is EnumType) {
    return '\\(${keyField.name}.name)';
  }
  return '\\(${keyField.name})';
}

void _writeEnum(StringBuffer buffer, EnumDefinition enumDef) {
  buffer.writeln('enum ${enumDef.name}: Int {');
  for (var i = 0; i < enumDef.values.length; i++) {
    final value = enumDef.values[i];
    buffer.writeln('    case $value = $i');
  }
  buffer.writeln('}');
}

void _writeDataStruct(
  StringBuffer buffer,
  DataClassDefinition dataClass,
  Map<String, TypeDefinition> typeGraph,
) {
  final structName = dataClass.className;
  final fields = dataClass.fields;

  buffer.writeln('struct $structName {');

  for (final field in fields) {
    final swiftType = dartTypeToSwift(field.type);
    buffer.writeln('    let ${field.name}: $swiftType');
  }

  buffer
    ..writeln()
    ..writeln(
      '    ${generateSwiftFromListMethod(structName, fields, typeGraph)}',
    )
    ..writeln()
    ..writeln('    ${generateSwiftToListMethod(fields, typeGraph)}')
    ..writeln('}');
}
