// GENERATED CODE — DO NOT MODIFY BY HAND
// Generated by leancode_add2app_gen

package co.leancode.signal_module.navigator

import android.content.Context
import co.leancode.add2app.navigator.PageSettings

/**
 * Abstract handler for native routes dispatched from Flutter.
 *
 * Extend this class and implement each `on*` method to handle
 * native route requests. The base class decodes [PageSettings]
 * into pigeon-generated page objects automatically via `fromList()`.
 */
abstract class NativeRouteHandler : co.leancode.add2app.NativeRouteHandler {

    /**
     * Dispatches a [PageSettings] to the correct typed handler.
     * Called by the framework — do NOT call this directly.
     */
    override fun handle(context: Context, route: PageSettings) {
        when (route.routeId) {
            "nativeEditProfile" -> onNativeEditProfile(
                NativeEditProfilePage.fromList(route.params as List<Any?>),
                context,
            )
            "nativeMediaViewer" -> onNativeMediaViewer(
                NativeMediaViewerPage.fromList(route.params as List<Any?>),
                context,
            )
            else -> onUnknownRoute(route, context)
        }
    }

    abstract fun onNativeEditProfile(page: NativeEditProfilePage, context: Context)
    abstract fun onNativeMediaViewer(page: NativeMediaViewerPage, context: Context)

    /**
     * Called when no handler matches the route ID.
     * Override to customize error handling.
     */
    open fun onUnknownRoute(route: PageSettings, context: Context) {
        throw IllegalArgumentException(
            "No handler for native route '${route.routeId}'."
        )
    }
}
