// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package co.leancode.signal_module.navigator

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PagesPigeonUtils {
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Page settings for the Sounds & Notifications screen.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SoundsNotificationsPage (
  val contactId: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SoundsNotificationsPage {
      val contactId = pigeonVar_list[0] as String
      return SoundsNotificationsPage(contactId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contactId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SoundsNotificationsPage) {
      return false
    }
    if (this === other) {
      return true
    }
    return PagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SetWallpaperPage (
  val recipientId: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SetWallpaperPage {
      val recipientId = pigeonVar_list[0] as String
      return SetWallpaperPage(recipientId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      recipientId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SetWallpaperPage) {
      return false
    }
    if (this === other) {
      return true
    }
    return PagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ContactDetailsPage (
  val contactId: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ContactDetailsPage {
      val contactId = pigeonVar_list[0] as String
      return ContactDetailsPage(contactId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contactId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ContactDetailsPage) {
      return false
    }
    if (this === other) {
      return true
    }
    return PagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeEditProfilePage (
  val contactId: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeEditProfilePage {
      val contactId = pigeonVar_list[0] as String
      return NativeEditProfilePage(contactId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contactId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeEditProfilePage) {
      return false
    }
    if (this === other) {
      return true
    }
    return PagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeMediaViewerPage (
  val mediaId: String,
  val mediaType: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeMediaViewerPage {
      val mediaId = pigeonVar_list[0] as String
      val mediaType = pigeonVar_list[1] as String?
      return NativeMediaViewerPage(mediaId, mediaType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mediaId,
      mediaType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeMediaViewerPage) {
      return false
    }
    if (this === other) {
      return true
    }
    return PagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class PagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SoundsNotificationsPage.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SetWallpaperPage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ContactDetailsPage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeEditProfilePage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeMediaViewerPage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SoundsNotificationsPage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is SetWallpaperPage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ContactDetailsPage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NativeEditProfilePage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is NativeMediaViewerPage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

