import 'package:leancode_add2app_gen/src/models/schema.dart';
import 'package:leancode_add2app_gen/src/models/store_definition.dart';
import 'package:leancode_add2app_gen/src/models/type_info.dart';
import 'package:leancode_add2app_gen/src/parser/type_resolver.dart';

/// Generates Swift code for stores from a resolved schema.
///
/// Produces:
/// - Store structs with typed getters/setters via NativeStorageScope
String generateSwiftStores({
  required Schema schema,
  required Map<String, TypeDefinition> typeGraph,
}) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE — DO NOT MODIFY BY HAND')
    ..writeln('// Generated by leancode_add2app_gen')
    ..writeln()
    ..writeln('import Foundation')
    ..writeln();

  for (final store in schema.stores) {
    _writeStoreStruct(buffer, store, typeGraph);
    buffer.writeln();
  }

  final output = buffer.toString();
  return output.endsWith('\n') ? output : '$output\n';
}

void _writeStoreStruct(
  StringBuffer buffer,
  StoreDefinition store,
  Map<String, TypeDefinition> typeGraph,
) {
  final className = store.className;
  final storeKey = store.storeKey;
  final keyField = store.keyField;
  final valueFields = store.valueFields;

  buffer
    ..writeln('/// Generated store wrapper for $className.')
    ..writeln('struct $className {')
    ..writeln('    private let storage: NativeStorageScope');
  if (keyField != null) {
    final swiftType = _swiftStoreType(keyField.type.baseName, typeGraph);
    buffer.writeln('    private let ${keyField.name}: $swiftType');
  }
  buffer.writeln();

  // Key helper.
  if (keyField == null) {
    buffer.writeln(
      '    private func key(_ field: String) -> String { "$storeKey/\\(field)" }',
    );
  } else {
    final keySegment = _keySegmentExpression(keyField, typeGraph);
    buffer.writeln(
      '    private func key(_ field: String) -> String { "$storeKey/$keySegment/\\(field)" }',
    );
  }
  buffer.writeln();

  // Properties for each value field.
  for (final field in valueFields) {
    _writeProperty(buffer, field, typeGraph);
    buffer.writeln();
  }

  // clear() method.
  buffer
    ..writeln('    func clear() { storage.removeByPrefix(key("")) }')
    ..writeln('}');
}

void _writeProperty(
  StringBuffer buffer,
  FieldInfo field,
  Map<String, TypeDefinition> typeGraph,
) {
  final baseName = field.type.baseName;
  final enumType = typeGraph[baseName] is EnumType
      ? typeGraph[baseName]! as EnumType
      : null;
  final swiftType = _swiftStoreType(baseName, typeGraph);
  final rawDefault =
      field.defaultValue ?? _defaultValueForType(baseName, enumType);
  final defaultVal = _dartToSwiftLiteral(rawDefault, baseName);

  buffer.writeln('    var ${field.name}: $swiftType {');

  // Getter.
  if (enumType != null) {
    buffer
      ..writeln('        get {')
      ..writeln(
        '            guard let raw = storage.get(key: key("${field.name}")),',
      )
      ..writeln(
        '                  let intVal = Int(raw) else { return $defaultVal }',
      )
      ..writeln('            return $baseName(rawValue: intVal) ?? $defaultVal')
      ..writeln('        }')
      ..writeln(
        '        set { storage.put(key: key("${field.name}"), value: String(newValue.rawValue)) }',
      )
      ..writeln('    }');
    return;
  }

  switch (baseName) {
    case 'bool':
      if (defaultVal == 'true') {
        buffer.writeln(
          '        get { storage.get(key: key("${field.name}")) != "false" }',
        );
      } else {
        buffer.writeln(
          '        get { storage.get(key: key("${field.name}")) == "true" }',
        );
      }
    case 'int':
      buffer.writeln(
        '        get { Int(storage.get(key: key("${field.name}")) ?? "") ?? $defaultVal }',
      );
    case 'double':
      buffer.writeln(
        '        get { Double(storage.get(key: key("${field.name}")) ?? "") ?? $defaultVal }',
      );
    case 'String':
      buffer.writeln(
        '        get { storage.get(key: key("${field.name}")) ?? $defaultVal }',
      );
    default:
      buffer.writeln(
        '        get { storage.get(key: key("${field.name}")) ?? "" }',
      );
  }

  // Setter.
  switch (baseName) {
    case 'String':
      buffer.writeln(
        '        set { storage.put(key: key("${field.name}"), value: newValue) }',
      );
    default:
      buffer.writeln(
        '        set { storage.put(key: key("${field.name}"), value: String(describing: newValue)) }',
      );
  }

  buffer.writeln('    }');
}

String _swiftStoreType(String dartType, Map<String, TypeDefinition> typeGraph) {
  if (typeGraph[dartType] is EnumType) {
    return dartType;
  }

  switch (dartType) {
    case 'bool':
      return 'Bool';
    case 'int':
      return 'Int';
    case 'double':
      return 'Double';
    case 'String':
      return 'String';
    default:
      return 'String';
  }
}

String _defaultValueForType(String dartType, EnumType? enumType) {
  if (enumType != null) {
    return '.${enumType.values.first}';
  }

  switch (dartType) {
    case 'bool':
      return 'false';
    case 'int':
      return '0';
    case 'double':
      return '0.0';
    case 'String':
      return '""';
    default:
      return '""';
  }
}

/// Converts a Dart literal to its Swift equivalent.
String _dartToSwiftLiteral(String dartLiteral, String dartType) {
  if (dartType == 'String') {
    if (dartLiteral.startsWith("'") && dartLiteral.endsWith("'")) {
      final content = dartLiteral.substring(1, dartLiteral.length - 1);
      return '"$content"';
    }
  }
  // Enum defaults already use .value syntax from _defaultValueForType.
  return dartLiteral;
}

String _keySegmentExpression(
  FieldInfo keyField,
  Map<String, TypeDefinition> typeGraph,
) {
  if (typeGraph[keyField.type.baseName] is EnumType) {
    return '\\(${keyField.name}.name)';
  }
  return '\\(${keyField.name})';
}
