import 'package:leancode_add2app_gen/src/generators/swift/swift_serialization.dart';
import 'package:leancode_add2app_gen/src/models/data_type_definition.dart';
import 'package:leancode_add2app_gen/src/models/route_definition.dart';
import 'package:leancode_add2app_gen/src/models/schema.dart';
import 'package:leancode_add2app_gen/src/models/type_info.dart';
import 'package:leancode_add2app_gen/src/parser/type_resolver.dart';
import 'package:leancode_add2app_gen/src/utils/naming.dart';

/// Generates Swift code for routes from a resolved schema.
///
/// Produces:
/// - Structs for routes with toList()/fromList() serialization
/// - Structs for shared types
/// - Enum definitions
/// - NativeRouteHandler protocol and base implementation
String generateSwiftRoutes({
  required Schema schema,
  required Map<String, TypeDefinition> typeGraph,
}) {
  final buffer = StringBuffer();

  // Header.
  buffer.writeln('// GENERATED CODE — DO NOT MODIFY BY HAND');
  buffer.writeln('// Generated by leancode_add2app_gen');
  buffer.writeln();
  buffer.writeln('import Foundation');
  buffer.writeln('import UIKit');
  buffer.writeln();

  // Generate enums.
  for (final enumDef in schema.enums) {
    _writeEnum(buffer, enumDef);
    buffer.writeln();
  }

  // Generate structs for shared types.
  for (final dataClass in schema.dataClasses) {
    _writeDataStruct(buffer, dataClass, typeGraph);
    buffer.writeln();
  }

  // Generate structs for Flutter routes.
  for (final route in schema.flutterRoutes) {
    _writeRouteStruct(buffer, route, typeGraph);
    buffer.writeln();
  }

  // Generate structs for native routes.
  for (final route in schema.nativeRoutes) {
    _writeRouteStruct(buffer, route, typeGraph);
    buffer.writeln();
  }

  // Generate NativeRouteHandler if there are native routes.
  if (schema.nativeRoutes.isNotEmpty) {
    _writeNativeRouteHandler(buffer, schema.nativeRoutes);
  }

  final output = buffer.toString();
  return output.endsWith('\n') ? output : '$output\n';
}

void _writeEnum(StringBuffer buffer, EnumDefinition enumDef) {
  buffer.writeln('enum ${enumDef.name}: Int {');
  for (var i = 0; i < enumDef.values.length; i++) {
    final value = enumDef.values[i];
    buffer.writeln('    case $value = $i');
  }
  buffer.writeln('}');
}

void _writeDataStruct(
  StringBuffer buffer,
  DataClassDefinition dataClass,
  Map<String, TypeDefinition> typeGraph,
) {
  final structName = dataClass.className;
  final fields = dataClass.fields;

  _writeStructWithFields(buffer, structName, fields, typeGraph);
}

void _writeRouteStruct(
  StringBuffer buffer,
  RouteDefinition route,
  Map<String, TypeDefinition> typeGraph,
) {
  final structName = route.className;
  final fields = route.fields;
  final isFlutterRoute = route.routeType == RouteType.flutter;

  buffer.writeln('struct $structName {');

  // Fields.
  for (final field in fields) {
    final swiftType = dartTypeToSwift(field.type);
    buffer.writeln('    let ${field.name}: $swiftType');
  }
  buffer.writeln();

  // Route name constant.
  buffer.writeln('    static let routeName = "${route.routeName}"');
  buffer.writeln();

  // fromList() method.
  buffer.writeln('    ${generateSwiftFromListMethod(structName, fields, typeGraph)}');
  buffer.writeln();

  // toList() method.
  buffer.writeln('    ${generateSwiftToListMethod(fields, typeGraph)}');

  // For Flutter routes, add toDict() and toPageSettings() for easier iOS navigation.
  if (isFlutterRoute) {
    buffer.writeln();
    buffer.writeln('    func toDict() -> [String: String] {');
    buffer.writeln('        [');
    for (var i = 0; i < fields.length; i++) {
      final field = fields[i];
      final comma = i < fields.length - 1 ? ',' : '';
      if (field.type.isNullable) {
        buffer.writeln(
          '            "${field.name}": ${field.name} ?? ""$comma',
        );
      } else {
        buffer.writeln('            "${field.name}": String(describing: ${field.name})$comma');
      }
    }
    buffer.writeln('        ]');
    buffer.writeln('    }');
    buffer.writeln();
    buffer.writeln(
      '    func toPageSettings() -> PageSettings {',
    );
    buffer.writeln(
      '        PageSettings(routeId: Self.routeName, params: toDict())',
    );
    buffer.writeln('    }');
  }

  buffer.writeln('}');
}

void _writeStructWithFields(
  StringBuffer buffer,
  String structName,
  List<FieldInfo> fields,
  Map<String, TypeDefinition> typeGraph,
) {
  buffer.writeln('struct $structName {');

  // Fields.
  for (final field in fields) {
    final swiftType = dartTypeToSwift(field.type);
    buffer.writeln('    let ${field.name}: $swiftType');
  }
  buffer.writeln();

  // fromList() method.
  buffer.writeln('    ${generateSwiftFromListMethod(structName, fields, typeGraph)}');
  buffer.writeln();

  // toList() method.
  buffer.writeln('    ${generateSwiftToListMethod(fields, typeGraph)}');

  buffer.writeln('}');
}

void _writeNativeRouteHandler(
  StringBuffer buffer,
  List<RouteDefinition> routes,
) {
  // Protocol.
  buffer.writeln('protocol NativeRouteHandling {');
  buffer.writeln(
    '    func handle(viewController: UIViewController, route: PageSettings)',
  );
  buffer.writeln('}');
  buffer.writeln();

  // Base class.
  buffer.writeln('class NativeRouteHandler: NativeRouteHandling {');
  buffer.writeln();

  // handle() method.
  buffer.writeln(
    '    func handle(viewController: UIViewController, route: PageSettings) {',
  );
  buffer.writeln('        switch route.routeId {');

  for (final route in routes) {
    final methodName = methodNameFromClassName(route.className);
    buffer.writeln('        case "${route.routeName}":');
    buffer.writeln('            $methodName(');
    buffer.writeln(
      '                page: ${route.className}.fromList(route.params as! [Any?]),',
    );
    buffer.writeln('                viewController: viewController');
    buffer.writeln('            )');
  }

  buffer.writeln('        default:');
  buffer.writeln(
    '            onUnknownRoute(route: route, viewController: viewController)',
  );
  buffer.writeln('        }');
  buffer.writeln('    }');
  buffer.writeln();

  // Abstract methods for each route.
  for (final route in routes) {
    final methodName = methodNameFromClassName(route.className);
    buffer.writeln(
      '    func $methodName(page: ${route.className}, viewController: UIViewController) {',
    );
    buffer.writeln('        fatalError("Must override $methodName")');
    buffer.writeln('    }');
    buffer.writeln();
  }

  // Default onUnknownRoute.
  buffer.writeln(
    '    func onUnknownRoute(route: PageSettings, viewController: UIViewController) {',
  );
  buffer.writeln(r'        fatalError("Unknown route: \(route.routeId)")');
  buffer.writeln('    }');

  buffer.writeln('}');
}
