import 'package:leancode_add2app_gen/src/generators/dart/dart_routes_generator.dart'
    show extractPathParamNames, isSimpleType;
import 'package:leancode_add2app_gen/src/generators/swift/swift_serialization.dart';
import 'package:leancode_add2app_gen/src/models/data_type_definition.dart';
import 'package:leancode_add2app_gen/src/models/route_definition.dart';
import 'package:leancode_add2app_gen/src/models/schema.dart';
import 'package:leancode_add2app_gen/src/models/type_info.dart';
import 'package:leancode_add2app_gen/src/parser/type_resolver.dart';
import 'package:leancode_add2app_gen/src/utils/naming.dart';

/// Generates Swift code for routes from a resolved schema.
///
/// Produces:
/// - Structs for routes with toList()/fromList() serialization
/// - Structs for shared types
/// - Enum definitions
/// - NativeRouteHandler protocol and base implementation
String generateSwiftRoutes({
  required Schema schema,
  required Map<String, TypeDefinition> typeGraph,
}) {
  final buffer = StringBuffer()
    // Header.
    ..writeln('// GENERATED CODE — DO NOT MODIFY BY HAND')
    ..writeln('// Generated by leancode_add2app_gen')
    ..writeln()
    ..writeln('import Foundation')
    ..writeln('import UIKit')
    ..writeln();

  // Generate enums.
  for (final enumDef in schema.enums) {
    _writeEnum(buffer, enumDef);
    buffer.writeln();
  }

  // Generate structs for shared types.
  for (final dataClass in schema.dataClasses) {
    _writeDataStruct(buffer, dataClass, typeGraph);
    buffer.writeln();
  }

  // Generate structs for Flutter routes.
  for (final route in schema.flutterRoutes) {
    _writeRouteStruct(buffer, route, typeGraph);
    buffer.writeln();
  }

  // Generate structs for native routes.
  for (final route in schema.nativeRoutes) {
    _writeRouteStruct(buffer, route, typeGraph);
    buffer.writeln();
  }

  // Generate NativeRouteHandler if there are native routes.
  if (schema.nativeRoutes.isNotEmpty) {
    _writeNativeRouteHandler(buffer, schema.nativeRoutes);
  }

  final output = buffer.toString();
  return output.endsWith('\n') ? output : '$output\n';
}

void _writeEnum(StringBuffer buffer, EnumDefinition enumDef) {
  buffer.writeln('enum ${enumDef.name}: Int {');
  for (var i = 0; i < enumDef.values.length; i++) {
    final value = enumDef.values[i];
    buffer.writeln('    case $value = $i');
  }
  buffer.writeln('}');
}

void _writeDataStruct(
  StringBuffer buffer,
  DataClassDefinition dataClass,
  Map<String, TypeDefinition> typeGraph,
) {
  final structName = dataClass.className;
  final fields = dataClass.fields;

  _writeStructWithFields(buffer, structName, fields, typeGraph);
}

void _writeRouteStruct(
  StringBuffer buffer,
  RouteDefinition route,
  Map<String, TypeDefinition> typeGraph,
) {
  final structName = route.className;
  final fields = route.fields;
  final isFlutterRoute = route.routeType == RouteType.flutter;
  final path = route.path;

  // Flutter routes conform to FlutterRoute protocol.
  if (isFlutterRoute) {
    buffer.writeln('struct $structName: FlutterRoute {');
  } else {
    buffer.writeln('struct $structName {');
  }

  // Fields.
  for (final field in fields) {
    final swiftType = dartTypeToSwift(field.type);
    buffer.writeln('    let ${field.name}: $swiftType');
  }

  buffer
    ..writeln()
    // Route name constant.
    ..writeln('    static let routeName = "${route.routeName}"');

  if (path != null) {
    buffer.writeln('    static let pathTemplate = "$path"');
  }

  buffer
    ..writeln()
    // fromList() method.
    ..writeln('    ${generateSwiftFromListMethod(structName, fields, typeGraph)}')
    ..writeln()
    // toList() method.
    ..writeln('    ${generateSwiftToListMethod(fields, typeGraph)}');

  // For Flutter routes, add toDict(), toPath(), and toPageSettings().
  if (isFlutterRoute) {
    final dictFields = fields.where((f) => isSimpleType(f.type, typeGraph)).toList();
    buffer
      ..writeln()
      ..writeln('    func toDict() -> [String: String] {')
      ..writeln('        [');
    for (var i = 0; i < dictFields.length; i++) {
      final field = dictFields[i];
      final comma = i < dictFields.length - 1 ? ',' : '';
      final valueExpr = _swiftFieldToDictValue(field, typeGraph);
      buffer.writeln('            "${field.name}": $valueExpr$comma');
    }
    buffer
      ..writeln('        ]')
      ..writeln('    }');

    if (path != null) {
      _writeSwiftToPath(buffer, path, fields, typeGraph);
    }

    buffer.writeln();
    if (path != null) {
      buffer
        ..writeln('    func toPageSettings() -> PageSettings {')
        ..writeln(
          '        PageSettings(routeId: Self.routeName, params: toList(), path: toPath())',
        )
        ..writeln('    }');
    } else {
      buffer
        ..writeln('    func toPageSettings() -> PageSettings {')
        ..writeln(
          '        PageSettings(routeId: Self.routeName, params: toList())',
        )
        ..writeln('    }');
    }
  }

  buffer.writeln('}');
}

void _writeSwiftToPath(
  StringBuffer buffer,
  String path,
  List<FieldInfo> fields,
  Map<String, TypeDefinition> typeGraph,
) {
  final pathParamNames = extractPathParamNames(path);
  final queryFields = fields.where(
    (f) =>
        !pathParamNames.contains(f.name) && isSimpleType(f.type, typeGraph),
  );

  buffer.writeln();

  // Build path expression with percent-encoded params.
  var pathExpr = path;
  for (final paramName in pathParamNames) {
    final field = fields.where((f) => f.name == paramName).firstOrNull;
    final isNullable = field?.type.isNullable ?? false;
    if (isNullable) {
      pathExpr = pathExpr.replaceAll(
        ':$paramName',
        '\\(($paramName ?? "").addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? "")',
      );
    } else {
      pathExpr = pathExpr.replaceAll(
        ':$paramName',
        '\\($paramName.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? $paramName)',
      );
    }
  }

  if (queryFields.isEmpty) {
    buffer
      ..writeln('    func toPath() -> String {')
      ..writeln('        "$pathExpr"')
      ..writeln('    }');
  } else {
    buffer
      ..writeln('    func toPath() -> String {')
      ..writeln('        let basePath = "$pathExpr"')
      ..writeln('        var query: [String] = []');
    for (final field in queryFields) {
      final name = field.name;
      final valueExpr = _swiftFieldToQueryValue(
        field.type,
        typeGraph,
        valueName: field.type.isNullable ? '${name}Val' : name,
      );
      if (field.type.isNullable) {
        buffer.writeln(
          '        if let ${name}Val = $name { query.append("$name=\\($valueExpr.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed) ?? $valueExpr)") }',
        );
      } else {
        buffer.writeln(
          '        query.append("$name=\\($valueExpr.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed) ?? $valueExpr)")',
        );
      }
    }
    buffer
      ..writeln('        if query.isEmpty { return basePath }')
      ..writeln(r'        return "\(basePath)?\(query.joined(separator: "&"))"')
      ..writeln('    }');
  }
}

String _swiftFieldToQueryValue(
  TypeInfo type,
  Map<String, TypeDefinition> typeGraph, {
  required String valueName,
}) {
  final nonNullType = _toNonNullable(type);

  if (nonNullType.name == 'String') {
    return valueName;
  }

  if (typeGraph[nonNullType.name] is EnumType) {
    return 'String($valueName.rawValue)';
  }

  return 'String(describing: $valueName)';
}

String _swiftFieldToDictValue(
  FieldInfo field,
  Map<String, TypeDefinition> typeGraph,
) {
  final name = field.name;
  final type = field.type;
  final nonNullType = _toNonNullable(type);

  if (!type.isNullable) {
    if (nonNullType.name == 'String') {
      return name;
    }
    if (typeGraph[nonNullType.name] is EnumType) {
      return 'String($name.rawValue)';
    }
    return 'String(describing: $name)';
  }

  if (nonNullType.name == 'String') {
    return '$name ?? ""';
  }
  if (typeGraph[nonNullType.name] is EnumType) {
    return '$name.map { String(\$0.rawValue) } ?? ""';
  }
  return '$name.map { String(describing: \$0) } ?? ""';
}

TypeInfo _toNonNullable(TypeInfo type) {
  return TypeInfo(
    name: type.name,
    isNullable: false,
    typeArguments: type.typeArguments,
  );
}

void _writeStructWithFields(
  StringBuffer buffer,
  String structName,
  List<FieldInfo> fields,
  Map<String, TypeDefinition> typeGraph,
) {
  buffer.writeln('struct $structName {');

  // Fields.
  for (final field in fields) {
    final swiftType = dartTypeToSwift(field.type);
    buffer.writeln('    let ${field.name}: $swiftType');
  }

  buffer
    ..writeln()
    // fromList() method.
    ..writeln('    ${generateSwiftFromListMethod(structName, fields, typeGraph)}')
    ..writeln()
    // toList() method.
    ..writeln('    ${generateSwiftToListMethod(fields, typeGraph)}')
    ..writeln('}');
}

void _writeNativeRouteHandler(
  StringBuffer buffer,
  List<RouteDefinition> routes,
) {
  buffer
    // Base class.
    ..writeln('class NativeRouteHandler: NativeRouteHandling {')
    ..writeln()
    // handle() method.
    ..writeln(
      '    func handle(viewController: UIViewController, route: PageSettings) {',
    )
    ..writeln('        switch route.routeId {');

  for (final route in routes) {
    final methodName = methodNameFromClassName(route.className);
    buffer
      ..writeln('        case "${route.routeName}":')
      ..writeln('            $methodName(')
      ..writeln(
        '                page: ${route.className}.fromList(route.params as! [Any?]),',
      )
      ..writeln('                viewController: viewController')
      ..writeln('            )');
  }

  buffer
    ..writeln('        default:')
    ..writeln(
      '            onUnknownRoute(route: route, viewController: viewController)',
    )
    ..writeln('        }')
    ..writeln('    }')
    ..writeln();

  // Abstract methods for each route.
  for (final route in routes) {
    final methodName = methodNameFromClassName(route.className);
    buffer
      ..writeln(
        '    func $methodName(page: ${route.className}, viewController: UIViewController) {',
      )
      ..writeln('        fatalError("Must override $methodName")')
      ..writeln('    }')
      ..writeln();
  }

  buffer
    // Default onUnknownRoute.
    ..writeln(
      '    func onUnknownRoute(route: PageSettings, viewController: UIViewController) {',
    )
    ..writeln(r'        fatalError("Unknown route: \(route.routeId)")')
    ..writeln('    }')
    ..writeln('}');
}
