// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


/// Describes a page to navigate to (Flutter or native).
///
/// [routeId] identifies the screen. [params] carries the page data
/// using pigeon's `encode()` output — the native side decodes it with
/// the matching pigeon-generated class's `fromList()` / `decode()`.
///
/// For Flutter pages pushed from native, [params] is a `Map<String, String>`
/// (produced by URL-decoding the `initialRoute` string).
class PageSettings {
  PageSettings({
    required this.routeId,
    this.params,
    this.path,
  });

  /// Identifies which screen to show (e.g. "soundsNotifications").
  String routeId;

  /// Page parameters. For native pages this is the pigeon-encoded object
  /// (via `encode()`). For Flutter pages this is a `Map<String, String>`.
  Object? params;

  /// URL path derived from the typed route object (e.g. "/products/42").
  /// When set, used as the `initialRoute` for router-based navigation.
  String? path;

  List<Object?> _toList() {
    return <Object?>[
      routeId,
      params,
      path,
    ];
  }

  Object encode() {
    return _toList();  }

  static PageSettings decode(Object result) {
    result as List<Object?>;
    return PageSettings(
      routeId: result[0]! as String,
      params: result[1],
      path: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PageSettings || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is PageSettings) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return PageSettings.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host API — Flutter asks the platform to push a new Activity/ViewController.
///
/// The platform side owns the Activity/ViewController stack; Flutter cannot
/// start them directly. This API hides FlutterEngine / EngineGroup /
/// Activity/ViewController internals from the developer.
class Add2AppNavigatorHostApi {
  /// Constructor for [Add2AppNavigatorHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  Add2AppNavigatorHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Push a new Flutter Activity/ViewController for the given page.
  Future<void> push(PageSettings page) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.leancode_add2app.Add2AppNavigatorHostApi.push$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[page]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Pop the current Flutter Activity/ViewController.
  Future<void> pop() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.leancode_add2app.Add2AppNavigatorHostApi.pop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Open a native Activity/ViewController identified by [route].
  ///
  /// The platform side dispatches to a registered native route handler.
  /// If no handler is registered for the given `routeId`, this is a no-op
  /// (or throws, depending on platform configuration).
  Future<void> pushNativeRoute(PageSettings route) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.leancode_add2app.Add2AppNavigatorHostApi.pushNativeRoute$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[route]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Return the full route data that the native host stored for this engine.
  ///
  /// Flutter calls this once at startup to retrieve the typed route object
  /// (with all fields, including complex nested objects). Returns `null`
  /// for the prewarm engine or when no data was set.
  Future<PageSettings?> getInitialRouteData() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.leancode_add2app.Add2AppNavigatorHostApi.getInitialRouteData$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as PageSettings?);
    }
  }
}
