import 'package:inlay_gen/src/generators/dart/dart_routes_generator.dart'
    show extractPathParamNames, isSimpleType;
import 'package:inlay_gen/src/generators/kotlin/kotlin_serialization.dart';
import 'package:inlay_gen/src/models/data_type_definition.dart';
import 'package:inlay_gen/src/models/route_definition.dart';
import 'package:inlay_gen/src/models/schema.dart';
import 'package:inlay_gen/src/models/type_info.dart';
import 'package:inlay_gen/src/parser/type_resolver.dart';
import 'package:inlay_gen/src/utils/file_header.dart';
import 'package:inlay_gen/src/utils/naming.dart';

/// Generates Kotlin code for routes from a resolved schema.
///
/// Produces:
/// - Data classes for routes with toList()/fromList() serialization
/// - Data classes for shared types
/// - Enum classes
/// - NativeRouteHandler base class
String generateKotlinRoutes({
  required Schema schema,
  required Map<String, TypeDefinition> typeGraph,
  required String packageName,
  required String schemaFingerprint,
  List<String> header = const [],
}) {
  final hasFlutterRoutes = schema.flutterRoutes.isNotEmpty;
  final hasDialogRoutes = schema.flutterDialogRoutes.isNotEmpty;
  final hasFlutterRoutesWithResult = schema.flutterRoutes.any(
    (r) => r.resultType != null,
  );
  final hasDialogRoutesWithResult = schema.flutterDialogRoutes.any(
    (r) => r.resultType != null,
  );
  final buffer = StringBuffer(renderFileHeader(header))
    // Header.
    ..writeln('// GENERATED CODE — DO NOT MODIFY BY HAND')
    ..writeln('// Generated by inlay_gen')
    ..writeln()
    ..writeln('package $packageName')
    ..writeln()
    ..writeln('import android.content.Context')
    ..writeln('import android.net.Uri');
  if (hasFlutterRoutes) {
    buffer.writeln('import co.leancode.inlay.FlutterRoute');
  }
  if (hasFlutterRoutesWithResult) {
    buffer.writeln('import co.leancode.inlay.FlutterRouteWithResult');
  }
  if (hasDialogRoutes) {
    buffer.writeln('import co.leancode.inlay.FlutterDialogRoute');
  }
  if (hasDialogRoutesWithResult) {
    buffer.writeln('import co.leancode.inlay.FlutterDialogRouteWithResult');
  }
  buffer
    ..writeln(
      'import co.leancode.inlay.NativeRouteHandler as NativeRouteHandling',
    )
    ..writeln('import co.leancode.inlay.navigator.PageSettings')
    ..writeln()
    ..writeln('/**')
    ..writeln(' * Fingerprint of the schema this file was generated from.')
    ..writeln(' *')
    ..writeln(
      ' * Embedded into every outgoing [PageSettings] and verified by the',
    )
    ..writeln(
      ' * generated route handler, so host/module schema drift fails fast.',
    )
    ..writeln(' */')
    ..writeln('object InlaySchema {')
    ..writeln('    const val FINGERPRINT = "$schemaFingerprint"')
    ..writeln('}')
    ..writeln();

  // Generate enums.
  for (final enumDef in schema.enums) {
    _writeEnum(buffer, enumDef);
    buffer.writeln();
  }

  // Generate data classes for shared types.
  for (final dataClass in schema.dataClasses) {
    _writeDataClass(buffer, dataClass, typeGraph);
    buffer.writeln();
  }

  // Generate data classes for Flutter routes.
  for (final route in schema.flutterRoutes) {
    _writeRouteDataClass(buffer, route, typeGraph);
    buffer.writeln();
  }

  // Generate data classes for Flutter dialog routes.
  for (final route in schema.flutterDialogRoutes) {
    _writeRouteDataClass(buffer, route, typeGraph);
    buffer.writeln();
  }

  // Generate data classes for native routes.
  for (final route in schema.nativeRoutes) {
    _writeRouteDataClass(buffer, route, typeGraph);
    buffer.writeln();
  }

  // Generate NativeRouteHandler if there are native routes.
  if (schema.nativeRoutes.isNotEmpty) {
    _writeNativeRouteHandler(buffer, schema.nativeRoutes);
  }

  final output = buffer.toString();
  return output.endsWith('\n') ? output : '$output\n';
}

void _writeEnum(StringBuffer buffer, EnumDefinition enumDef) {
  buffer.writeln('enum class ${enumDef.name} {');
  for (var i = 0; i < enumDef.values.length; i++) {
    final value = enumDef.values[i];
    if (i < enumDef.values.length - 1) {
      buffer.writeln('    $value,');
    } else {
      buffer.writeln('    $value');
    }
  }
  buffer.writeln('}');
}

void _writeDataClass(
  StringBuffer buffer,
  DataClassDefinition dataClass,
  Map<String, TypeDefinition> typeGraph,
) {
  final className = dataClass.className;
  final fields = dataClass.fields;

  _writeDataClassWithFields(buffer, className, fields, typeGraph);
}

void _writeRouteDataClass(
  StringBuffer buffer,
  RouteDefinition route,
  Map<String, TypeDefinition> typeGraph,
) {
  final className = route.className;
  final fields = route.fields;
  final isFlutterRoute = route.routeType == RouteType.flutter;
  final isDialogRoute = route.routeType == RouteType.flutterDialog;
  final path = route.path;

  // A Kotlin data class needs at least one constructor parameter, so
  // parameterless routes are plain classes.
  final classKeyword = fields.isEmpty ? 'class' : 'data class';
  buffer.write('$classKeyword $className(');
  if (fields.isNotEmpty) {
    buffer.writeln();
    for (var i = 0; i < fields.length; i++) {
      final field = fields[i];
      final kotlinType = dartTypeToKotlin(field.type);
      final comma = i < fields.length - 1 ? ',' : '';
      buffer.writeln('    val ${field.name}: $kotlinType$comma');
    }
  }

  // Flutter routes implement FlutterRoute, dialog routes FlutterDialogRoute;
  // routes declaring a result type implement the typed WithResult variants
  // so native callers receive an already-decoded result.
  final resultType = route.resultType;
  final kotlinResultType = resultType != null
      ? dartTypeToKotlin(resultType)
      : null;
  if (isFlutterRoute) {
    buffer.writeln(
      kotlinResultType != null
          ? ') : FlutterRouteWithResult<$kotlinResultType> {'
          : ') : FlutterRoute {',
    );
  } else if (isDialogRoute) {
    buffer.writeln(
      kotlinResultType != null
          ? ') : FlutterDialogRouteWithResult<$kotlinResultType> {'
          : ') : FlutterDialogRoute {',
    );
  } else {
    buffer.writeln(') {');
  }

  // Route name constant + path template.
  buffer
    ..writeln('    companion object {')
    ..writeln('        const val ROUTE_NAME = "${route.routeName}"');
  if (path != null) {
    buffer.writeln('        const val PATH_TEMPLATE = "$path"');
  }
  buffer
    ..writeln()
    ..writeln(
      '        ${generateKotlinFromListMethod(className, fields, typeGraph)}',
    );

  // Result codecs: native routes encode (handler side), Flutter/dialog
  // routes decode (native caller side). Emitting both is harmless.
  final result = route.resultType;
  if (result != null) {
    final kotlinResult = dartTypeToKotlin(result);
    final encode = generateKotlinEncode('result', result, typeGraph);
    final decode = generateKotlinDecode('raw', result, typeGraph);
    buffer
      ..writeln()
      ..writeln(
        '        fun encodeResult(result: $kotlinResult): Any? = $encode',
      )
      ..writeln()
      ..writeln('        fun decodeResult(raw: Any?): $kotlinResult? =')
      ..writeln('            if (raw == null) null else $decode');
  }

  buffer.writeln('    }');

  // Instance-level typed decode for the WithResult interfaces.
  if (kotlinResultType != null && (isFlutterRoute || isDialogRoute)) {
    buffer
      ..writeln()
      ..writeln(
        '    override fun decodeResult(raw: Any?): $kotlinResultType? = '
        'Companion.decodeResult(raw)',
      );
  }

  buffer
    ..writeln()
    // toList() method.
    ..writeln('    ${generateKotlinToListMethod(fields, typeGraph)}');

  // For Flutter/dialog routes, add toMap(), toPath(), and toPageSettings().
  if (isFlutterRoute || isDialogRoute) {
    buffer
      ..writeln()
      ..writeln('    fun toMap(): Map<String, String> = mapOf(');
    for (var i = 0; i < fields.length; i++) {
      final field = fields[i];
      final comma = i < fields.length - 1 ? ',' : '';
      if (field.type.isNullable) {
        buffer.writeln(
          '        "${field.name}" to (${field.name}?.toString() ?: "")$comma',
        );
      } else {
        buffer.writeln(
          '        "${field.name}" to ${field.name}.toString()$comma',
        );
      }
    }
    buffer.writeln('    )');

    if (path != null) {
      _writeKotlinToPath(buffer, path, fields, typeGraph);
    }

    buffer.writeln();
    if (path != null) {
      buffer.writeln(
        '    override fun toPageSettings(): PageSettings = PageSettings(ROUTE_NAME, toList(), toPath(), InlaySchema.FINGERPRINT)',
      );
    } else {
      buffer.writeln(
        '    override fun toPageSettings(): PageSettings = PageSettings(ROUTE_NAME, toList(), schemaFingerprint = InlaySchema.FINGERPRINT)',
      );
    }
  }

  buffer.writeln('}');
}

void _writeKotlinToPath(
  StringBuffer buffer,
  String path,
  List<FieldInfo> fields,
  Map<String, TypeDefinition> typeGraph,
) {
  final pathParamNames = extractPathParamNames(path);
  final queryFields = fields.where(
    (f) => !pathParamNames.contains(f.name) && isSimpleType(f.type, typeGraph),
  );

  buffer.writeln();

  // Build path expression with URI-encoded params.
  var pathExpr = path;
  for (final paramName in pathParamNames) {
    final field = fields.where((f) => f.name == paramName).firstOrNull;
    final isNullable = field?.type.isNullable ?? false;
    final encode = isNullable
        ? '\${Uri.encode($paramName ?: "")}'
        : '\${Uri.encode($paramName)}';
    pathExpr = pathExpr.replaceAll(':$paramName', encode);
  }

  if (queryFields.isEmpty) {
    buffer.writeln('    fun toPath(): String = "$pathExpr"');
  } else {
    buffer
      ..writeln('    fun toPath(): String {')
      ..writeln('        val basePath = "$pathExpr"')
      ..writeln('        val query = mutableListOf<String>()');
    for (final field in queryFields) {
      final name = field.name;
      if (field.type.isNullable) {
        buffer.writeln(
          '        $name?.let { query.add("$name=\${Uri.encode(it.toString())}") }',
        );
      } else {
        buffer.writeln(
          '        query.add("$name=\${Uri.encode($name.toString())}")',
        );
      }
    }
    buffer
      ..writeln('        if (query.isEmpty()) return basePath')
      ..writeln(r'        return "$basePath?${query.joinToString("&")}"')
      ..writeln('    }');
  }
}

void _writeDataClassWithFields(
  StringBuffer buffer,
  String className,
  List<FieldInfo> fields,
  Map<String, TypeDefinition> typeGraph,
) {
  buffer.writeln('data class $className(');
  for (var i = 0; i < fields.length; i++) {
    final field = fields[i];
    final kotlinType = dartTypeToKotlin(field.type);
    final comma = i < fields.length - 1 ? ',' : '';
    buffer.writeln('    val ${field.name}: $kotlinType$comma');
  }

  buffer
    ..writeln(') {')
    // companion object with fromList.
    ..writeln('    companion object {')
    ..writeln(
      '        ${generateKotlinFromListMethod(className, fields, typeGraph)}',
    )
    ..writeln('    }')
    ..writeln()
    // toList() method.
    ..writeln('    ${generateKotlinToListMethod(fields, typeGraph)}')
    ..writeln('}');
}

void _writeNativeRouteHandler(
  StringBuffer buffer,
  List<RouteDefinition> routes,
) {
  buffer
    ..writeln('abstract class NativeRouteHandler : NativeRouteHandling {')
    ..writeln()
    // handle() method.
    ..writeln(
      '    override fun handle(context: Context, route: PageSettings, completion: (Any?) -> Unit) {',
    )
    ..writeln('        route.schemaFingerprint?.let { remote ->')
    ..writeln('            check(remote == InlaySchema.FINGERPRINT) {')
    ..writeln(
      '                "Inlay schema mismatch: the Flutter module sent a route generated " +',
    )
    ..writeln(
      r'                    "from schema $remote, but this host was built against schema " +',
    )
    ..writeln(
      r'                    "${InlaySchema.FINGERPRINT}. Re-run inlay_gen and rebuild both sides " +',
    )
    ..writeln('                    "from the same schema revision."')
    ..writeln('            }')
    ..writeln('        }')
    ..writeln('        when (route.routeId) {');

  for (final route in routes) {
    final methodName = methodNameFromClassName(route.className);
    final result = route.resultType;
    final decodedPage =
        '${route.className}.fromList(route.params as List<Any?>)';
    buffer.writeln('            "${route.routeName}" -> {');
    if (result != null) {
      // Developer completes with the typed result; we encode it for the wire.
      buffer.writeln(
        '                $methodName($decodedPage, context) { result -> '
        'completion(${route.className}.encodeResult(result)) }',
      );
    } else {
      // No result type: complete with null once the handler is invoked.
      buffer
        ..writeln('                $methodName($decodedPage, context)')
        ..writeln('                completion(null)');
    }
    buffer.writeln('            }');
  }

  buffer
    ..writeln('            else -> {')
    ..writeln('                onUnknownRoute(route, context)')
    ..writeln('                completion(null)')
    ..writeln('            }')
    ..writeln('        }')
    ..writeln('    }')
    ..writeln();

  // Abstract methods for each route.
  for (final route in routes) {
    final methodName = methodNameFromClassName(route.className);
    final result = route.resultType;
    if (result != null) {
      final kotlinResult = dartTypeToKotlin(result);
      buffer.writeln(
        '    abstract fun $methodName(page: ${route.className}, '
        'context: Context, completion: ($kotlinResult) -> Unit)',
      );
    } else {
      buffer.writeln(
        '    abstract fun $methodName(page: ${route.className}, context: Context)',
      );
    }
  }

  buffer
    ..writeln()
    // Default onUnknownRoute.
    ..writeln(
      '    open fun onUnknownRoute(route: PageSettings, context: Context) {',
    )
    ..writeln(
      r'        throw IllegalArgumentException("Unknown route: ${route.routeId}")',
    )
    ..writeln('    }')
    ..writeln('}');
}
