import 'package:inlay_gen/src/generators/kotlin/kotlin_serialization.dart';
import 'package:inlay_gen/src/models/data_type_definition.dart';
import 'package:inlay_gen/src/models/schema.dart';
import 'package:inlay_gen/src/models/store_definition.dart';
import 'package:inlay_gen/src/models/type_info.dart';
import 'package:inlay_gen/src/parser/type_resolver.dart';

/// Generates Kotlin code for stores from a resolved schema.
///
/// Produces:
/// - Store classes with typed getters/setters via NativeStorageScope
String generateKotlinStores({
  required Schema schema,
  required Map<String, TypeDefinition> typeGraph,
  required String packageName,
  String? schemaFingerprint,
}) {
  final needsJson = _storesRequireJson(schema, typeGraph);
  final buffer = StringBuffer()
    // Header.
    ..writeln('// GENERATED CODE — DO NOT MODIFY BY HAND')
    ..writeln('// Generated by inlay_gen')
    ..writeln()
    ..writeln('package $packageName')
    ..writeln()
    ..writeln('import co.leancode.inlay.NativeStorageScope')
    ..writeln('import co.leancode.inlay.storage.StorageEntry');

  if (needsJson) {
    buffer
      ..writeln('import org.json.JSONArray')
      ..writeln('import org.json.JSONObject');
  }

  buffer.writeln();

  if (schemaFingerprint != null) {
    buffer
      ..writeln('/**')
      ..writeln(' * Fingerprint of the schema this file was generated from.')
      ..writeln(' *')
      ..writeln(
        ' * Register with `InlayNavigator.setSchemaFingerprint(InlaySchema.FINGERPRINT)`',
      )
      ..writeln(
        ' * so Flutter engines can detect a module built from a different schema revision.',
      )
      ..writeln(' */')
      ..writeln('object InlaySchema {')
      ..writeln('    const val FINGERPRINT = "$schemaFingerprint"')
      ..writeln('}')
      ..writeln();
  }

  if (needsJson) {
    _writeJsonToKotlinHelper(buffer);
    buffer.writeln();
  }

  // Generate store-only enums.
  for (final enumDef in schema.enums) {
    _writeEnum(buffer, enumDef);
    buffer.writeln();
  }

  // Generate store-only data classes.
  for (final dataClass in schema.dataClasses) {
    _writeDataClass(buffer, dataClass, typeGraph);
    buffer.writeln();
  }

  // Generate store classes.
  for (final store in schema.stores) {
    _writeStoreClass(buffer, store, typeGraph);
    buffer.writeln();
  }

  final output = buffer.toString();
  return output.endsWith('\n') ? output : '$output\n';
}

void _writeStoreClass(
  StringBuffer buffer,
  StoreDefinition store,
  Map<String, TypeDefinition> typeGraph,
) {
  final className = store.className;
  final storeKey = store.storeKey;
  final keyField = store.keyField;
  final valueFields = store.valueFields;

  buffer
    ..writeln('/**')
    ..writeln(' * Generated store wrapper for $className.')
    ..writeln(' */')
    // Class declaration.
    ..write('class $className(')
    ..writeln()
    ..writeln('    private val storage: NativeStorageScope,');
  if (keyField != null) {
    final kotlinType = dartTypeToKotlin(keyField.type);
    buffer.writeln('    private val ${keyField.name}: $kotlinType,');
  }
  buffer
    ..writeln(') {')
    ..writeln();

  // Key prefix and key helper.
  if (keyField == null) {
    buffer
      ..writeln('    val keyPrefix: String get() = "$storeKey/"')
      ..writeln()
      ..writeln('    private fun key(field: String) = "$storeKey/\$field"');
  } else {
    final keySegment = _keySegmentExpression(keyField, typeGraph);
    buffer
      ..writeln('    val keyPrefix: String get() = "$storeKey/$keySegment/"')
      ..writeln()
      ..writeln(
        '    private fun key(field: String) = "$storeKey/$keySegment/\$field"',
      );
  }
  buffer
    ..writeln()
    // containsChanges helper.
    ..writeln(
      '    fun containsChanges(entries: List<StorageEntry>) = entries.any { it.key.startsWith(keyPrefix) }',
    )
    ..writeln();

  // Properties for each value field.
  for (final field in valueFields) {
    _writeProperty(buffer, field, typeGraph);
    buffer.writeln();
  }

  // clear() method.
  buffer
    ..writeln('    fun clear() = storage.removeByPrefix(key(""))')
    ..writeln('}');
}

void _writeProperty(
  StringBuffer buffer,
  FieldInfo field,
  Map<String, TypeDefinition> typeGraph,
) {
  if (isSimpleStoreType(field.type, typeGraph)) {
    _writeSimpleProperty(buffer, field, typeGraph);
  } else {
    _writeComplexProperty(buffer, field, typeGraph);
  }
}

void _writeSimpleProperty(
  StringBuffer buffer,
  FieldInfo field,
  Map<String, TypeDefinition> typeGraph,
) {
  final baseName = field.type.baseName;
  final enumType = typeGraph[baseName] is EnumType
      ? typeGraph[baseName]! as EnumType
      : null;
  final kotlinType = _kotlinStoreType(baseName, enumType);
  final rawDefault =
      field.defaultValue ?? _defaultValueForType(baseName, enumType);
  final defaultVal = _dartToKotlinLiteral(rawDefault, baseName);

  buffer.writeln('    var ${field.name}: $kotlinType');

  // Getter.
  if (enumType != null) {
    buffer
      ..writeln(
        '        get() = storage.get(key("${field.name}"))?.toIntOrNull()?.let { $baseName.entries[it] } ?: $defaultVal',
      )
      ..writeln(
        '        set(value) = storage.put(key("${field.name}"), value.ordinal.toString())',
      );
    return;
  }

  switch (baseName) {
    case 'bool':
      if (defaultVal == 'true') {
        buffer.writeln(
          '        get() = storage.get(key("${field.name}")) != "false"',
        );
      } else {
        buffer.writeln(
          '        get() = storage.get(key("${field.name}")) == "true"',
        );
      }
    case 'int':
      buffer.writeln(
        '        get() = storage.get(key("${field.name}"))?.toLongOrNull() ?: $defaultVal',
      );
    case 'double':
      buffer.writeln(
        '        get() = storage.get(key("${field.name}"))?.toDoubleOrNull() ?: $defaultVal',
      );
    case 'String':
      buffer.writeln(
        '        get() = storage.get(key("${field.name}")) ?: $defaultVal',
      );
    default:
      buffer.writeln('        get() = storage.get(key("${field.name}")) ?: ""');
  }

  // Setter.
  switch (baseName) {
    case 'String':
      buffer.writeln(
        '        set(value) = storage.put(key("${field.name}"), value)',
      );
    default:
      buffer.writeln(
        '        set(value) = storage.put(key("${field.name}"), value.toString())',
      );
  }
}

void _writeComplexProperty(
  StringBuffer buffer,
  FieldInfo field,
  Map<String, TypeDefinition> typeGraph,
) {
  final kotlinType = dartTypeToKotlin(field.type);
  final jsonWrapper = _jsonWrapperType(field.type, typeGraph);

  buffer.writeln('    var ${field.name}: $kotlinType');

  // Getter.
  if (field.type.isNullable) {
    final decodeExpr = generateKotlinDecode(
      'decoded',
      field.type.toNonNullable(),
      typeGraph,
    );
    buffer
      ..writeln('        get() {')
      ..writeln(
        '            val raw = storage.get(key("${field.name}")) ?: return null',
      )
      ..writeln('            val decoded = jsonToKotlin($jsonWrapper(raw))')
      ..writeln('            return $decodeExpr')
      ..writeln('        }');
  } else {
    final decodeExpr = generateKotlinDecode('decoded', field.type, typeGraph);
    final rawDefault = field.defaultValue ?? 'emptyList()';
    final defaultVal = _dartToKotlinLiteral(rawDefault, field.type.baseName);
    buffer
      ..writeln('        get() {')
      ..writeln(
        '            val raw = storage.get(key("${field.name}")) ?: return $defaultVal',
      )
      ..writeln('            val decoded = jsonToKotlin($jsonWrapper(raw))')
      ..writeln('            return $decodeExpr')
      ..writeln('        }');
  }

  // Setter.
  if (field.type.isNullable) {
    final encodeExpr = generateKotlinEncode(
      'value',
      field.type.toNonNullable(),
      typeGraph,
    );
    buffer
      ..writeln('        set(value) {')
      ..writeln('            if (value == null) {')
      ..writeln('                storage.remove(key("${field.name}"))')
      ..writeln('                return')
      ..writeln('            }')
      ..writeln(
        '            storage.put(key("${field.name}"), $jsonWrapper($encodeExpr).toString())',
      )
      ..writeln('        }');
  } else {
    final encodeExpr = generateKotlinEncode('value', field.type, typeGraph);
    buffer.writeln(
      '        set(value) = storage.put(key("${field.name}"), $jsonWrapper($encodeExpr).toString())',
    );
  }
}

String _kotlinStoreType(String dartType, EnumType? enumType) {
  if (enumType != null) {
    return enumType.name;
  }

  switch (dartType) {
    case 'bool':
      return 'Boolean';
    case 'int':
      return 'Long';
    case 'double':
      return 'Double';
    case 'String':
      return 'String';
    default:
      return 'String';
  }
}

String _defaultValueForType(String dartType, EnumType? enumType) {
  if (enumType != null) {
    return '${enumType.name}.${enumType.values.first}';
  }

  switch (dartType) {
    case 'bool':
      return 'false';
    case 'int':
      return '0L';
    case 'double':
      return '0.0';
    case 'String':
      return '""';
    default:
      return '""';
  }
}

/// Converts a Dart literal to its Kotlin equivalent.
///
/// Handles string literals (single → double quotes) and
/// collection literals (const [] → emptyList(), const {} → emptyMap()).
String _dartToKotlinLiteral(String dartLiteral, String dartType) {
  if (dartType == 'String') {
    if (dartLiteral.startsWith("'") && dartLiteral.endsWith("'")) {
      final content = dartLiteral.substring(1, dartLiteral.length - 1);
      return '"$content"';
    }
  }
  if (dartLiteral == 'const []' || dartLiteral == '[]') {
    return 'emptyList()';
  }
  if (dartLiteral == 'const {}' || dartLiteral == '{}') {
    return 'emptyMap()';
  }
  return dartLiteral;
}

String _keySegmentExpression(
  FieldInfo keyField,
  Map<String, TypeDefinition> typeGraph,
) {
  if (typeGraph[keyField.type.baseName] is EnumType) {
    return '\${${keyField.name}.name}';
  }
  return '\$${keyField.name}';
}

bool _storesRequireJson(Schema schema, Map<String, TypeDefinition> typeGraph) {
  for (final store in schema.stores) {
    for (final field in store.valueFields) {
      if (!isSimpleStoreType(field.type, typeGraph)) {
        return true;
      }
    }
  }
  return false;
}

/// Returns the JSONArray or JSONObject wrapper based on the underlying type.
///
/// Lists and data classes (which encode to lists) use JSONArray.
/// Maps use JSONObject.
String _jsonWrapperType(TypeInfo type, Map<String, TypeDefinition> typeGraph) {
  if (type.baseName == 'Map') {
    return 'JSONObject';
  }
  // Lists and data classes (which encode to List<Object?>) use JSONArray.
  return 'JSONArray';
}

void _writeEnum(StringBuffer buffer, EnumDefinition enumDef) {
  buffer.writeln('enum class ${enumDef.name} {');
  for (var i = 0; i < enumDef.values.length; i++) {
    final value = enumDef.values[i];
    if (i < enumDef.values.length - 1) {
      buffer.writeln('    $value,');
    } else {
      buffer.writeln('    $value');
    }
  }
  buffer.writeln('}');
}

void _writeDataClass(
  StringBuffer buffer,
  DataClassDefinition dataClass,
  Map<String, TypeDefinition> typeGraph,
) {
  final className = dataClass.className;
  final fields = dataClass.fields;

  buffer.writeln('data class $className(');
  for (var i = 0; i < fields.length; i++) {
    final field = fields[i];
    final kotlinType = dartTypeToKotlin(field.type);
    final comma = i < fields.length - 1 ? ',' : '';
    buffer.writeln('    val ${field.name}: $kotlinType$comma');
  }

  buffer
    ..writeln(') {')
    ..writeln('    companion object {')
    ..writeln(
      '        ${generateKotlinFromListMethod(className, fields, typeGraph)}',
    )
    ..writeln('    }')
    ..writeln()
    ..writeln('    ${generateKotlinToListMethod(fields, typeGraph)}')
    ..writeln('}');
}

void _writeJsonToKotlinHelper(StringBuffer buffer) {
  buffer
    ..writeln('private fun jsonToKotlin(json: Any?): Any? {')
    ..writeln('    return when (json) {')
    ..writeln(
      '        is JSONArray -> (0 until json.length()).map { jsonToKotlin(json.opt(it)) }',
    )
    ..writeln(
      '        is JSONObject -> json.keys().asSequence().associateWith { jsonToKotlin(json.opt(it)) }',
    )
    ..writeln('        JSONObject.NULL -> null')
    ..writeln(
      '        is Number -> json.toLong().let { l -> if (l in Int.MIN_VALUE..Int.MAX_VALUE) l.toInt() else l }',
    )
    ..writeln('        else -> json')
    ..writeln('    }')
    ..writeln('}');
}
