import 'package:leancode_add2app_gen/src/models/page_definition.dart';
import 'package:leancode_add2app_gen/src/models/page_field.dart';
import 'package:leancode_add2app_gen/src/utils/naming.dart';

/// Generates Dart `Add2AppFlutterRoute` wrappers for `flutter_page` schema classes.
///
/// Example output:
/// ```dart
/// class SoundsNotificationsPage extends Add2AppFlutterRoute {
///   const SoundsNotificationsPage({required this.contactId});
///
///   final String contactId;
///
///   @override
///   String get routeId => 'soundsNotifications';
///
///   @override
///   Map<String, String> get params => {'contactId': contactId};
/// }
/// ```
String generateDartFlutterPages({required List<PageDefinition> flutterPages}) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE — DO NOT MODIFY BY HAND')
    ..writeln('// Generated by leancode_add2app_gen')
    ..writeln()
    ..writeln("import 'package:flutter/widgets.dart';")
    ..writeln("import 'package:leancode_add2app/leancode_add2app.dart';")
    ..writeln();

  for (final page in flutterPages) {
    _writeClass(buffer, page);
    buffer.writeln();
  }

  _writeHandlerClass(buffer, flutterPages);

  final output = buffer.toString();
  return output.endsWith('\n') ? output : '$output\n';
}

void _writeClass(StringBuffer buffer, PageDefinition page) {
  final routeId = routeIdFromClassName(page.className);
  final className = page.className;

  buffer
    ..writeln('class $className extends Add2AppFlutterRoute {')
    ..writeln('  const $className(${_constructorParams(page.fields)});')
    ..writeln();

  for (final field in page.fields) {
    final suffix = field.isNullable ? '?' : '';
    buffer.writeln('  final ${field.dartType}$suffix ${field.name};');
  }

  if (page.fields.isNotEmpty) {
    buffer.writeln();
  }

  buffer
    ..writeln("  static const String routeName = '$routeId';")
    ..writeln()
    ..writeln('  static $className fromParams(Map<String, String> params) {')
    ..writeln(
      '    return $className(${_fromParamsArgs(className, page.fields)});',
    )
    ..writeln('  }')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  String get routeId => routeName;')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Map<String, String> get params => ${_paramsMap(page.fields)};')
    ..writeln('}');
}

String _constructorParams(List<PageField> fields) {
  if (fields.isEmpty) {
    return '';
  }

  final params = fields
      .map((field) {
        final required = field.isRequired ? 'required ' : '';
        return '${required}this.${field.name}';
      })
      .join(', ');

  return '{$params}';
}

String _paramsMap(List<PageField> fields) {
  if (fields.isEmpty) {
    return '{}';
  }

  final buffer = StringBuffer()..writeln('{');

  for (final field in fields) {
    if (field.isNullable) {
      buffer.writeln(
        "    ...?${field.name} != null ? {'${field.name}': ${_toStringExpr(field, nonNull: true)}} : null,",
      );
    } else {
      buffer.writeln(
        "    '${field.name}': ${_toStringExpr(field, nonNull: false)},",
      );
    }
  }

  buffer.write('  }');
  return buffer.toString();
}

String _toStringExpr(PageField field, {required bool nonNull}) {
  final value = nonNull ? '${field.name}!' : field.name;
  return field.dartType == 'String' ? value : '$value.toString()';
}

String _fromParamsArgs(String className, List<PageField> fields) {
  if (fields.isEmpty) {
    return '';
  }

  final args = fields
      .map((field) {
        final valueExpr = _fromParamsValueExpr(className, field);
        return '${field.name}: $valueExpr';
      })
      .join(', ');

  return args;
}

String _fromParamsValueExpr(String className, PageField field) {
  final rawValue = "params['${field.name}']";

  if (field.isNullable) {
    return _decodeNullable(rawValue, field.dartType);
  }

  return _decodeRequired(className, rawValue, field);
}

String _decodeRequired(String className, String rawValue, PageField field) {
  final requiredValue =
      '$rawValue ?? '
      "(throw ArgumentError('Missing required param ${field.name} for $className'))";
  return _parseValue(requiredValue, field.dartType);
}

String _decodeNullable(String rawValue, String dartType) {
  switch (dartType) {
    case 'String':
      return rawValue;
    case 'int':
      return '$rawValue != null ? int.parse($rawValue) : null';
    case 'double':
      return '$rawValue != null ? double.parse($rawValue) : null';
    case 'num':
      return '$rawValue != null ? num.parse($rawValue) : null';
    case 'bool':
      return '$rawValue != null ? ($rawValue == \'true\') : null';
    default:
      return '$rawValue != null ? '
          "(throw UnsupportedError('Unsupported nullable type: $dartType')) "
          ': null';
  }
}

String _parseValue(String value, String dartType) {
  switch (dartType) {
    case 'String':
      return value;
    case 'int':
      return 'int.parse($value)';
    case 'double':
      return 'double.parse($value)';
    case 'num':
      return 'num.parse($value)';
    case 'bool':
      return "($value == 'true')";
    default:
      return "(throw UnsupportedError('Unsupported type: $dartType'))";
  }
}

void _writeHandlerClass(
  StringBuffer buffer,
  List<PageDefinition> flutterPages,
) {
  buffer
    ..writeln('abstract class FlutterRouteHandler {')
    ..writeln('  const FlutterRouteHandler();')
    ..writeln()
    ..writeln('  Widget handle(PageSettings route) {')
    ..writeln('    switch (route.routeId) {');

  for (final page in flutterPages) {
    final routeId = routeIdFromClassName(page.className);
    final methodName = methodNameFromClassName(page.className);
    buffer
      ..writeln("      case '$routeId':")
      ..writeln(
        '        return $methodName(${page.className}.fromParams(_asMap(route.params)));',
      );
  }

  buffer
    ..writeln('      default:')
    ..writeln('        return onUnknownRoute(route);')
    ..writeln('    }')
    ..writeln('  }')
    ..writeln();

  for (final page in flutterPages) {
    final methodName = methodNameFromClassName(page.className);
    buffer.writeln('  Widget $methodName(${page.className} page);');
  }

  buffer
    ..writeln()
    ..writeln('  Widget onUnknownRoute(PageSettings route) {')
    ..writeln(
      "    return Center(child: Text('Unknown route: \${route.routeId}'));",
    )
    ..writeln('  }')
    ..writeln()
    ..writeln(
      '  static Map<String, String> _asMap(Object? raw) => raw is Map<String, String>',
    )
    ..writeln('      ? raw')
    ..writeln(
      "      : (raw is Map ? Map<String, String>.from(raw) : const {});",
    )
    ..writeln('}');
}
