import 'package:leancode_add2app_gen/src/models/page_definition.dart';
import 'package:leancode_add2app_gen/src/utils/naming.dart';

/// Generates Dart extensions on pigeon-generated native_page classes that
/// add `.toNativeRoute()` using pigeon's own `encode()`.
///
/// Example output:
/// ```dart
/// extension NativeEditProfilePageToNativeRoute on NativeEditProfilePage {
///   static const String routeId = 'nativeEditProfile';
///
///   Add2AppNativeRoute toNativeRoute() {
///     return Add2AppNativeRoute(
///       PageSettings(routeId: routeId, params: encode()),
///     );
///   }
/// }
/// ```
String generateDartNativePages({
  required List<PageDefinition> nativePages,
  required String pigeonDartImport,
}) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE — DO NOT MODIFY BY HAND')
    ..writeln('// Generated by leancode_add2app_gen')
    ..writeln()
    ..writeln(
      "import 'package:leancode_add2app/leancode_add2app.dart' "
      'show Add2AppNativeRoute, PageSettings;',
    )
    ..writeln("import '$pigeonDartImport';")
    ..writeln();

  for (final page in nativePages) {
    _writeExtension(buffer, page);
    buffer.writeln();
  }

  return buffer.toString();
}

void _writeExtension(StringBuffer buffer, PageDefinition page) {
  final routeId = routeIdFromClassName(page.className);

  buffer
    ..writeln(
      'extension ${page.className}ToNativeRoute on ${page.className} {',
    )
    ..writeln("  static const String routeId = '$routeId';")
    ..writeln()
    ..writeln('  Add2AppNativeRoute toNativeRoute() {')
    ..writeln('    return Add2AppNativeRoute(')
    ..writeln("      PageSettings(routeId: '$routeId', params: encode()),")
    ..writeln('    );')
    ..writeln('  }')
    ..writeln('}');
}
