import 'package:leancode_add2app_gen/src/models/page_definition.dart';
import 'package:leancode_add2app_gen/src/models/page_field.dart';
import 'package:leancode_add2app_gen/src/utils/naming.dart';

/// Generates Dart `Add2AppFlutterRoute` wrappers for `flutter_page` schema classes.
///
/// Example output:
/// ```dart
/// class SoundsNotificationsPage extends Add2AppFlutterRoute {
///   const SoundsNotificationsPage({required this.contactId});
///
///   final String contactId;
///
///   @override
///   String get routeId => 'soundsNotifications';
///
///   @override
///   Map<String, String> get params => {'contactId': contactId};
/// }
/// ```
String generateDartFlutterPages({
  required List<PageDefinition> flutterPages,
}) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE — DO NOT MODIFY BY HAND')
    ..writeln('// Generated by leancode_add2app_gen')
    ..writeln()
    ..writeln("import 'package:leancode_add2app/leancode_add2app.dart';")
    ..writeln();

  for (final page in flutterPages) {
    _writeClass(buffer, page);
    buffer.writeln();
  }

  final output = buffer.toString();
  return output.endsWith('\n') ? output : '$output\n';
}

void _writeClass(StringBuffer buffer, PageDefinition page) {
  final routeId = routeIdFromClassName(page.className);

  buffer
    ..writeln('class ${page.className} extends Add2AppFlutterRoute {')
    ..writeln('  const ${page.className}(${_constructorParams(page.fields)});')
    ..writeln();

  for (final field in page.fields) {
    final suffix = field.isNullable ? '?' : '';
    buffer.writeln('  final ${field.dartType}$suffix ${field.name};');
  }

  if (page.fields.isNotEmpty) {
    buffer.writeln();
  }

  buffer
    ..writeln('  @override')
    ..writeln("  String get routeId => '$routeId';")
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Map<String, String> get params => ${_paramsMap(page.fields)};')
    ..writeln('}');
}

String _constructorParams(List<PageField> fields) {
  if (fields.isEmpty) {
    return '';
  }

  final params = fields.map((field) {
    final required = field.isRequired ? 'required ' : '';
    return '${required}this.${field.name}';
  }).join(', ');

  return '{$params}';
}

String _paramsMap(List<PageField> fields) {
  if (fields.isEmpty) {
    return '{}';
  }

  final buffer = StringBuffer()..writeln('{');

  for (final field in fields) {
    if (field.isNullable) {
      buffer.writeln(
        "    ...?${field.name} != null ? {'${field.name}': ${_toStringExpr(field, nonNull: true)}} : null,",
      );
    } else {
      buffer.writeln(
        "    '${field.name}': ${_toStringExpr(field, nonNull: false)},",
      );
    }
  }

  buffer.write('  }');
  return buffer.toString();
}

String _toStringExpr(PageField field, {required bool nonNull}) {
  final value = nonNull ? '${field.name}!' : field.name;
  return field.dartType == 'String' ? value : '$value.toString()';
}
