import 'package:leancode_add2app_gen/src/models/page_definition.dart';
import 'package:leancode_add2app_gen/src/utils/naming.dart';

/// Generates Dart extensions on pigeon-generated native_page classes that
/// add `.toPageSettings()` using pigeon's own `encode()`.
///
/// Example output:
/// ```dart
/// extension NativeEditProfilePageToPageSettings on NativeEditProfilePage {
///   static const String routeId = 'nativeEditProfile';
///
///   PageSettings toPageSettings() {
///     return PageSettings(routeId: routeId, params: encode());
///   }
/// }
/// ```
String generateDartNativePages({
  required List<PageDefinition> nativePages,
  required String pigeonDartImport,
}) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE — DO NOT MODIFY BY HAND')
    ..writeln('// Generated by leancode_add2app_gen')
    ..writeln()
    ..writeln(
      "import 'package:leancode_add2app/leancode_add2app.dart' "
      'show PageSettings;',
    )
    ..writeln("import '$pigeonDartImport';")
    ..writeln();

  for (final page in nativePages) {
    _writeExtension(buffer, page);
    buffer.writeln();
  }

  return buffer.toString();
}

void _writeExtension(StringBuffer buffer, PageDefinition page) {
  final routeId = routeIdFromClassName(page.className);

  buffer
    ..writeln(
      'extension ${page.className}ToPageSettings on ${page.className} {',
    )
    ..writeln("  static const String routeId = '$routeId';")
    ..writeln()
    ..writeln('  PageSettings toPageSettings() {')
    ..writeln("    return PageSettings(routeId: '$routeId', params: encode());")
    ..writeln('  }')
    ..writeln('}');
}
