import 'package:leancode_add2app_gen/src/models/page_definition.dart';
import 'package:leancode_add2app_gen/src/utils/naming.dart';

/// Generates a Kotlin file with an abstract `NativeRouteHandler` that
/// dispatches `PageSettings` to typed `on*` methods using pigeon-generated
/// classes directly (via `fromList()`).
///
/// Example output:
/// ```kotlin
/// abstract class NativeRouteHandler {
///     fun handle(context: Context, route: PageSettings) {
///         when (route.routeId) {
///             "nativeEditProfile" -> onNativeEditProfile(
///                 NativeEditProfilePage.fromList(route.params as List<Any?>), context,
///             )
///         }
///     }
///     abstract fun onNativeEditProfile(page: NativeEditProfilePage, context: Context)
/// }
/// ```
String generateKotlinNativeRouteHandler({
  required List<PageDefinition> nativePages,
  required String kotlinPackage,
}) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE — DO NOT MODIFY BY HAND')
    ..writeln('// Generated by leancode_add2app_gen')
    ..writeln()
    ..writeln('package $kotlinPackage')
    ..writeln()
    ..writeln('import android.content.Context')
    ..writeln('import co.leancode.add2app.navigator.PageSettings')
    ..writeln();

  _writeHandlerClass(buffer, nativePages);

  return buffer.toString();
}

void _writeHandlerClass(
  StringBuffer buffer,
  List<PageDefinition> nativePages,
) {
  buffer
    ..writeln('/**')
    ..writeln(
      ' * Abstract handler for native routes dispatched from Flutter.',
    )
    ..writeln(' *')
    ..writeln(
      ' * Extend this class and implement each `on*` method to handle',
    )
    ..writeln(
      ' * native route requests. The base class decodes [PageSettings]',
    )
    ..writeln(
      ' * into pigeon-generated page objects automatically via `fromList()`.',
    )
    ..writeln(' */')
    ..writeln(
      'abstract class NativeRouteHandler : co.leancode.add2app.NativeRouteHandler {',
    )
    ..writeln()
    ..writeln('    /**')
    ..writeln(
      '     * Dispatches a [PageSettings] to the correct typed handler.',
    )
    ..writeln('     * Called by the framework — do NOT call this directly.')
    ..writeln('     */')
    ..writeln(
      '    override fun handle(context: Context, route: PageSettings) {',
    )
    ..writeln('        when (route.routeId) {');

  for (final page in nativePages) {
    final routeId = routeIdFromClassName(page.className);
    final methodName = methodNameFromClassName(page.className);
    buffer
      ..writeln('            "$routeId" -> $methodName(')
      ..writeln(
        '                ${page.className}.fromList(route.params as List<Any?>),',
      )
      ..writeln('                context,')
      ..writeln('            )');
  }

  buffer
    ..writeln('            else -> onUnknownRoute(route, context)')
    ..writeln('        }')
    ..writeln('    }')
    ..writeln();

  // Abstract method for each native page — uses the pigeon-generated class.
  for (final page in nativePages) {
    final methodName = methodNameFromClassName(page.className);
    buffer.writeln(
      '    abstract fun $methodName(page: ${page.className}, context: Context)',
    );
  }

  buffer
    ..writeln()
    ..writeln('    /**')
    ..writeln('     * Called when no handler matches the route ID.')
    ..writeln('     * Override to customize error handling.')
    ..writeln('     */')
    ..writeln(
      '    open fun onUnknownRoute(route: PageSettings, context: Context) {',
    )
    ..writeln('        throw IllegalArgumentException(')
    ..writeln(
      '            '
      r'"No handler for native route ' "'" r'${route.routeId}' "'" '."',
    )
    ..writeln('        )')
    ..writeln('    }')
    ..writeln('}');
}
