import 'package:leancode_add2app_gen/src/models/page_definition.dart';
import 'package:leancode_add2app_gen/src/utils/naming.dart';

/// Generates a Swift file with a `NativeRouteHandler` base class that
/// dispatches `PageSettings` to typed `on*` methods using pigeon-generated
/// structs directly (via `fromList()`).
///
/// The generated class conforms to the framework's `NativeRouteHandling`
/// protocol. Developers subclass it and override the `on*` methods.
///
/// Example output:
/// ```swift
/// class NativeRouteHandler: NativeRouteHandling {
///     func handle(viewController: UIViewController, route: PageSettings) {
///         switch route.routeId {
///         case "nativeEditProfile":
///             onNativeEditProfile(
///                 page: NativeEditProfilePage.fromList(route.params as! [Any?])!,
///                 viewController: viewController
///             )
///         default:
///             onUnknownRoute(route: route, viewController: viewController)
///         }
///     }
///     func onNativeEditProfile(page: NativeEditProfilePage, viewController: UIViewController) {
///         fatalError("Must override")
///     }
/// }
/// ```
String generateSwiftNativeRouteHandler({
  required List<PageDefinition> nativePages,
}) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE — DO NOT MODIFY BY HAND')
    ..writeln('// Generated by leancode_add2app_gen')
    ..writeln()
    ..writeln('import Foundation')
    ..writeln('import UIKit')
    ..writeln();

  _writeHandlerClass(buffer, nativePages);

  return buffer.toString();
}

void _writeHandlerClass(
  StringBuffer buffer,
  List<PageDefinition> nativePages,
) {
  buffer
    ..writeln('/// Abstract handler for native routes dispatched from Flutter.')
    ..writeln('///')
    ..writeln(
      '/// Subclass this and override each `on*` method to handle',
    )
    ..writeln(
      '/// native route requests. The base class decodes `PageSettings`',
    )
    ..writeln(
      '/// into pigeon-generated page structs automatically via `fromList()`.',
    )
    ..writeln('class NativeRouteHandler: NativeRouteHandling {')
    ..writeln()
    ..writeln('    /// Dispatches a `PageSettings` to the correct typed handler.')
    ..writeln('    /// Called by the framework — do NOT call this directly.')
    ..writeln(
      '    func handle(viewController: UIViewController, route: PageSettings) {',
    )
    ..writeln('        switch route.routeId {');

  for (final page in nativePages) {
    final routeId = routeIdFromClassName(page.className);
    final methodName = methodNameFromClassName(page.className);
    buffer
      ..writeln('        case "$routeId":')
      ..writeln('            $methodName(')
      ..writeln(
        '                page: ${page.className}.fromList(route.params as! [Any?])!,',
      )
      ..writeln('                viewController: viewController')
      ..writeln('            )');
  }

  buffer
    ..writeln('        default:')
    ..writeln(
      '            onUnknownRoute(route: route, viewController: viewController)',
    )
    ..writeln('        }')
    ..writeln('    }')
    ..writeln();

  // Open method for each native page — subclasses must override.
  for (final page in nativePages) {
    final methodName = methodNameFromClassName(page.className);
    buffer
      ..writeln(
        '    /// Override to handle the `${page.className}` route.',
      )
      ..writeln(
        '    func $methodName(page: ${page.className}, viewController: UIViewController) {',
      )
      ..writeln(
        '        fatalError("$methodName(page:viewController:) must be overridden")',
      )
      ..writeln('    }')
      ..writeln();
  }

  buffer
    ..writeln('    /// Called when no handler matches the route ID.')
    ..writeln('    /// Override to customize error handling.')
    ..writeln(
      '    func onUnknownRoute(route: PageSettings, viewController: UIViewController) {',
    )
    ..writeln(
      r'        fatalError("No handler for native route ' "'" r'\(route.routeId)' "'" r'.")',
    )
    ..writeln('    }')
    ..writeln('}');
}
