import 'package:leancode_add2app_gen/src/models/schema.dart';
import 'package:leancode_add2app_gen/src/models/store_definition.dart';
import 'package:leancode_add2app_gen/src/models/type_info.dart';
import 'package:leancode_add2app_gen/src/parser/type_resolver.dart';

/// Generates Dart code for stores from a resolved schema.
///
/// Produces:
/// - Store classes with typed getters/setters
/// - Snapshot classes for reactive reading
/// - Stream support for change notifications
String generateDartStores({
  required Schema schema,
  required Map<String, TypeDefinition> typeGraph,
}) {
  final needsRoutesImport = _storesRequireRoutesImport(schema, typeGraph);
  final buffer = StringBuffer()
    // Header.
    ..writeln('// GENERATED CODE — DO NOT MODIFY BY HAND')
    ..writeln('// Generated by leancode_add2app_gen')
    ..writeln()
    ..writeln("import 'dart:async';")
    ..writeln()
    ..writeln("import 'package:leancode_add2app/leancode_add2app.dart';")
    ..writeln();

  if (needsRoutesImport) {
    buffer
      ..writeln("import 'routes.g.dart';")
      ..writeln();
  }

  // Generate store classes.
  for (final store in schema.stores) {
    _writeStoreClass(buffer, store, typeGraph);
    buffer.writeln();
    _writeSnapshotClass(buffer, store);
    buffer.writeln();
  }

  final output = buffer.toString();
  return output.endsWith('\n') ? output : '$output\n';
}

bool _storesRequireRoutesImport(
  Schema schema,
  Map<String, TypeDefinition> typeGraph,
) {
  for (final store in schema.stores) {
    for (final field in store.allFields) {
      if (typeGraph[field.type.baseName] is EnumType) {
        return true;
      }
    }
  }
  return false;
}

void _writeStoreClass(
  StringBuffer buffer,
  StoreDefinition store,
  Map<String, TypeDefinition> typeGraph,
) {
  final className = store.className;
  final storeKey = store.storeKey;
  final keyField = store.keyField;
  final valueFields = store.valueFields;

  final snapshotClassName = '${className}Snapshot';

  buffer
    ..writeln('/// Generated store wrapper for $className.')
    ..writeln('class $className implements Add2AppSnapshotStore<$snapshotClassName> {')
    // Constructor.
    ..write('  $className(this._storage');
  if (keyField != null) {
    buffer
      ..write(', {')
      ..write('required this.${keyField.name}, ')
      ..write('}');
  }
  buffer
    ..writeln(');')
    ..writeln()
    // Storage field.
    ..writeln('  final KeyValueStorage _storage;');

  // Store key field.
  if (keyField != null) {
    buffer.writeln('  final ${keyField.type.toSource()} ${keyField.name};');
  }
  buffer.writeln();

  // Key helper.
  if (keyField == null) {
    buffer.writeln("  String _key(String field) => '$storeKey/\$field';");
  } else {
    final keySegment = _keySegmentExpression(keyField, typeGraph);
    buffer.writeln("  String _key(String field) => '$storeKey/$keySegment/\$field';");
  }

  buffer
    ..writeln()
    // Getters for each value field.
    ..writeln('  // ── Getters (async, always fresh) ─────────────────────────────')
    ..writeln();

  for (final field in valueFields) {
    _writeGetter(buffer, field, typeGraph);
    buffer.writeln();
  }

  // Setters for each value field.
  buffer
    ..writeln('  // ── Setters ───────────────────────────────────────────────────')
    ..writeln();

  for (final field in valueFields) {
    _writeSetter(buffer, field, typeGraph);
    buffer.writeln();
  }

  // Stream for reactive updates.
  buffer
    ..writeln('  // ── Reactive Stream ───────────────────────────────────────────')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Stream<$snapshotClassName> get stream {')
    ..writeln('    return _storage.stream')
    ..writeln("        .where((entries) => entries.any((e) => e.key.startsWith(_key(''))))")
    ..writeln('        .asyncMap((_) => getSnapshot());')
    ..writeln('  }')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Future<$snapshotClassName> getSnapshot() async {')
    ..writeln('    return $snapshotClassName(');
  for (final field in valueFields) {
    final getterName = _getterNameForField(field);
    buffer.writeln('      ${field.name}: await $getterName(),');
  }

  buffer
    ..writeln('    );')
    ..writeln('  }')
    ..writeln();

  // writeSnapshot() — diff-based batch write using putAll.
  _writeWriteSnapshot(buffer, snapshotClassName, valueFields, typeGraph);

  buffer
    ..writeln()
    // clear() method.
    ..writeln('  // ── Clear ─────────────────────────────────────────────────────')
    ..writeln()
    ..writeln('  Future<void> clear() async {')
    ..writeln("    await _storage.removeByPrefix(_key(''));")
    ..writeln('  }')
    ..writeln('}');
}

void _writeSnapshotClass(StringBuffer buffer, StoreDefinition store) {
  final className = '${store.className}Snapshot';
  final valueFields = store.valueFields;

  buffer
    ..writeln('/// Immutable snapshot of ${store.className} values.')
    ..writeln('class $className {')
    // Constructor.
    ..write('  const $className(');
  if (valueFields.isNotEmpty) {
    buffer.writeln('{');
    for (final field in valueFields) {
      buffer.writeln('    required this.${field.name},');
    }
    buffer.write('  }');
  }
  buffer
    ..writeln(');')
    ..writeln();

  // Fields.
  for (final field in valueFields) {
    final type = _nonNullableType(field);
    buffer.writeln('  final $type ${field.name};');
  }

  // copyWith method.
  _writeCopyWith(buffer, store);

  buffer.writeln('}');
}

void _writeGetter(
  StringBuffer buffer,
  FieldInfo field,
  Map<String, TypeDefinition> typeGraph,
) {
  final getterName = _getterNameForField(field);
  final returnType = _nonNullableType(field);
  final baseName = field.type.baseName;

  buffer
    ..writeln('  Future<$returnType> $getterName() async {')
    ..writeln("    final value = await _storage.getString(_key('${field.name}'));");

  if (typeGraph[baseName] case final EnumType enumType) {
    final defaultVal = field.defaultValue ?? '$baseName.${enumType.values.first}';
    buffer
      ..writeln(
        '    return value != null ? $baseName.values[int.parse(value)] : $defaultVal;',
      )
      ..writeln('  }');
    return;
  }

  switch (baseName) {
    case 'bool':
      final defaultVal = field.defaultValue ?? 'false';
      if (defaultVal == 'true') {
        buffer.writeln("    return value != 'false';");
      } else {
        buffer.writeln("    return value == 'true';");
      }
    case 'int':
      final defaultVal = field.defaultValue ?? '0';
      buffer.writeln('    return value != null ? int.parse(value) : $defaultVal;');
    case 'double':
      final defaultVal = field.defaultValue ?? '0.0';
      buffer.writeln('    return value != null ? double.parse(value) : $defaultVal;');
    case 'String':
      final defaultVal = field.defaultValue ?? "''";
      buffer.writeln('    return value ?? $defaultVal;');
    default:
      // Shouldn't happen if type validation worked.
      buffer.writeln("    return value ?? '';");
  }

  buffer.writeln('  }');
}

void _writeSetter(
  StringBuffer buffer,
  FieldInfo field,
  Map<String, TypeDefinition> typeGraph,
) {
  final setterName = _setterNameForField(field);
  final paramType = _nonNullableType(field);
  final baseName = field.type.baseName;

  buffer.writeln('  Future<void> $setterName($paramType value) async {');

  if (typeGraph[baseName] is EnumType) {
    buffer
      ..writeln(
        "    await _storage.putString(_key('${field.name}'), value.index.toString());",
      )
      ..writeln('  }');
    return;
  }

  switch (baseName) {
    case 'String':
      buffer.writeln("    await _storage.putString(_key('${field.name}'), value);");
    default:
      buffer.writeln("    await _storage.putString(_key('${field.name}'), value.toString());");
  }

  buffer.writeln('  }');
}

String _keySegmentExpression(
  FieldInfo keyField,
  Map<String, TypeDefinition> typeGraph,
) {
  if (typeGraph[keyField.type.baseName] is EnumType) {
    return '\${${keyField.name}.name}';
  }
  return '\$${keyField.name}';
}

String _getterNameForField(FieldInfo field) {
  final name = field.name;
  return 'get${name[0].toUpperCase()}${name.substring(1)}';
}

String _setterNameForField(FieldInfo field) {
  final name = field.name;
  return 'set${name[0].toUpperCase()}${name.substring(1)}';
}

void _writeWriteSnapshot(
  StringBuffer buffer,
  String snapshotClassName,
  List<FieldInfo> valueFields,
  Map<String, TypeDefinition> typeGraph,
) {
  buffer
    ..writeln('  // ── Write Snapshot ────────────────────────────────────────────')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Future<void> writeSnapshot(')
    ..writeln('    $snapshotClassName snapshot, {')
    ..writeln('    $snapshotClassName? previous,')
    ..writeln('  }) async {')
    ..writeln('    final entries = <StorageEntry>[];');

  for (final field in valueFields) {
    final name = field.name;
    final baseName = field.type.baseName;

    buffer.writeln(
      '    if (previous == null || previous.$name != snapshot.$name) {',
    );

    final valueExpr = switch (typeGraph[baseName]) {
      EnumType() => 'snapshot.$name.index.toString()',
      _ when baseName == 'String' => 'snapshot.$name',
      _ => 'snapshot.$name.toString()',
    };

    buffer
      ..writeln(
        "      entries.add(StorageEntry(key: _key('$name'), value: $valueExpr));",
      )
      ..writeln('    }');
  }

  buffer
    ..writeln('    if (entries.isNotEmpty) {')
    ..writeln('      await _storage.putAll(entries);')
    ..writeln('    }')
    ..writeln('  }');
}

void _writeCopyWith(StringBuffer buffer, StoreDefinition store) {
  final className = '${store.className}Snapshot';
  final valueFields = store.valueFields;

  if (valueFields.isEmpty) {
    return;
  }

  buffer
    ..writeln()
    ..writeln('  $className copyWith({');
  for (final field in valueFields) {
    final type = _nonNullableType(field);
    buffer.writeln('    $type? ${field.name},');
  }
  buffer
    ..writeln('  }) {')
    ..writeln('    return $className(');
  for (final field in valueFields) {
    buffer.writeln('      ${field.name}: ${field.name} ?? this.${field.name},');
  }
  buffer
    ..writeln('    );')
    ..writeln('  }');
}

/// Returns the non-nullable version of the field's type.
/// For stores, all values are stored as strings and decoded, so we use non-nullable.
String _nonNullableType(FieldInfo field) {
  return field.type.baseName;
}
