import 'package:leancode_add2app_gen/src/models/schema.dart';
import 'package:leancode_add2app_gen/src/models/store_definition.dart';
import 'package:leancode_add2app_gen/src/models/type_info.dart';

/// Generates Dart code for stores from a resolved schema.
///
/// Produces:
/// - Store classes with typed getters/setters
/// - Snapshot classes for reactive reading
/// - Stream support for change notifications
String generateDartStores({required Schema schema}) {
  final buffer = StringBuffer()
    // Header.
    ..writeln('// GENERATED CODE — DO NOT MODIFY BY HAND')
    ..writeln('// Generated by leancode_add2app_gen')
    ..writeln()
    ..writeln("import 'dart:async';")
    ..writeln()
    ..writeln("import 'package:leancode_add2app/leancode_add2app.dart';")
    ..writeln();

  // Generate store classes.
  for (final store in schema.stores) {
    _writeStoreClass(buffer, store);
    buffer.writeln();
    _writeSnapshotClass(buffer, store);
    buffer.writeln();
  }

  final output = buffer.toString();
  return output.endsWith('\n') ? output : '$output\n';
}

void _writeStoreClass(StringBuffer buffer, StoreDefinition store) {
  final className = store.className;
  final storeKey = store.storeKey;
  final scopeFields = store.scopeFields;
  final valueFields = store.valueFields;

  buffer
    ..writeln('/// Generated store wrapper for $className.')
    ..writeln('class $className {')
    // Constructor.
    ..write('  $className(this._storage');
  if (scopeFields.isNotEmpty) {
    buffer.write(', {');
    for (final field in scopeFields) {
      buffer.write('required this.${field.name}, ');
    }
    buffer.write('}');
  }
  buffer
    ..writeln(');')
    ..writeln()
    // Storage field.
    ..writeln('  final KeyValueStorage _storage;');

  // Scope fields.
  for (final field in scopeFields) {
    buffer.writeln('  final ${field.type.toSource()} ${field.name};');
  }
  buffer.writeln();

  // Key helper.
  if (scopeFields.isEmpty) {
    buffer.writeln("  String _key(String field) => '$storeKey/\$field';");
  } else {
    final scopeParts = scopeFields.map((f) => '\$${f.name}').join('/');
    buffer.writeln("  String _key(String field) => '$storeKey/$scopeParts/\$field';");
  }

  buffer
    ..writeln()
    // Getters for each value field.
    ..writeln('  // ── Getters (async, always fresh) ─────────────────────────────')
    ..writeln();

  for (final field in valueFields) {
    _writeGetter(buffer, field);
    buffer.writeln();
  }

  // Setters for each value field.
  buffer
    ..writeln('  // ── Setters ───────────────────────────────────────────────────')
    ..writeln();

  for (final field in valueFields) {
    _writeSetter(buffer, field);
    buffer.writeln();
  }

  // Stream for reactive updates.
  buffer
    ..writeln('  // ── Reactive Stream ───────────────────────────────────────────')
    ..writeln();

  final snapshotClassName = '${className}Snapshot';
  buffer
    ..writeln('  Stream<$snapshotClassName> get stream {')
    ..writeln('    return _storage.stream')
    ..writeln("        .where((entries) => entries.any((e) => e.key.startsWith(_key(''))))")
    ..writeln('        .asyncMap((_) => getSnapshot());')
    ..writeln('  }')
    ..writeln()
    // getSnapshot() method.
    ..writeln('  Future<$snapshotClassName> getSnapshot() async {')
    ..writeln('    return $snapshotClassName(');
  for (final field in valueFields) {
    final getterName = _getterNameForField(field);
    buffer.writeln('      ${field.name}: await $getterName(),');
  }

  buffer
    ..writeln('    );')
    ..writeln('  }')
    ..writeln()
    // clear() method.
    ..writeln('  // ── Clear ─────────────────────────────────────────────────────')
    ..writeln()
    ..writeln('  Future<void> clear() async {')
    ..writeln("    await _storage.removeByPrefix(_key(''));")
    ..writeln('  }')
    ..writeln('}');
}

void _writeSnapshotClass(StringBuffer buffer, StoreDefinition store) {
  final className = '${store.className}Snapshot';
  final valueFields = store.valueFields;

  buffer
    ..writeln('/// Immutable snapshot of ${store.className} values.')
    ..writeln('class $className {')
    // Constructor.
    ..write('  const $className(');
  if (valueFields.isNotEmpty) {
    buffer.writeln('{');
    for (final field in valueFields) {
      buffer.writeln('    required this.${field.name},');
    }
    buffer.write('  }');
  }
  buffer
    ..writeln(');')
    ..writeln();

  // Fields.
  for (final field in valueFields) {
    final type = _nonNullableType(field);
    buffer.writeln('  final $type ${field.name};');
  }

  buffer.writeln('}');
}

void _writeGetter(StringBuffer buffer, FieldInfo field) {
  final getterName = _getterNameForField(field);
  final returnType = _nonNullableType(field);
  final baseName = field.type.baseName;

  buffer
    ..writeln('  Future<$returnType> $getterName() async {')
    ..writeln("    final value = await _storage.getString(_key('${field.name}'));");

  switch (baseName) {
    case 'bool':
      final defaultVal = field.defaultValue ?? 'false';
      if (defaultVal == 'true') {
        buffer.writeln("    return value != 'false';");
      } else {
        buffer.writeln("    return value == 'true';");
      }
    case 'int':
      final defaultVal = field.defaultValue ?? '0';
      buffer.writeln('    return value != null ? int.parse(value) : $defaultVal;');
    case 'double':
      final defaultVal = field.defaultValue ?? '0.0';
      buffer.writeln('    return value != null ? double.parse(value) : $defaultVal;');
    case 'String':
      final defaultVal = field.defaultValue ?? "''";
      buffer.writeln('    return value ?? $defaultVal;');
    default:
      // Shouldn't happen if type validation worked.
      buffer.writeln("    return value ?? '';");
  }

  buffer.writeln('  }');
}

void _writeSetter(StringBuffer buffer, FieldInfo field) {
  final setterName = _setterNameForField(field);
  final paramType = _nonNullableType(field);
  final baseName = field.type.baseName;

  buffer.writeln('  Future<void> $setterName($paramType value) async {');

  switch (baseName) {
    case 'String':
      buffer.writeln("    await _storage.putString(_key('${field.name}'), value);");
    default:
      buffer.writeln("    await _storage.putString(_key('${field.name}'), value.toString());");
  }

  buffer.writeln('  }');
}

String _getterNameForField(FieldInfo field) {
  final name = field.name;
  return 'get${name[0].toUpperCase()}${name.substring(1)}';
}

String _setterNameForField(FieldInfo field) {
  final name = field.name;
  return 'set${name[0].toUpperCase()}${name.substring(1)}';
}

/// Returns the non-nullable version of the field's type.
/// For stores, all values are stored as strings and decoded, so we use non-nullable.
String _nonNullableType(FieldInfo field) {
  return field.type.baseName;
}
