import 'package:leancode_add2app_gen/src/generators/dart/dart_serialization.dart';
import 'package:leancode_add2app_gen/src/models/data_type_definition.dart';
import 'package:leancode_add2app_gen/src/models/route_definition.dart';
import 'package:leancode_add2app_gen/src/models/schema.dart';
import 'package:leancode_add2app_gen/src/models/type_info.dart';
import 'package:leancode_add2app_gen/src/parser/type_resolver.dart';
import 'package:leancode_add2app_gen/src/utils/naming.dart';

/// Generates Dart code for routes from a resolved schema.
///
/// Produces:
/// - Flutter route classes extending `FlutterRouteBase`
/// - Native route classes with `toNativeRoute()` method
/// - Data classes with serialization
/// - Enum definitions
/// - FlutterRouteHandler base class
String generateDartRoutes({
  required Schema schema,
  required Map<String, TypeDefinition> typeGraph,
}) {
  final buffer = StringBuffer()
    // Header.
    ..writeln('// GENERATED CODE — DO NOT MODIFY BY HAND')
    ..writeln('// Generated by leancode_add2app_gen')
    ..writeln()
    ..writeln("import 'package:flutter/widgets.dart';")
    ..writeln("import 'package:leancode_add2app/leancode_add2app.dart';")
    ..writeln();

  // Generate enums first (they might be referenced by other types).
  for (final enumDef in schema.enums) {
    _writeEnum(buffer, enumDef);
    buffer.writeln();
  }

  // Generate data classes (shared types).
  for (final dataClass in schema.dataClasses) {
    _writeDataClass(buffer, dataClass, typeGraph);
    buffer.writeln();
  }

  // Generate Flutter route classes.
  for (final route in schema.flutterRoutes) {
    _writeFlutterRoute(buffer, route, typeGraph);
    buffer.writeln();
  }

  // Generate native route classes.
  for (final route in schema.nativeRoutes) {
    _writeNativeRoute(buffer, route, typeGraph);
    buffer.writeln();
  }

  // Generate FlutterRouteHandler if there are Flutter routes.
  if (schema.flutterRoutes.isNotEmpty) {
    _writeFlutterRouteHandler(buffer, schema.flutterRoutes);
    buffer.writeln();
    _writeDecodeFlutterRouteData(buffer, schema.flutterRoutes);
  }

  final output = buffer.toString();
  return output.endsWith('\n') ? output : '$output\n';
}

void _writeEnum(StringBuffer buffer, EnumDefinition enumDef) {
  buffer.writeln('enum ${enumDef.name} {');
  for (final value in enumDef.values) {
    buffer.writeln('  $value,');
  }
  buffer.writeln('}');
}

void _writeDataClass(
  StringBuffer buffer,
  DataClassDefinition dataClass,
  Map<String, TypeDefinition> typeGraph,
) {
  final className = dataClass.className;
  final fields = dataClass.fields;

  buffer
    // Class declaration.
    ..writeln('class $className {')
    // Constructor.
    ..write('  const $className(');
  if (fields.isNotEmpty) {
    buffer.writeln('{');
    for (final field in fields) {
      final required = field.isRequired ? 'required ' : '';
      buffer.writeln('    ${required}this.${field.name},');
    }
    buffer.write('  }');
  }
  buffer
    ..writeln(');')
    ..writeln();

  // Fields.
  for (final field in fields) {
    buffer.writeln('  final ${field.type.toSource()} ${field.name};');
  }

  if (fields.isNotEmpty) {
    buffer.writeln();
  }

  buffer
    // encode() method.
    ..writeln('  ${generateDartEncodeMethod(fields, typeGraph)};')
    ..writeln()
    // decode() static method.
    ..writeln('  ${generateDartDecodeMethod(className, fields, typeGraph)}')
    ..writeln('}');
}

void _writeFlutterRoute(
  StringBuffer buffer,
  RouteDefinition route,
  Map<String, TypeDefinition> typeGraph,
) {
  final className = route.className;
  final fields = route.fields;
  final routeName = route.routeName;
  final path = route.path;

  buffer
    // Class declaration.
    ..writeln('class $className extends FlutterRouteBase {')
    // Constructor.
    ..write('  const $className(');
  if (fields.isNotEmpty) {
    buffer.writeln('{');
    for (final field in fields) {
      final required = field.isRequired ? 'required ' : '';
      buffer.writeln('    ${required}this.${field.name},');
    }
    buffer.write('  }');
  }
  buffer
    ..writeln(');')
    ..writeln();

  // Fields.
  for (final field in fields) {
    buffer.writeln('  final ${field.type.toSource()} ${field.name};');
  }

  if (fields.isNotEmpty) {
    buffer.writeln();
  }

  buffer.writeln("  static const String routeName = '$routeName';");

  // Path support.
  if (path != null) {
    final pathParamNames = extractPathParamNames(path);
    final queryFields = fields.where(
      (f) =>
          !pathParamNames.contains(f.name) && isSimpleType(f.type, typeGraph),
    );

    buffer
      ..writeln()
      ..writeln("  static const String pathTemplate = '$path';")
      ..writeln()
      ..writeln('  String toPath() {');

    // Build path string with substituted params.
    var pathExpr = path;
    for (final paramName in pathParamNames) {
      final field = fields.where((f) => f.name == paramName).firstOrNull;
      final isNullable = field?.type.isNullable ?? false;
      final encode = isNullable
          ? "\${Uri.encodeComponent($paramName ?? '')}"
          : '\${Uri.encodeComponent($paramName)}';
      pathExpr = pathExpr.replaceAll(':$paramName', encode);
    }
    buffer.writeln("    final basePath = '$pathExpr';");

    if (queryFields.isEmpty) {
      buffer.writeln('    return basePath;');
    } else {
      buffer.writeln('    final query = <String, String>{};');
      for (final field in queryFields) {
        final valueExpr = _dartFieldToQueryValue(field);
        if (field.type.isNullable) {
          buffer.writeln(
            "    if (${field.name} != null) query['${field.name}'] = $valueExpr;",
          );
        } else {
          buffer.writeln("    query['${field.name}'] = $valueExpr;");
        }
      }
      buffer
        ..writeln('    if (query.isEmpty) return basePath;')
        ..writeln(
          r"    return '$basePath?${query.entries.map((e) => '${e.key}=${Uri.encodeComponent(e.value)}').join('&')}';",
        );
    }
    buffer.writeln('  }');
  }

  buffer
    ..writeln()
    // encode() method.
    ..writeln('  ${generateDartEncodeMethod(fields, typeGraph)};')
    ..writeln()
    // decode() static method (from List).
    ..writeln('  ${generateDartDecodeMethod(className, fields, typeGraph)}')
    ..writeln()
    // decodeFromMap() static method (from Map, used by iOS URL encoding).
    ..writeln('  ${_generateDecodeFromMapMethod(className, fields, typeGraph)}')
    ..writeln()
    // FlutterRouteBase overrides.
    ..writeln('  @override')
    ..writeln('  String get routeId => routeName;')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Object? get params => encode();');

  // Override toPageSettings to include path.
  if (path != null) {
    buffer
      ..writeln()
      ..writeln('  @override')
      ..writeln('  PageSettings toPageSettings() {')
      ..writeln(
        '    return PageSettings(routeId: routeId, params: params, path: toPath());',
      )
      ..writeln('  }');
  }

  buffer.writeln('}');
}

/// Extracts path parameter names from a path template.
/// E.g. '/products/:id/reviews/:reviewId' -> ['id', 'reviewId']
List<String> extractPathParamNames(String path) {
  final regex = RegExp(r':(\w+)');
  return regex.allMatches(path).map((m) => m.group(1)!).toList();
}

/// Whether a type is simple enough to be encoded as a query parameter.
///
/// Simple types are primitives and enums. Data classes and collections
/// are considered complex and should NOT be serialized into query params.
/// When [typeGraph] is provided, we check whether the type is actually an
/// enum. Without it we fall back to a heuristic (non-primitive, non-collection,
/// no type args → assumed enum).
bool isSimpleType(TypeInfo type, [Map<String, TypeDefinition>? typeGraph]) {
  if (type.isPrimitive) {
    return true;
  }
  if (type.isList || type.isMap) {
    return false;
  }
  if (type.typeArguments.isNotEmpty) {
    return false;
  }

  if (typeGraph != null) {
    final def = typeGraph[type.name];
    return def is EnumType;
  }

  return true;
}

/// Returns a Dart expression that converts a field value to a String for query params.
String _dartFieldToQueryValue(FieldInfo field) {
  final name = field.name;
  final type = field.type;
  final nullSuffix = type.isNullable ? '!' : '';

  if (type.name == 'String') {
    return '$name$nullSuffix';
  }
  if (type.name == 'int' || type.name == 'double' || type.name == 'num') {
    return '$name$nullSuffix.toString()';
  }
  if (type.name == 'bool') {
    return '$name$nullSuffix.toString()';
  }
  return '$name$nullSuffix.index.toString()';
}

String _generateDecodeFromMapMethod(
  String className,
  List<FieldInfo> fields,
  Map<String, TypeDefinition> typeGraph,
) {
  final buffer = StringBuffer()
    ..writeln('static $className decodeFromMap(Map<Object?, Object?> map) {')
    ..write('    return $className(');

  if (fields.isEmpty) {
    buffer.writeln(');');
  } else {
    buffer.writeln();
    for (final field in fields) {
      final fieldName = field.name;
      final accessor = _mapAccessorForType(fieldName, field.type);
      buffer.writeln('      $fieldName: $accessor,');
    }
    buffer.writeln('    );');
  }

  buffer.write('  }');
  return buffer.toString();
}

String _mapAccessorForType(String fieldName, TypeInfo type) {
  final name = type.name;
  final isNullable = type.isNullable;

  // iOS URL encoding passes all values as Strings.
  if (name == 'String') {
    return isNullable
        ? "map['$fieldName'] as String?"
        : "map['$fieldName'] as String? ?? ''";
  }
  if (name == 'int') {
    return isNullable
        ? "map['$fieldName'] != null ? int.tryParse(map['$fieldName'] as String? ?? '') : null"
        : "int.tryParse(map['$fieldName'] as String? ?? '') ?? 0";
  }
  if (name == 'double') {
    return isNullable
        ? "map['$fieldName'] != null ? double.tryParse(map['$fieldName'] as String? ?? '') : null"
        : "double.tryParse(map['$fieldName'] as String? ?? '') ?? 0.0";
  }
  if (name == 'bool') {
    return isNullable
        ? "map['$fieldName'] != null ? map['$fieldName'] == 'true' : null"
        : "map['$fieldName'] == 'true'";
  }

  // For complex types, cast to the full declared Dart type.
  // URL maps only carry strings in real iOS deep-link cases, but this keeps
  // generated code type-correct for generic fields (e.g. List<Custom>?).
  final typeSource = type.toSource();
  return "map['$fieldName'] as $typeSource";
}

void _writeNativeRoute(
  StringBuffer buffer,
  RouteDefinition route,
  Map<String, TypeDefinition> typeGraph,
) {
  final className = route.className;
  final fields = route.fields;
  final routeName = route.routeName;

  buffer
    // Class declaration.
    ..writeln('class $className {')
    // Constructor.
    ..write('  const $className(');
  if (fields.isNotEmpty) {
    buffer.writeln('{');
    for (final field in fields) {
      final required = field.isRequired ? 'required ' : '';
      buffer.writeln('    ${required}this.${field.name},');
    }
    buffer.write('  }');
  }
  buffer
    ..writeln(');')
    ..writeln();

  // Fields.
  for (final field in fields) {
    buffer.writeln('  final ${field.type.toSource()} ${field.name};');
  }

  if (fields.isNotEmpty) {
    buffer.writeln();
  }

  buffer
    // Static route ID.
    ..writeln("  static const String routeId = '$routeName';")
    ..writeln()
    // encode() method.
    ..writeln('  ${generateDartEncodeMethod(fields, typeGraph)};')
    ..writeln()
    // decode() static method.
    ..writeln('  ${generateDartDecodeMethod(className, fields, typeGraph)}')
    ..writeln()
    // toNativeRoute() method.
    ..writeln('  NativeRouteWrapper toNativeRoute() => NativeRouteWrapper(')
    ..writeln('    PageSettings(routeId: routeId, params: encode()),')
    ..writeln('  );')
    ..writeln('}');
}

void _writeFlutterRouteHandler(
  StringBuffer buffer,
  List<RouteDefinition> routes,
) {
  buffer
    ..writeln('abstract class FlutterRouteHandler {')
    ..writeln('  const FlutterRouteHandler();')
    ..writeln()
    // handle() method.
    ..writeln('  Widget handle(PageSettings route) {')
    ..writeln('    final params = route.params;')
    ..writeln('    switch (route.routeId) {');

  for (final route in routes) {
    final methodName = methodNameFromClassName(route.className);
    buffer
      ..writeln("      case '${route.routeName}':")
      ..writeln('        return $methodName(')
      ..writeln('          params is List')
      ..writeln(
        '              ? ${route.className}.decode(params.cast<Object?>())',
      )
      ..writeln(
        '              : ${route.className}.decodeFromMap(params as Map<Object?, Object?>? ?? {}),',
      )
      ..writeln('        );');
  }

  buffer
    ..writeln('      default:')
    ..writeln('        return onUnknownRoute(route);')
    ..writeln('    }')
    ..writeln('  }')
    ..writeln();

  // Abstract methods for each route.
  for (final route in routes) {
    final methodName = methodNameFromClassName(route.className);
    buffer.writeln('  Widget $methodName(${route.className} page);');
  }

  buffer
    ..writeln()
    ..writeln('  Widget onUnknownRoute(PageSettings route) {')
    ..writeln(
      r"    return Center(child: Text('Unknown route: ${route.routeId}'));",
    )
    ..writeln('  }')
    ..writeln('}');
}

void _writeDecodeFlutterRouteData(
  StringBuffer buffer,
  List<RouteDefinition> routes,
) {
  buffer
    ..writeln(
      '/// Decodes [PageSettings] returned by the native host into a typed',
    )
    ..writeln('/// [FlutterRouteBase] subclass. Pass this to')
    ..writeln('/// [Add2AppNavigator.fetchInitialRoute] as the decoder.')
    ..writeln(
      'FlutterRouteBase? decodeFlutterRouteData(PageSettings? settings) {',
    )
    ..writeln('  if (settings == null) return null;')
    ..writeln('  final params = settings.params;')
    ..writeln('  if (params is! List) return null;')
    ..writeln('  switch (settings.routeId) {');

  for (final route in routes) {
    buffer
      ..writeln('    case ${route.className}.routeName:')
      ..writeln(
        '      return ${route.className}.decode(params.cast<Object?>());',
      );
  }

  buffer
    ..writeln('    default:')
    ..writeln('      return null;')
    ..writeln('  }')
    ..writeln('}');
}
