import 'package:leancode_add2app_gen/src/generators/dart/dart_serialization.dart';
import 'package:leancode_add2app_gen/src/models/data_type_definition.dart';
import 'package:leancode_add2app_gen/src/models/route_definition.dart';
import 'package:leancode_add2app_gen/src/models/schema.dart';
import 'package:leancode_add2app_gen/src/models/type_info.dart';
import 'package:leancode_add2app_gen/src/parser/type_resolver.dart';
import 'package:leancode_add2app_gen/src/utils/naming.dart';

/// Generates Dart code for routes from a resolved schema.
///
/// Produces:
/// - Flutter route classes extending `FlutterRouteBase`
/// - Native route classes with `toNativeRoute()` method
/// - Data classes with serialization
/// - Enum definitions
/// - FlutterRouteHandler base class
String generateDartRoutes({
  required Schema schema,
  required Map<String, TypeDefinition> typeGraph,
}) {
  final buffer = StringBuffer();

  // Header.
  buffer.writeln('// GENERATED CODE — DO NOT MODIFY BY HAND');
  buffer.writeln('// Generated by leancode_add2app_gen');
  buffer.writeln();
  buffer.writeln("import 'package:flutter/widgets.dart';");
  buffer.writeln("import 'package:leancode_add2app/leancode_add2app.dart';");
  buffer.writeln();

  // Generate enums first (they might be referenced by other types).
  for (final enumDef in schema.enums) {
    _writeEnum(buffer, enumDef);
    buffer.writeln();
  }

  // Generate data classes (shared types).
  for (final dataClass in schema.dataClasses) {
    _writeDataClass(buffer, dataClass, typeGraph);
    buffer.writeln();
  }

  // Generate Flutter route classes.
  for (final route in schema.flutterRoutes) {
    _writeFlutterRoute(buffer, route, typeGraph);
    buffer.writeln();
  }

  // Generate native route classes.
  for (final route in schema.nativeRoutes) {
    _writeNativeRoute(buffer, route, typeGraph);
    buffer.writeln();
  }

  // Generate FlutterRouteHandler if there are Flutter routes.
  if (schema.flutterRoutes.isNotEmpty) {
    _writeFlutterRouteHandler(buffer, schema.flutterRoutes);
  }

  final output = buffer.toString();
  return output.endsWith('\n') ? output : '$output\n';
}

void _writeEnum(StringBuffer buffer, EnumDefinition enumDef) {
  buffer.writeln('enum ${enumDef.name} {');
  for (final value in enumDef.values) {
    buffer.writeln('  $value,');
  }
  buffer.writeln('}');
}

void _writeDataClass(
  StringBuffer buffer,
  DataClassDefinition dataClass,
  Map<String, TypeDefinition> typeGraph,
) {
  final className = dataClass.className;
  final fields = dataClass.fields;

  // Class declaration.
  buffer.writeln('class $className {');

  // Constructor.
  buffer.write('  const $className(');
  if (fields.isNotEmpty) {
    buffer.writeln('{');
    for (final field in fields) {
      final required = field.isRequired ? 'required ' : '';
      buffer.writeln('    ${required}this.${field.name},');
    }
    buffer.write('  }');
  }
  buffer.writeln(');');
  buffer.writeln();

  // Fields.
  for (final field in fields) {
    buffer.writeln('  final ${field.type.toSource()} ${field.name};');
  }

  if (fields.isNotEmpty) {
    buffer.writeln();
  }

  // encode() method.
  buffer.writeln('  ${generateDartEncodeMethod(fields, typeGraph)};');
  buffer.writeln();

  // decode() static method.
  buffer.writeln('  ${generateDartDecodeMethod(className, fields, typeGraph)}');

  buffer.writeln('}');
}

void _writeFlutterRoute(
  StringBuffer buffer,
  RouteDefinition route,
  Map<String, TypeDefinition> typeGraph,
) {
  final className = route.className;
  final fields = route.fields;
  final routeName = route.routeName;

  // Class declaration.
  buffer.writeln('class $className extends FlutterRouteBase {');

  // Constructor.
  buffer.write('  const $className(');
  if (fields.isNotEmpty) {
    buffer.writeln('{');
    for (final field in fields) {
      final required = field.isRequired ? 'required ' : '';
      buffer.writeln('    ${required}this.${field.name},');
    }
    buffer.write('  }');
  }
  buffer.writeln(');');
  buffer.writeln();

  // Fields.
  for (final field in fields) {
    buffer.writeln('  final ${field.type.toSource()} ${field.name};');
  }

  if (fields.isNotEmpty) {
    buffer.writeln();
  }

  // Static route name.
  buffer.writeln("  static const String routeName = '$routeName';");
  buffer.writeln();

  // encode() method.
  buffer.writeln('  ${generateDartEncodeMethod(fields, typeGraph)};');
  buffer.writeln();

  // decode() static method (from List).
  buffer.writeln('  ${generateDartDecodeMethod(className, fields, typeGraph)}');
  buffer.writeln();

  // decodeFromMap() static method (from Map, used by iOS URL encoding).
  buffer.writeln(
    '  ${_generateDecodeFromMapMethod(className, fields, typeGraph)}',
  );
  buffer.writeln();

  // FlutterRouteBase overrides.
  buffer.writeln('  @override');
  buffer.writeln('  String get routeId => routeName;');
  buffer.writeln();
  buffer.writeln('  @override');
  buffer.writeln('  Object? get params => encode();');

  buffer.writeln('}');
}

String _generateDecodeFromMapMethod(
  String className,
  List<FieldInfo> fields,
  Map<String, TypeDefinition> typeGraph,
) {
  final buffer = StringBuffer();
  buffer.writeln('static $className decodeFromMap(Map<Object?, Object?> map) {');
  buffer.write('    return $className(');

  if (fields.isEmpty) {
    buffer.writeln(');');
  } else {
    buffer.writeln();
    for (final field in fields) {
      final fieldName = field.name;
      final accessor = _mapAccessorForType(fieldName, field.type);
      buffer.writeln('      $fieldName: $accessor,');
    }
    buffer.writeln('    );');
  }

  buffer.write('  }');
  return buffer.toString();
}

String _mapAccessorForType(String fieldName, TypeInfo type) {
  final name = type.name;
  final isNullable = type.isNullable;

  // iOS URL encoding passes all values as Strings.
  if (name == 'String') {
    return isNullable
        ? "map['$fieldName'] as String?"
        : "map['$fieldName'] as String? ?? ''";
  }
  if (name == 'int') {
    return isNullable
        ? "map['$fieldName'] != null ? int.tryParse(map['$fieldName'] as String? ?? '') : null"
        : "int.tryParse(map['$fieldName'] as String? ?? '') ?? 0";
  }
  if (name == 'double') {
    return isNullable
        ? "map['$fieldName'] != null ? double.tryParse(map['$fieldName'] as String? ?? '') : null"
        : "double.tryParse(map['$fieldName'] as String? ?? '') ?? 0.0";
  }
  if (name == 'bool') {
    return isNullable
        ? "map['$fieldName'] != null ? map['$fieldName'] == 'true' : null"
        : "map['$fieldName'] == 'true'";
  }

  // For complex types, just cast (they won't work via URL anyway).
  return isNullable ? "map['$fieldName'] as $name?" : "map['$fieldName'] as $name";
}

void _writeNativeRoute(
  StringBuffer buffer,
  RouteDefinition route,
  Map<String, TypeDefinition> typeGraph,
) {
  final className = route.className;
  final fields = route.fields;
  final routeName = route.routeName;

  // Class declaration.
  buffer.writeln('class $className {');

  // Constructor.
  buffer.write('  const $className(');
  if (fields.isNotEmpty) {
    buffer.writeln('{');
    for (final field in fields) {
      final required = field.isRequired ? 'required ' : '';
      buffer.writeln('    ${required}this.${field.name},');
    }
    buffer.write('  }');
  }
  buffer.writeln(');');
  buffer.writeln();

  // Fields.
  for (final field in fields) {
    buffer.writeln('  final ${field.type.toSource()} ${field.name};');
  }

  if (fields.isNotEmpty) {
    buffer.writeln();
  }

  // Static route ID.
  buffer.writeln("  static const String routeId = '$routeName';");
  buffer.writeln();

  // encode() method.
  buffer.writeln('  ${generateDartEncodeMethod(fields, typeGraph)};');
  buffer.writeln();

  // decode() static method.
  buffer.writeln('  ${generateDartDecodeMethod(className, fields, typeGraph)}');
  buffer.writeln();

  // toNativeRoute() method.
  buffer.writeln('  NativeRouteWrapper toNativeRoute() => NativeRouteWrapper(');
  buffer.writeln('    PageSettings(routeId: routeId, params: encode()),');
  buffer.writeln('  );');

  buffer.writeln('}');
}

void _writeFlutterRouteHandler(
  StringBuffer buffer,
  List<RouteDefinition> routes,
) {
  buffer.writeln('abstract class FlutterRouteHandler {');
  buffer.writeln('  const FlutterRouteHandler();');
  buffer.writeln();

  // handle() method.
  buffer.writeln('  Widget handle(PageSettings route) {');
  buffer.writeln('    final params = route.params;');
  buffer.writeln('    switch (route.routeId) {');

  for (final route in routes) {
    final methodName = methodNameFromClassName(route.className);
    buffer.writeln("      case '${route.routeName}':");
    buffer.writeln('        return $methodName(');
    buffer.writeln('          params is List');
    buffer.writeln(
      '              ? ${route.className}.decode(params.cast<Object?>())',
    );
    buffer.writeln(
      '              : ${route.className}.decodeFromMap(params as Map<Object?, Object?>? ?? {}),',
    );
    buffer.writeln('        );');
  }

  buffer.writeln('      default:');
  buffer.writeln('        return onUnknownRoute(route);');
  buffer.writeln('    }');
  buffer.writeln('  }');
  buffer.writeln();

  // Abstract methods for each route.
  for (final route in routes) {
    final methodName = methodNameFromClassName(route.className);
    buffer.writeln('  Widget $methodName(${route.className} page);');
  }

  buffer.writeln();
  buffer.writeln('  Widget onUnknownRoute(PageSettings route) {');
  buffer.writeln(
    "    return Center(child: Text('Unknown route: \${route.routeId}'));",
  );
  buffer.writeln('  }');
  buffer.writeln('}');
}
