// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package co.leancode.inlay.navigator

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object InlayNavigatorApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is InlayNavigatorError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class InlayNavigatorError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Describes a page to navigate to (Flutter or native).
 *
 * [routeId] identifies the screen. [params] carries the page data
 * using pigeon's `encode()` output — the native side decodes it with
 * the matching pigeon-generated class's `fromList()` / `decode()`.
 *
 * For Flutter pages pushed from native, [params] is a `Map<String, String>`
 * (produced by URL-decoding the `initialRoute` string).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PageSettings (
  /** Identifies which screen to show (e.g. "soundsNotifications"). */
  val routeId: String,
  /**
   * Page parameters. For native pages this is the pigeon-encoded object
   * (via `encode()`). For Flutter pages this is a `Map<String, String>`.
   */
  val params: Any? = null,
  /**
   * URL path derived from the typed route object (e.g. "/products/42").
   * When set, used as the `initialRoute` for router-based navigation.
   */
  val path: String? = null,
  /**
   * Fingerprint of the generated schema on the sending side.
   *
   * Set automatically by generated `toPageSettings()` implementations and
   * verified automatically by the generated decoders on the receiving
   * side, so a host and module built from different schema revisions fail
   * with a descriptive error instead of corrupting positional data.
   * `null` when the sender predates fingerprinting (check skipped).
   */
  val schemaFingerprint: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PageSettings {
      val routeId = pigeonVar_list[0] as String
      val params = pigeonVar_list[1]
      val path = pigeonVar_list[2] as String?
      val schemaFingerprint = pigeonVar_list[3] as String?
      return PageSettings(routeId, params, path, schemaFingerprint)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      routeId,
      params,
      path,
      schemaFingerprint,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PageSettings) {
      return false
    }
    if (this === other) {
      return true
    }
    return InlayNavigatorApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class InlayNavigatorApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PageSettings.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PageSettings -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Host API — Flutter asks the platform to push a new Activity/ViewController.
 *
 * The platform side owns the Activity/ViewController stack; Flutter cannot
 * start them directly. This API hides FlutterEngine / EngineGroup /
 * Activity/ViewController internals from the developer.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface InlayNavigatorHostApi {
  /** Push a new Flutter Activity/ViewController for the given page. */
  fun push(page: PageSettings)
  /** Pop the current Flutter Activity/ViewController. */
  fun pop()
  /**
   * Enable/disable native iOS back gesture for this container.
   *
   * Used by Flutter to disable container-level swipe-back while the in-Flutter
   * navigator can handle pop, preventing double-pop.
   */
  fun setNativePopGestureEnabled(enabled: Boolean)
  /**
   * Open a native Activity/ViewController identified by [route].
   *
   * The platform side dispatches to a registered native route handler.
   * If no handler is registered for the given `routeId`, this is a no-op
   * (or throws, depending on platform configuration).
   */
  fun pushNativeRoute(route: PageSettings)
  /**
   * Return the full route data that the native host stored for this engine.
   *
   * Flutter calls this once at startup to retrieve the typed route object
   * (with all fields, including complex nested objects). Returns `null`
   * for the prewarm engine or when no data was set.
   */
  fun getInitialRouteData(): PageSettings?
  /**
   * Present a Flutter dialog in a transparent native container.
   *
   * The native side creates a transparent Activity/ViewController and
   * starts a new Flutter engine. Flutter renders the dialog content
   * (barrier, animation, positioning) over the native screen underneath.
   */
  fun presentDialog(page: PageSettings)

  companion object {
    /** The codec used by InlayNavigatorHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      InlayNavigatorApiPigeonCodec()
    }
    /** Sets up an instance of `InlayNavigatorHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: InlayNavigatorHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inlay.InlayNavigatorHostApi.push$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pageArg = args[0] as PageSettings
            val wrapped: List<Any?> = try {
              api.push(pageArg)
              listOf(null)
            } catch (exception: Throwable) {
              InlayNavigatorApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inlay.InlayNavigatorHostApi.pop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.pop()
              listOf(null)
            } catch (exception: Throwable) {
              InlayNavigatorApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inlay.InlayNavigatorHostApi.setNativePopGestureEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setNativePopGestureEnabled(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              InlayNavigatorApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inlay.InlayNavigatorHostApi.pushNativeRoute$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val routeArg = args[0] as PageSettings
            val wrapped: List<Any?> = try {
              api.pushNativeRoute(routeArg)
              listOf(null)
            } catch (exception: Throwable) {
              InlayNavigatorApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inlay.InlayNavigatorHostApi.getInitialRouteData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getInitialRouteData())
            } catch (exception: Throwable) {
              InlayNavigatorApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inlay.InlayNavigatorHostApi.presentDialog$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pageArg = args[0] as PageSettings
            val wrapped: List<Any?> = try {
              api.presentDialog(pageArg)
              listOf(null)
            } catch (exception: Throwable) {
              InlayNavigatorApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
