// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
public final class InlayNavigatorError: Error {
  public let code: String
  public let message: String?
  public let details: Sendable?

  public init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  public var localizedDescription: String {
    return
      "InlayNavigatorError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? InlayNavigatorError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsInlayNavigatorApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsInlayNavigatorApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsInlayNavigatorApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashInlayNavigatorApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashInlayNavigatorApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashInlayNavigatorApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Describes a page to navigate to (Flutter or native).
///
/// [routeId] identifies the screen. [params] carries the page data
/// using pigeon's `encode()` output — the native side decodes it with
/// the matching pigeon-generated class's `fromList()` / `decode()`.
///
/// For Flutter pages pushed from native, [params] is a `Map<String, String>`
/// (produced by URL-decoding the `initialRoute` string).
///
/// Generated class from Pigeon that represents data sent in messages.
public struct PageSettings: Hashable {
  /// Identifies which screen to show (e.g. "soundsNotifications").
  public var routeId: String
  /// Page parameters. For native pages this is the pigeon-encoded object
  /// (via `encode()`). For Flutter pages this is a `Map<String, String>`.
  public var params: Any? = nil
  /// URL path derived from the typed route object (e.g. "/products/42").
  /// When set, used as the `initialRoute` for router-based navigation.
  public var path: String? = nil

  public init(routeId: String, params: Any? = nil, path: String? = nil) {
    self.routeId = routeId
    self.params = params
    self.path = path
  }


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PageSettings? {
    let routeId = pigeonVar_list[0] as! String
    let params: Any? = pigeonVar_list[1]
    let path: String? = nilOrValue(pigeonVar_list[2])

    return PageSettings(
      routeId: routeId,
      params: params,
      path: path
    )
  }
  func toList() -> [Any?] {
    return [
      routeId,
      params,
      path,
    ]
  }
  public static func == (lhs: PageSettings, rhs: PageSettings) -> Bool {
    return deepEqualsInlayNavigatorApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashInlayNavigatorApi(value: toList(), hasher: &hasher)
  }
}

private class InlayNavigatorApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return PageSettings.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class InlayNavigatorApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PageSettings {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class InlayNavigatorApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return InlayNavigatorApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return InlayNavigatorApiPigeonCodecWriter(data: data)
  }
}

class InlayNavigatorApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = InlayNavigatorApiPigeonCodec(readerWriter: InlayNavigatorApiPigeonCodecReaderWriter())
}

/// Host API — Flutter asks the platform to push a new Activity/ViewController.
///
/// The platform side owns the Activity/ViewController stack; Flutter cannot
/// start them directly. This API hides FlutterEngine / EngineGroup /
/// Activity/ViewController internals from the developer.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol InlayNavigatorHostApi {
  /// Push a new Flutter Activity/ViewController for the given page.
  func push(page: PageSettings) throws
  /// Pop the current Flutter Activity/ViewController.
  func pop() throws
  /// Enable/disable native iOS back gesture for this container.
  ///
  /// Used by Flutter to disable container-level swipe-back while the in-Flutter
  /// navigator can handle pop, preventing double-pop.
  func setNativePopGestureEnabled(enabled: Bool) throws
  /// Open a native Activity/ViewController identified by [route].
  ///
  /// The platform side dispatches to a registered native route handler.
  /// If no handler is registered for the given `routeId`, this is a no-op
  /// (or throws, depending on platform configuration).
  func pushNativeRoute(route: PageSettings) throws
  /// Return the full route data that the native host stored for this engine.
  ///
  /// Flutter calls this once at startup to retrieve the typed route object
  /// (with all fields, including complex nested objects). Returns `null`
  /// for the prewarm engine or when no data was set.
  func getInitialRouteData() throws -> PageSettings?
  /// Present a Flutter dialog in a transparent native container.
  ///
  /// The native side creates a transparent Activity/ViewController and
  /// starts a new Flutter engine. Flutter renders the dialog content
  /// (barrier, animation, positioning) over the native screen underneath.
  func presentDialog(page: PageSettings) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class InlayNavigatorHostApiSetup {
  static var codec: FlutterStandardMessageCodec { InlayNavigatorApiPigeonCodec.shared }
  /// Sets up an instance of `InlayNavigatorHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: InlayNavigatorHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Push a new Flutter Activity/ViewController for the given page.
    let pushChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inlay.InlayNavigatorHostApi.push\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pushChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pageArg = args[0] as! PageSettings
        do {
          try api.push(page: pageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pushChannel.setMessageHandler(nil)
    }
    /// Pop the current Flutter Activity/ViewController.
    let popChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inlay.InlayNavigatorHostApi.pop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      popChannel.setMessageHandler { _, reply in
        do {
          try api.pop()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      popChannel.setMessageHandler(nil)
    }
    /// Enable/disable native iOS back gesture for this container.
    ///
    /// Used by Flutter to disable container-level swipe-back while the in-Flutter
    /// navigator can handle pop, preventing double-pop.
    let setNativePopGestureEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inlay.InlayNavigatorHostApi.setNativePopGestureEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setNativePopGestureEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setNativePopGestureEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setNativePopGestureEnabledChannel.setMessageHandler(nil)
    }
    /// Open a native Activity/ViewController identified by [route].
    ///
    /// The platform side dispatches to a registered native route handler.
    /// If no handler is registered for the given `routeId`, this is a no-op
    /// (or throws, depending on platform configuration).
    let pushNativeRouteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inlay.InlayNavigatorHostApi.pushNativeRoute\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pushNativeRouteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let routeArg = args[0] as! PageSettings
        do {
          try api.pushNativeRoute(route: routeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pushNativeRouteChannel.setMessageHandler(nil)
    }
    /// Return the full route data that the native host stored for this engine.
    ///
    /// Flutter calls this once at startup to retrieve the typed route object
    /// (with all fields, including complex nested objects). Returns `null`
    /// for the prewarm engine or when no data was set.
    let getInitialRouteDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inlay.InlayNavigatorHostApi.getInitialRouteData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getInitialRouteDataChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getInitialRouteData()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getInitialRouteDataChannel.setMessageHandler(nil)
    }
    /// Present a Flutter dialog in a transparent native container.
    ///
    /// The native side creates a transparent Activity/ViewController and
    /// starts a new Flutter engine. Flutter renders the dialog content
    /// (barrier, animation, positioning) over the native screen underneath.
    let presentDialogChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inlay.InlayNavigatorHostApi.presentDialog\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      presentDialogChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pageArg = args[0] as! PageSettings
        do {
          try api.presentDialog(page: pageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      presentDialogChannel.setMessageHandler(nil)
    }
  }
}
