// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsAdd2AppNavigatorApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsAdd2AppNavigatorApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsAdd2AppNavigatorApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashAdd2AppNavigatorApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashAdd2AppNavigatorApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashAdd2AppNavigatorApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Describes a page to navigate to (Flutter or native).
///
/// [routeId] identifies the screen. [params] carries the page data
/// using pigeon's `encode()` output — the native side decodes it with
/// the matching pigeon-generated class's `fromList()` / `decode()`.
///
/// For Flutter pages pushed from native, [params] is a `Map<String, String>`
/// (produced by URL-decoding the `initialRoute` string).
///
/// Generated class from Pigeon that represents data sent in messages.
struct PageSettings: Hashable {
  /// Identifies which screen to show (e.g. "soundsNotifications").
  var routeId: String
  /// Page parameters. For native pages this is the pigeon-encoded object
  /// (via `encode()`). For Flutter pages this is a `Map<String, String>`.
  var params: Any? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PageSettings? {
    let routeId = pigeonVar_list[0] as! String
    let params: Any? = pigeonVar_list[1]

    return PageSettings(
      routeId: routeId,
      params: params
    )
  }
  func toList() -> [Any?] {
    return [
      routeId,
      params,
    ]
  }
  static func == (lhs: PageSettings, rhs: PageSettings) -> Bool {
    return deepEqualsAdd2AppNavigatorApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAdd2AppNavigatorApi(value: toList(), hasher: &hasher)
  }
}

private class Add2AppNavigatorApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return PageSettings.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class Add2AppNavigatorApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PageSettings {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class Add2AppNavigatorApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return Add2AppNavigatorApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return Add2AppNavigatorApiPigeonCodecWriter(data: data)
  }
}

class Add2AppNavigatorApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = Add2AppNavigatorApiPigeonCodec(readerWriter: Add2AppNavigatorApiPigeonCodecReaderWriter())
}

/// Host API — Flutter asks the platform to push a new Activity/ViewController.
///
/// The platform side owns the Activity/ViewController stack; Flutter cannot
/// start them directly. This API hides FlutterEngine / EngineGroup /
/// Activity/ViewController internals from the developer.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol Add2AppNavigatorHostApi {
  /// Push a new Flutter Activity/ViewController for the given page.
  func push(page: PageSettings) throws
  /// Pop the current Flutter Activity/ViewController.
  func pop() throws
  /// Open a native Activity/ViewController identified by [route].
  ///
  /// The platform side dispatches to a registered native route handler.
  /// If no handler is registered for the given `routeId`, this is a no-op
  /// (or throws, depending on platform configuration).
  func pushNativeRoute(route: PageSettings) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class Add2AppNavigatorHostApiSetup {
  static var codec: FlutterStandardMessageCodec { Add2AppNavigatorApiPigeonCodec.shared }
  /// Sets up an instance of `Add2AppNavigatorHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: Add2AppNavigatorHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Push a new Flutter Activity/ViewController for the given page.
    let pushChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.leancode_add2app.Add2AppNavigatorHostApi.push\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pushChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pageArg = args[0] as! PageSettings
        do {
          try api.push(page: pageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pushChannel.setMessageHandler(nil)
    }
    /// Pop the current Flutter Activity/ViewController.
    let popChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.leancode_add2app.Add2AppNavigatorHostApi.pop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      popChannel.setMessageHandler { _, reply in
        do {
          try api.pop()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      popChannel.setMessageHandler(nil)
    }
    /// Open a native Activity/ViewController identified by [route].
    ///
    /// The platform side dispatches to a registered native route handler.
    /// If no handler is registered for the given `routeId`, this is a no-op
    /// (or throws, depending on platform configuration).
    let pushNativeRouteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.leancode_add2app.Add2AppNavigatorHostApi.pushNativeRoute\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pushNativeRouteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let routeArg = args[0] as! PageSettings
        do {
          try api.pushNativeRoute(route: routeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pushNativeRouteChannel.setMessageHandler(nil)
    }
  }
}
