// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsKeyValueStorageApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsKeyValueStorageApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsKeyValueStorageApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashKeyValueStorageApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashKeyValueStorageApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashKeyValueStorageApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// A generic key-value entry stored on the platform side.
///
/// Generated class from Pigeon that represents data sent in messages.
struct StorageEntry: Hashable {
  /// The key for this entry.
  var key: String
  /// The JSON-encoded value for this entry.
  /// We use String (JSON) so Pigeon can transport any structured data.
  var value: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StorageEntry? {
    let key = pigeonVar_list[0] as! String
    let value = pigeonVar_list[1] as! String

    return StorageEntry(
      key: key,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      key,
      value,
    ]
  }
  static func == (lhs: StorageEntry, rhs: StorageEntry) -> Bool {
    return deepEqualsKeyValueStorageApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashKeyValueStorageApi(value: toList(), hasher: &hasher)
  }
}

/// Batch of changed entries, used for change notifications.
///
/// Generated class from Pigeon that represents data sent in messages.
struct StorageChangeEvent: Hashable {
  /// The entries that changed (new values).
  var entries: [StorageEntry]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StorageChangeEvent? {
    let entries = pigeonVar_list[0] as! [StorageEntry]

    return StorageChangeEvent(
      entries: entries
    )
  }
  func toList() -> [Any?] {
    return [
      entries
    ]
  }
  static func == (lhs: StorageChangeEvent, rhs: StorageChangeEvent) -> Bool {
    return deepEqualsKeyValueStorageApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashKeyValueStorageApi(value: toList(), hasher: &hasher)
  }
}

private class KeyValueStorageApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return StorageEntry.fromList(self.readValue() as! [Any?])
    case 130:
      return StorageChangeEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class KeyValueStorageApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? StorageEntry {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? StorageChangeEvent {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class KeyValueStorageApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return KeyValueStorageApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return KeyValueStorageApiPigeonCodecWriter(data: data)
  }
}

class KeyValueStorageApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = KeyValueStorageApiPigeonCodec(readerWriter: KeyValueStorageApiPigeonCodecReaderWriter())
}

/// Host API — Flutter calls into platform (Android/iOS).
/// The platform owns the data; Flutter reads/writes through this API.
/// Uses TaskQueue.serialBackgroundThread for thread-safety.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol KeyValueStorageHostApi {
  /// Put a value into the storage. Overwrites if key already exists.
  func put(entry: StorageEntry) throws
  /// Put multiple values at once (atomic batch).
  func putAll(entries: [StorageEntry]) throws
  /// Get a value by key. Returns null if not found.
  func get(key: String) throws -> StorageEntry?
  /// Get all values whose keys start with the given prefix.
  func getByPrefix(prefix: String) throws -> [StorageEntry]
  /// Remove a value by key. Returns true if the key existed.
  func remove(key: String) throws -> Bool
  /// Remove all values whose keys start with the given prefix.
  func removeByPrefix(prefix: String) throws
  /// Get all stored entries (full dump).
  func getAll() throws -> [StorageEntry]
  /// Clear all storage.
  func clear() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class KeyValueStorageHostApiSetup {
  static var codec: FlutterStandardMessageCodec { KeyValueStorageApiPigeonCodec.shared }
  /// Sets up an instance of `KeyValueStorageHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: KeyValueStorageHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    #if os(iOS)
      let taskQueue = binaryMessenger.makeBackgroundTaskQueue?()
    #else
      let taskQueue: FlutterTaskQueue? = nil
    #endif
    /// Put a value into the storage. Overwrites if key already exists.
    let putChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.leancode_add2app.KeyValueStorageHostApi.put\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.leancode_add2app.KeyValueStorageHostApi.put\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      putChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let entryArg = args[0] as! StorageEntry
        do {
          try api.put(entry: entryArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      putChannel.setMessageHandler(nil)
    }
    /// Put multiple values at once (atomic batch).
    let putAllChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.leancode_add2app.KeyValueStorageHostApi.putAll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.leancode_add2app.KeyValueStorageHostApi.putAll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      putAllChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let entriesArg = args[0] as! [StorageEntry]
        do {
          try api.putAll(entries: entriesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      putAllChannel.setMessageHandler(nil)
    }
    /// Get a value by key. Returns null if not found.
    let getChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.leancode_add2app.KeyValueStorageHostApi.get\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.leancode_add2app.KeyValueStorageHostApi.get\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      getChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        do {
          let result = try api.get(key: keyArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getChannel.setMessageHandler(nil)
    }
    /// Get all values whose keys start with the given prefix.
    let getByPrefixChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.leancode_add2app.KeyValueStorageHostApi.getByPrefix\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.leancode_add2app.KeyValueStorageHostApi.getByPrefix\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      getByPrefixChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let prefixArg = args[0] as! String
        do {
          let result = try api.getByPrefix(prefix: prefixArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getByPrefixChannel.setMessageHandler(nil)
    }
    /// Remove a value by key. Returns true if the key existed.
    let removeChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.leancode_add2app.KeyValueStorageHostApi.remove\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.leancode_add2app.KeyValueStorageHostApi.remove\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      removeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        do {
          let result = try api.remove(key: keyArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeChannel.setMessageHandler(nil)
    }
    /// Remove all values whose keys start with the given prefix.
    let removeByPrefixChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.leancode_add2app.KeyValueStorageHostApi.removeByPrefix\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.leancode_add2app.KeyValueStorageHostApi.removeByPrefix\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      removeByPrefixChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let prefixArg = args[0] as! String
        do {
          try api.removeByPrefix(prefix: prefixArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeByPrefixChannel.setMessageHandler(nil)
    }
    /// Get all stored entries (full dump).
    let getAllChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.leancode_add2app.KeyValueStorageHostApi.getAll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.leancode_add2app.KeyValueStorageHostApi.getAll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      getAllChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAll()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAllChannel.setMessageHandler(nil)
    }
    /// Clear all storage.
    let clearChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.leancode_add2app.KeyValueStorageHostApi.clear\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.leancode_add2app.KeyValueStorageHostApi.clear\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      clearChannel.setMessageHandler { _, reply in
        do {
          try api.clear()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearChannel.setMessageHandler(nil)
    }
  }
}
/// Flutter API — Platform calls into Flutter to notify about changes.
/// Each Flutter engine isolate registers this so it gets notified when
/// any other engine (or native code) changes storage.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol KeyValueStorageFlutterApiProtocol {
  /// Called when entries in the storage have changed.
  func onStorageChanged(event eventArg: StorageChangeEvent, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class KeyValueStorageFlutterApi: KeyValueStorageFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: KeyValueStorageApiPigeonCodec {
    return KeyValueStorageApiPigeonCodec.shared
  }
  /// Called when entries in the storage have changed.
  func onStorageChanged(event eventArg: StorageChangeEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.leancode_add2app.KeyValueStorageFlutterApi.onStorageChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
