// GENERATED CODE — DO NOT MODIFY BY HAND
// Generated by leancode_add2app_gen

import Foundation
import UIKit

/// Abstract handler for native routes dispatched from Flutter.
///
/// Subclass this and override each `on*` method to handle
/// native route requests. The base class decodes `PageSettings`
/// into pigeon-generated page structs automatically via `fromList()`.
class NativeRouteHandler: NativeRouteHandling {

    /// Dispatches a `PageSettings` to the correct typed handler.
    /// Called by the framework — do NOT call this directly.
    func handle(viewController: UIViewController, route: PageSettings) {
        switch route.routeId {
        case "nativeEditProfile":
            onNativeEditProfile(
                page: NativeEditProfilePage.fromList(route.params as! [Any?])!,
                viewController: viewController
            )
        case "nativeMediaViewer":
            onNativeMediaViewer(
                page: NativeMediaViewerPage.fromList(route.params as! [Any?])!,
                viewController: viewController
            )
        default:
            onUnknownRoute(route: route, viewController: viewController)
        }
    }

    /// Override to handle the `NativeEditProfilePage` route.
    func onNativeEditProfile(page: NativeEditProfilePage, viewController: UIViewController) {
        fatalError("onNativeEditProfile(page:viewController:) must be overridden")
    }

    /// Override to handle the `NativeMediaViewerPage` route.
    func onNativeMediaViewer(page: NativeMediaViewerPage, viewController: UIViewController) {
        fatalError("onNativeMediaViewer(page:viewController:) must be overridden")
    }

    /// Called when no handler matches the route ID.
    /// Override to customize error handling.
    func onUnknownRoute(route: PageSettings, viewController: UIViewController) {
        fatalError("No handler for native route '\(route.routeId)'.")
    }
}
