// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

// PigeonError is defined in Add2AppNavigatorApi.g.swift — shared across
// all pigeon-generated files compiled in the same target.

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsPages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsPages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsPages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashPages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashPages(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashPages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Page settings for the Sounds & Notifications screen.
///
/// Generated class from Pigeon that represents data sent in messages.
struct SoundsNotificationsPage: Hashable {
  var contactId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SoundsNotificationsPage? {
    let contactId = pigeonVar_list[0] as! String

    return SoundsNotificationsPage(
      contactId: contactId
    )
  }
  func toList() -> [Any?] {
    return [
      contactId
    ]
  }
  static func == (lhs: SoundsNotificationsPage, rhs: SoundsNotificationsPage) -> Bool {
    return deepEqualsPages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SetWallpaperPage: Hashable {
  var recipientId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SetWallpaperPage? {
    let recipientId = pigeonVar_list[0] as! String

    return SetWallpaperPage(
      recipientId: recipientId
    )
  }
  func toList() -> [Any?] {
    return [
      recipientId
    ]
  }
  static func == (lhs: SetWallpaperPage, rhs: SetWallpaperPage) -> Bool {
    return deepEqualsPages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ContactDetailsPage: Hashable {
  var contactId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ContactDetailsPage? {
    let contactId = pigeonVar_list[0] as! String

    return ContactDetailsPage(
      contactId: contactId
    )
  }
  func toList() -> [Any?] {
    return [
      contactId
    ]
  }
  static func == (lhs: ContactDetailsPage, rhs: ContactDetailsPage) -> Bool {
    return deepEqualsPages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeEditProfilePage: Hashable {
  var contactId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeEditProfilePage? {
    let contactId = pigeonVar_list[0] as! String

    return NativeEditProfilePage(
      contactId: contactId
    )
  }
  func toList() -> [Any?] {
    return [
      contactId
    ]
  }
  static func == (lhs: NativeEditProfilePage, rhs: NativeEditProfilePage) -> Bool {
    return deepEqualsPages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeMediaViewerPage: Hashable {
  var mediaId: String
  var mediaType: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeMediaViewerPage? {
    let mediaId = pigeonVar_list[0] as! String
    let mediaType: String? = nilOrValue(pigeonVar_list[1])

    return NativeMediaViewerPage(
      mediaId: mediaId,
      mediaType: mediaType
    )
  }
  func toList() -> [Any?] {
    return [
      mediaId,
      mediaType,
    ]
  }
  static func == (lhs: NativeMediaViewerPage, rhs: NativeMediaViewerPage) -> Bool {
    return deepEqualsPages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPages(value: toList(), hasher: &hasher)
  }
}

private class PagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return SoundsNotificationsPage.fromList(self.readValue() as! [Any?])
    case 130:
      return SetWallpaperPage.fromList(self.readValue() as! [Any?])
    case 131:
      return ContactDetailsPage.fromList(self.readValue() as! [Any?])
    case 132:
      return NativeEditProfilePage.fromList(self.readValue() as! [Any?])
    case 133:
      return NativeMediaViewerPage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SoundsNotificationsPage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? SetWallpaperPage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? ContactDetailsPage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NativeEditProfilePage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? NativeMediaViewerPage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PagesPigeonCodecWriter(data: data)
  }
}

class PagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PagesPigeonCodec(readerWriter: PagesPigeonCodecReaderWriter())
}

