import 'package:inlay_gen/src/generators/dart/dart_routes_generator.dart'
    show extractPathParamNames, isSimpleType;
import 'package:inlay_gen/src/generators/java/java_serialization.dart';
import 'package:inlay_gen/src/models/data_type_definition.dart';
import 'package:inlay_gen/src/models/route_definition.dart';
import 'package:inlay_gen/src/models/schema.dart';
import 'package:inlay_gen/src/models/type_info.dart';
import 'package:inlay_gen/src/parser/type_resolver.dart';
import 'package:inlay_gen/src/utils/file_header.dart';
import 'package:inlay_gen/src/utils/naming.dart';

/// File name of the generated schema-fingerprint holder.
const javaSchemaFileName = 'InlaySchema.java';

/// Generates Java code for routes from a resolved schema.
///
/// Java requires one public class per file, so unlike the Kotlin and Swift
/// generators this returns a map of file name (e.g. `CounterPage.java`) to
/// file content. The output mirrors the Kotlin one:
///
/// - Classes for routes and shared types with `toList()` / `fromList()`
///   serialization, getters, `equals` / `hashCode`
/// - Enums
/// - `InlaySchema` holding the schema fingerprint
/// - `NativeRouteHandler` base class
///
/// Routes declaring a result type implement `FlutterRouteWithResult<R>` /
/// `FlutterDialogRouteWithResult<R>` (instance `decodeResult`) and get a
/// static `encodeResult`. Native routes get both codecs as static methods.
Map<String, String> generateJavaRoutes({
  required Schema schema,
  required Map<String, TypeDefinition> typeGraph,
  required String packageName,
  required String schemaFingerprint,
  List<String> header = const [],
}) {
  final files = <String, String>{};

  void add(String className, String body) {
    files['$className.java'] = _javaFile(packageName, body, header);
  }

  add('InlaySchema', _schemaClass(schemaFingerprint));

  for (final enumDef in schema.enums) {
    add(enumDef.name, _enumBody(enumDef));
  }

  for (final dataClass in schema.dataClasses) {
    add(dataClass.className, _dataClassBody(dataClass, typeGraph));
  }

  for (final route in schema.allRoutes) {
    final body = StringBuffer();
    _writeRouteClass(body, route, typeGraph);
    add(route.className, body.toString());
  }

  if (schema.nativeRoutes.isNotEmpty) {
    add('NativeRouteHandler', _nativeRouteHandlerBody(schema.nativeRoutes));
  }

  return files;
}

/// Wraps a class [body] into a complete Java source file: the configured
/// [header] lines, the generated-code banner, package declaration and the
/// imports the body actually uses.
String _javaFile(String packageName, String body, List<String> header) {
  final buffer = StringBuffer(renderFileHeader(header))
    ..writeln('// GENERATED CODE — DO NOT MODIFY BY HAND')
    ..writeln('// Generated by inlay_gen')
    ..writeln()
    ..writeln('package $packageName;')
    ..writeln();

  final imports = _importsFor(body);
  if (imports.isNotEmpty) {
    imports.forEach(buffer.writeln);
    buffer.writeln();
  }

  buffer.write(body.trimLeft());
  final output = buffer.toString();
  return output.endsWith('\n') ? output : '$output\n';
}

/// Imports keyed by the simple name whose use in a class body requires them.
///
/// The generated `NativeRouteHandler` shadows `co.leancode.inlay
/// .NativeRouteHandler`, which is therefore always referenced by its fully
/// qualified name and never imported.
const _importsBySimpleName = <String, String>{
  'Arrays': 'java.util.Arrays',
  'Collections': 'java.util.Collections',
  'HashMap': 'java.util.HashMap',
  'List': 'java.util.List',
  'ArrayList': 'java.util.ArrayList',
  'Map': 'java.util.Map',
  'Objects': 'java.util.Objects',
  'Collectors': 'java.util.stream.Collectors',
  'Consumer': 'java.util.function.Consumer',
  'Context': 'android.content.Context',
  'Unit': 'kotlin.Unit',
  'Function1': 'kotlin.jvm.functions.Function1',
  'FlutterRoute': 'co.leancode.inlay.FlutterRoute',
  'FlutterRouteWithResult': 'co.leancode.inlay.FlutterRouteWithResult',
  'FlutterDialogRoute': 'co.leancode.inlay.FlutterDialogRoute',
  'FlutterDialogRouteWithResult':
      'co.leancode.inlay.FlutterDialogRouteWithResult',
  'PageSettings': 'co.leancode.inlay.navigator.PageSettings',
};

List<String> _importsFor(String body) {
  final imports = <String>[];
  for (final MapEntry(key: name, value: import)
      in _importsBySimpleName.entries) {
    // Word boundaries keep e.g. `List` from matching `toList` or `ArrayList`.
    if (RegExp('(?<![A-Za-z0-9_.])$name(?![A-Za-z0-9_])').hasMatch(body)) {
      imports.add('import $import;');
    }
  }
  return imports..sort();
}

String _schemaClass(String schemaFingerprint) {
  return '''
/**
 * Fingerprint of the schema this code was generated from.
 *
 * Embedded into every outgoing {@code PageSettings} and verified by the
 * generated route handler, so host/module schema drift fails fast.
 */
public final class InlaySchema {
    public static final String FINGERPRINT = "$schemaFingerprint";

    private InlaySchema() {}
}
''';
}

String _enumBody(EnumDefinition enumDef) {
  final buffer = StringBuffer()..writeln('public enum ${enumDef.name} {');
  for (var i = 0; i < enumDef.values.length; i++) {
    final comma = i < enumDef.values.length - 1 ? ',' : '';
    buffer.writeln('    ${enumDef.values[i]}$comma');
  }
  buffer.writeln('}');
  return buffer.toString();
}

String _dataClassBody(
  DataClassDefinition dataClass,
  Map<String, TypeDefinition> typeGraph,
) {
  final className = dataClass.className;
  final fields = dataClass.fields;
  final buffer = StringBuffer()..writeln('public final class $className {');
  _writeFieldsAndConstructor(buffer, className, fields);
  buffer
    ..writeln()
    ..writeln('    ${generateJavaFromListMethod(className, fields, typeGraph)}')
    ..writeln()
    ..writeln('    ${generateJavaToListMethod(fields, typeGraph)}')
    ..writeln();
  _writeEqualsAndHashCode(buffer, className, fields);
  buffer.writeln('}');
  return buffer.toString();
}

void _writeRouteClass(
  StringBuffer buffer,
  RouteDefinition route,
  Map<String, TypeDefinition> typeGraph,
) {
  final className = route.className;
  final fields = route.fields;
  final isFlutterRoute = route.routeType == RouteType.flutter;
  final isDialogRoute = route.routeType == RouteType.flutterDialog;
  final path = route.path;
  final result = route.resultType;
  final javaResult = result != null ? dartTypeToJava(result) : null;

  // Flutter routes implement FlutterRoute, dialog routes FlutterDialogRoute;
  // routes declaring a result type implement the typed WithResult variants
  // so native callers receive an already-decoded result.
  final String? interface;
  if (isFlutterRoute) {
    interface = javaResult != null
        ? 'FlutterRouteWithResult<$javaResult>'
        : 'FlutterRoute';
  } else if (isDialogRoute) {
    interface = javaResult != null
        ? 'FlutterDialogRouteWithResult<$javaResult>'
        : 'FlutterDialogRoute';
  } else {
    interface = null;
  }
  buffer
    ..writeln(
      interface != null
          ? 'public final class $className implements $interface {'
          : 'public final class $className {',
    )
    ..writeln(
      '    public static final String ROUTE_NAME = "${route.routeName}";',
    );
  if (path != null) {
    buffer.writeln('    public static final String PATH_TEMPLATE = "$path";');
  }
  buffer.writeln();

  _writeFieldsAndConstructor(buffer, className, fields);
  buffer
    ..writeln()
    ..writeln('    ${generateJavaFromListMethod(className, fields, typeGraph)}')
    ..writeln()
    ..writeln('    ${generateJavaToListMethod(fields, typeGraph)}');

  if (isFlutterRoute || isDialogRoute) {
    if (path != null) {
      buffer.writeln();
      _writeToPath(buffer, path, fields, typeGraph);
    }
    buffer
      ..writeln()
      ..writeln('    @Override')
      ..writeln('    public PageSettings toPageSettings() {')
      ..writeln(
        path != null
            ? '        return new PageSettings(ROUTE_NAME, toList(), toPath(), InlaySchema.FINGERPRINT);'
            : '        return new PageSettings(ROUTE_NAME, toList(), null, InlaySchema.FINGERPRINT);',
      )
      ..writeln('    }');
  }

  if (result != null && javaResult != null) {
    // Result codecs: native routes encode (handler side), Flutter/dialog
    // routes decode (native caller side). Java forbids a static and an
    // instance method with the same signature, so Flutter/dialog routes
    // expose `decodeResult` only as the interface's instance method.
    final encode = generateJavaEncode('result', result, typeGraph);
    final decode = generateJavaDecode('raw', result, typeGraph);
    buffer
      ..writeln()
      ..writeln('    public static Object encodeResult($javaResult result) {')
      ..writeln('        return $encode;')
      ..writeln('    }')
      ..writeln();
    if (interface != null) {
      buffer.writeln('    @Override');
    }
    buffer
      ..writeln(
        interface != null
            ? '    public $javaResult decodeResult(Object raw) {'
            : '    public static $javaResult decodeResult(Object raw) {',
      )
      ..writeln('        return raw == null ? null : $decode;')
      ..writeln('    }');
  }

  buffer.writeln();
  _writeEqualsAndHashCode(buffer, className, fields);
  buffer.writeln('}');
}

void _writeFieldsAndConstructor(
  StringBuffer buffer,
  String className,
  List<FieldInfo> fields,
) {
  if (fields.isEmpty) {
    buffer.writeln('    public $className() {}');
    return;
  }

  for (final field in fields) {
    buffer.writeln(
      '    private final ${dartTypeToJava(field.type)} ${field.name};',
    );
  }
  buffer
    ..writeln()
    ..writeln('    public $className(');
  for (var i = 0; i < fields.length; i++) {
    final field = fields[i];
    final comma = i < fields.length - 1 ? ',' : '';
    buffer.writeln(
      '            ${dartTypeToJava(field.type)} ${field.name}$comma',
    );
  }
  buffer.writeln('    ) {');
  for (final field in fields) {
    buffer.writeln('        this.${field.name} = ${field.name};');
  }
  buffer.writeln('    }');

  for (final field in fields) {
    final getter =
        'get${field.name[0].toUpperCase()}${field.name.substring(1)}';
    buffer
      ..writeln()
      ..writeln('    public ${dartTypeToJava(field.type)} $getter() {')
      ..writeln('        return ${field.name};')
      ..writeln('    }');
  }
}

/// `equals` / `hashCode` over all fields. Deep variants so `byte[]` and
/// nested collections compare by content, like Kotlin data classes.
void _writeEqualsAndHashCode(
  StringBuffer buffer,
  String className,
  List<FieldInfo> fields,
) {
  buffer
    ..writeln('    @Override')
    ..writeln('    public boolean equals(Object o) {')
    ..writeln('        if (this == o) {')
    ..writeln('            return true;')
    ..writeln('        }')
    ..writeln('        if (o == null || getClass() != o.getClass()) {')
    ..writeln('            return false;')
    ..writeln('        }');
  if (fields.isEmpty) {
    buffer.writeln('        return true;');
  } else {
    buffer.writeln('        final $className that = ($className) o;');
    for (var i = 0; i < fields.length; i++) {
      final name = fields[i].name;
      final prefix = i == 0 ? '        return ' : '                && ';
      final suffix = i == fields.length - 1 ? ';' : '';
      buffer.writeln('${prefix}Objects.deepEquals($name, that.$name)$suffix');
    }
  }
  buffer
    ..writeln('    }')
    ..writeln()
    ..writeln('    @Override')
    ..writeln('    public int hashCode() {');
  if (fields.isEmpty) {
    buffer.writeln('        return $className.class.hashCode();');
  } else {
    buffer.writeln(
      '        return Arrays.deepHashCode(new Object[] {${fields.map((f) => f.name).join(', ')}});',
    );
  }
  buffer.writeln('    }');
}

/// Writes `toPath()` and, when it encodes anything, the private
/// `encodeRouteParam` helper it uses.
void _writeToPath(
  StringBuffer buffer,
  String path,
  List<FieldInfo> fields,
  Map<String, TypeDefinition> typeGraph,
) {
  final pathParamNames = extractPathParamNames(path);
  final queryFields = fields
      .where(
        (f) =>
            !pathParamNames.contains(f.name) && isSimpleType(f.type, typeGraph),
      )
      .toList();

  var pathExpr = path;
  for (final paramName in pathParamNames) {
    final field = fields.where((f) => f.name == paramName).firstOrNull;
    final isNullable = field?.type.isNullable ?? false;
    final encode = isNullable
        ? '" + encodeRouteParam($paramName == null ? "" : String.valueOf($paramName)) + "'
        : '" + encodeRouteParam(String.valueOf($paramName)) + "';
    pathExpr = pathExpr.replaceAll(':$paramName', encode);
  }
  // Drop the empty string concatenations a leading/trailing param leaves.
  pathExpr = '"$pathExpr"'.replaceAll('"" + ', '').replaceAll(' + ""', '');

  if (queryFields.isEmpty) {
    buffer
      ..writeln('    public String toPath() {')
      ..writeln('        return $pathExpr;')
      ..writeln('    }');
  } else {
    buffer
      ..writeln('    public String toPath() {')
      ..writeln('        final String basePath = $pathExpr;')
      ..writeln('        final List<String> query = new ArrayList<>();');
    for (final field in queryFields) {
      final name = field.name;
      final entry =
          'query.add("$name=" + encodeRouteParam(String.valueOf($name)));';
      if (field.type.isNullable) {
        buffer
          ..writeln('        if ($name != null) {')
          ..writeln('            $entry')
          ..writeln('        }');
      } else {
        buffer.writeln('        $entry');
      }
    }
    buffer
      ..writeln('        if (query.isEmpty()) {')
      ..writeln('            return basePath;')
      ..writeln('        }')
      ..writeln('        return basePath + "?" + String.join("&", query);')
      ..writeln('    }');
  }

  if (pathParamNames.isNotEmpty || queryFields.isNotEmpty) {
    // URLEncoder.encode(String, Charset) is API 33+. The (String, String)
    // overload exists since API 1 but declares a checked exception, so the
    // try/catch is mandatory to compile. "UTF-8" is guaranteed present on
    // every JVM, so the catch branch is unreachable.
    buffer
      ..writeln()
      ..writeln('    private static String encodeRouteParam(String value) {')
      ..writeln('        try {')
      ..writeln(
        '            return java.net.URLEncoder.encode(value, "UTF-8");',
      )
      ..writeln('        } catch (java.io.UnsupportedEncodingException e) {')
      ..writeln('            throw new AssertionError(e);')
      ..writeln('        }')
      ..writeln('    }');
  }
}

String _nativeRouteHandlerBody(List<RouteDefinition> routes) {
  final buffer = StringBuffer()
    ..writeln('/**')
    ..writeln(' * Base class for handling native routes pushed from Flutter.')
    ..writeln(' *')
    ..writeln(
      ' * Extend it and implement the typed {@code on*} methods; register the',
    )
    ..writeln(
      ' * instance with {@code InlayNavigator.INSTANCE.setNativeRouteHandler(...)}.',
    )
    ..writeln(' */')
    ..writeln(
      'public abstract class NativeRouteHandler implements co.leancode.inlay.NativeRouteHandler {',
    )
    ..writeln()
    ..writeln('    @Override')
    ..writeln('    @SuppressWarnings("unchecked")')
    ..writeln(
      '    public void handle(Context context, PageSettings route, Function1<Object, Unit> completion) {',
    )
    ..writeln('        final String remote = route.getSchemaFingerprint();')
    ..writeln(
      '        if (remote != null && !remote.equals(InlaySchema.FINGERPRINT)) {',
    )
    ..writeln('            throw new IllegalStateException(')
    ..writeln(
      '                    "Inlay schema mismatch: the Flutter module sent a route generated "',
    )
    ..writeln(
      '                            + "from schema " + remote + ", but this host was built against schema "',
    )
    ..writeln(
      '                            + InlaySchema.FINGERPRINT + ". Re-run inlay_gen and rebuild both sides "',
    )
    ..writeln(
      '                            + "from the same schema revision.");',
    )
    ..writeln('        }')
    ..writeln('        switch (route.getRouteId()) {');

  for (final route in routes) {
    final methodName = methodNameFromClassName(route.className);
    final decodedPage =
        '${route.className}.fromList((List<Object>) route.getParams())';
    buffer.writeln('            case ${route.className}.ROUTE_NAME:');
    if (route.resultType != null) {
      // Developer completes with the typed result; we encode it for the wire.
      buffer.writeln(
        '                $methodName($decodedPage, context, result -> completion.invoke(${route.className}.encodeResult(result)));',
      );
    } else {
      // No result type: complete with null once the handler is invoked.
      buffer
        ..writeln('                $methodName($decodedPage, context);')
        ..writeln('                completion.invoke(null);');
    }
    buffer.writeln('                break;');
  }

  buffer
    ..writeln('            default:')
    ..writeln('                onUnknownRoute(route, context);')
    ..writeln('                completion.invoke(null);')
    ..writeln('                break;')
    ..writeln('        }')
    ..writeln('    }')
    ..writeln();

  for (final route in routes) {
    final methodName = methodNameFromClassName(route.className);
    final result = route.resultType;
    if (result != null) {
      buffer.writeln(
        '    public abstract void $methodName(${route.className} page, Context context, Consumer<${dartTypeToJava(result)}> completion);',
      );
    } else {
      buffer.writeln(
        '    public abstract void $methodName(${route.className} page, Context context);',
      );
    }
  }

  buffer
    ..writeln()
    ..writeln(
      '    public void onUnknownRoute(PageSettings route, Context context) {',
    )
    ..writeln(
      '        throw new IllegalArgumentException("Unknown route: " + route.getRouteId());',
    )
    ..writeln('    }')
    ..writeln('}');
  return buffer.toString();
}
